### ISSUE TITLE
The changes to client.users() API has some missing test coverage

### ISSUE THREAD

**Issue by potrebic** [box/box-python-sdk#100]
Unless I'm mistaken the test_users_return_the_correct_user_objects() test isn't covering calling users() without any params. Code just calling:

```
clients.user()
```

isn't covered. What this means is that someone could change the production code to some combination of this:

```
def users(self, limit=-1, offset=-1, filter_term=''):
     ...
```

And all tests would continue to pass... even though the change introduces a bug. I suggest that when params have defaults we should have test coverage verifying expected behavior when those defaults are relied upon. I wouldn't be surprised if we're missing this sort of coverage in other places. I just looked at group.membership() tests... and this sort of test is missing there as well.

**Comment by carycheng** [comment]
Fixed in #398
