### ISSUE TITLE
Enterprise Issues? Missing Documentation?

### ISSUE THREAD

**Issue by csduarte** [box/box-python-sdk#101]
Hello,

I'm working with the library to manage a large enterprise account. I've created a test account to play with, and having a difficult time making any relevant steps. This may have to do with the settings of the box account itself, but I've exhausted the variations of settings.

Using the standard OAuth authentication works, but inevitably runs into insufficient privileges when trying to modify other users, despite being the admin. The JWT method of auth seems to the way to go, but fails when the permissions are set to standard box users. When I set the account to manage app users, it works, but can not manage the standard box users at that point.

Basic Script:
```
# coding: utf-8
from boxsdk import JWTAuth

def store_tokens(access_token, refresh_token):
    # store the tokens at secure storage (e.g. Keychain)
    return

auth = JWTAuth(
    client_id                       =   "...",
    client_secret                   =   "...",
    enterprise_id                   =   "...",
    rsa_private_key_file_sys_path   =   "./key.pem",
    store_tokens                    =   store_tokens,
)

access_token = auth.authenticate_instance()

from boxsdk import Client

client = Client(auth)
```

The error is...
```
Message: {"error":"invalid_scope","error_description":"Unsupported \"scope\": manage_app_users"}
```
Which seems obvious, but I don't want to manage app users, I want to manage the standard box users, which is why the settings are set as so in the developer portal.

So my questions are, is there something I'm missing from the readme? the portal? the api docs? I've combed through most of it looking for a solution.

Thank you.

**Comment by jmoldow** [comment]
You're right that JWTAuth is for managing app users, not standard box users. So that's not the way to go.

> Using the standard OAuth authentication works, but inevitably runs into insufficient privileges when trying to modify other users, despite being the admin.

This is the real problem. Can you show a code sample and stack trace / server response that demonstrates that problem?

Do other admin-only endpoints also fail for you (such as `Client.users()`), or do other ones work?

**Comment by csduarte** [comment]
Thank you for the response.

Here is the script I'm running for the standard OAuth...
```
from boxsdk import Client, OAuth2

oauth = OAuth2(
    client_id="...",
    client_secret="...",
    access_token="..."
)

client = Client(oauth)

me = client.user(user_id='me').get()
print me # Works!

# client.folder(folder_id='0').create_subfolder('test') # works!

users = client.users()

for user in users:
    print user['name']
    main_folder = client.as_user(user).folder(folder_id='0').get()
```

Result:
```
python test0.py
<boxsdk.object.user.User object at 0x108b7ecd0>
Ned Stark
Traceback (most recent call last):
  File "test0.py", line 20, in <module>
    main_folder = client.as_user(user).folder(folder_id='0').get()
  File "/usr/local/lib/python2.7/site-packages/boxsdk/object/item.py", line 126, in get
    return super(Item, self).get(fields=fields, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/boxsdk/object/base_object.py", line 105, in get

    box_response = self._session.get(url, params=params, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 372, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 276, in _prepare_and_send_request
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 360, in _make_request
    self._raise_on_unsuccessful_request(network_response, expect_json_response, method, url)
  File "/usr/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 215, in _raise_on_unsuccessful_request
    context_info=response_json.get('context_info', None),
boxsdk.exception.BoxAPIException:
Message: None
Status: 403
Code: None
Request id: None
Headers: {'Content-Length': '0', 'Age': '0', 'Server': 'ATS', 'Connection': 'keep-alive', 'Date': 'Mon, 28 Dec 2015 18:46:12 GMT', 'WWW-Authenticate': 'Bearer realm="Service", error="ins
ufficient_scope", error_description="The request requires higher privileges than provided by the access token."'}
URL: https://api.box.com/2.0/folders/0
Method: GET
Context info: None
```

**Comment by jmoldow** [comment]
Well, the `users()` call succeeded, so you definitely have admin permissions.

Are you an admin, or a co-admin? I noticed this in the API documentation for `As-User`:

> Note: Admins can use As-User to impersonate any managed users including co-admins. Co-admins can use As-User to impersonate managed users, but cannot impersonate any admin or co-admin. A 403 Forbidden error will be returned.

Are you a co-admin, and is the "Ned Stark" user another admin or co-admin?

If you're not sure, you can do ``print client.user(user_id='me').get(fields=['role']).role`` and ``print user.get(fields=['role']).role``.

You may need to do something like this:

```python
ADMIN_ROLE = 'admin'
COADMIN_ROLE = 'coadmin'

...

my_role = me.get(fields=['role']).role
am_coadmin = my_role == COADMIN_ROLE

...

for user in users:
    try:
        main_folder = client.as_user(user).folder(folder_id='0').get()
    except BoxAPIException as box_api_exception:
        if (box_api_exception.status == 403) and am_coadmin and (user.get(fields=['role']).role in (ADMIN_ROLE, COADMIN_ROLE)):
            continue
        raise
    ...
```

Though it doesn't seem to be documented, perhaps the same restriction exists for co-admins trying to modify other co-admins.

**Comment by csduarte** [comment]
First off, thank you for your efforts. The are helping me move through these issues.

The issue was definitely not roles, as I confirmed in a variety of ways.

I think the issue is with my lack of clicking on extra links, the as-user doc refers to [this article](https://box-content.readme.io/reference#as-user-1)

> To enable this functionality, please contact us with your API key.

My partner is contacting support as we speak. So I'll close this issue, and reopen on the next problem.

Thanks again!
