### ISSUE TITLE
Searching with Metadata Search Filters

### ISSUE THREAD

**Issue by royka** [box/box-python-sdk#104]
Hi,

Trying to use your SDK to search metadata filters and I can't seem to get it to work!

I build up my MetadataSearchFilters like so

    msf = MetadataSearchFilter(template_key='templateName', scope='enterprise')
    msf.add_value_based_filter(field_key='field', value='0')
    # Create a Search Filters obj
    msfs = MetadataSearchFilters()
    msfs.add_filter(msf)

Then try to use them

    client.search(query='test', limit=100, offset=0, metadata_filters=msfs)

Which raises

    BoxAPIException:
    Message: Instance not found for '"template", "scopedKey", "enterprise_553621", "templateName"'
    Status: 404
    Code: instance_tuple_not_found
    Request id: 688585143568b9d9e2af17
    Headers: {'Content-Length': '159', 'Content-Encoding': 'gzip', 'Age': '0', 'Vary': 'Accept-Encoding', 'Server': 'ATS', 'Connection': 'keep-alive', 'Date': 'Tue, 05 Jan 2016 10:40:30 GMT', 'Content-Type': 'application/json'}
    URL: https://api.box.com/2.0/search
    Method: GET
    Context info: None

Any ideas? I have a suspicion its not url encoding the filter correctly

**Comment by royka** [comment]
Ahh seems like my mistake, also would you except a PR that updates the README.rst with examples of metadata searches?

**Comment by Jeff-Meadows** [comment]
Yes, that sounds like a good pr!

**Comment by royka** [comment]
@Jeff-Meadows here you go any thoughs?
https://github.com/box/box-python-sdk/pull/105

**Comment by aryus96** [comment]
Hello,

Looks like there is no more example of metadatas search in the readme or demo/example.py

Thank you

**Comment by mattwiller** [comment]
@aryus96 We'll add some documentation in the near future, but for now here's a quick example:

```python
from boxsdk.object.search import MetadataSearchFilter, MetadataSearchFilters

metadata_search_filter = MetadataSearchFilter(template_key='marketingCollateral', scope='enterprise')
metadata_search_filter.add_value_based_filter(field_key='documentType', value='datasheet')
metadata_search_filter.add_value_based_filter(field_key='clientNumber', value='a123')	
metadata_search_filters = MetadataSearchFilters()
metadata_search_filters.add_filter(metadata_search_filter)

client.search().query('some_query', limit=100, offset=0, metadata_filters=metadata_search_filters)
```

**Comment by carycheng** [comment]
Hey @aryus96, 

We have a pr for this out, please refer to #374 

Thank you and apologies for the inconvenience!
