### ISSUE TITLE
Add support for getting file shared link download URLs

### ISSUE THREAD

**Issue by Frencil** [box/box-python-sdk#110]
The [get_shared_link()](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/item.py#L162) method returns:

```python
return item.shared_link['url']
```

However sometimes there may be a use case for getting a **direct link** to a file, which should also be present in the response from the [Box API](https://box-content.readme.io/reference#create-a-shared-link-for-a-file):

```json
{
    "type": "file",
    "id": "10559150999",
   ...
    "shared_link": {
        "url": "https://foo.box.com/s/7mcmdlavtye5o5i0ue8xmtwh2sx5bv8p",
        "download_url":"https://foo.box.com/shared/static/7mcmdlavtye5o5i0ue8xmtwh2sx5bv8p.png",
    ...
    }
}
```

Currently the Box Python SDK has a common `get_shared_link` method on the `Item` class, and since `download_url` is not a valid attribute for a shared link on a folder this probably should be added *only* in the context of `File`.

I'm beginning to implement this on my fork with the intent to submit back upstream. What seems like the least terrible approach would be to clone the `get_shared_link` method from the `Item` class into the `File` class, rename it `get_download_link` (or `get_download_url`?), and change the return value, but this seems like a lot of code duplication. Is there a better way?

Any recommendations on approaches or proper patterns to stick to would be most appreciated!

**

[Description of one specific use case for this feature](https://community.box.com/t5/Admin-Forum/quot-We-re-sorry-but-we-can-t-preview-zip-files-quot-is/m-p/11336)

**Comment by Jeff-Meadows** [comment]
This probably wasn't the best design decision we've ever made!

I think the best way going forward would be to refactor `get_shared_link()` into `get_shared_link_object()` that does everything except the last line of `get_shared_link()`. Then either expose that as a public method (and use `get_shared_link_object()['download_url']` in your client code) or expose a `get_download_url()` method on `File` that does the same.

**Comment by nehalecky** [comment]
+1 for `.get_download_url()`. 

I'm new to the box python sdk, but glad to see there is engagement! What is the possible status of this feature?

**Comment by Frencil** [comment]
@nehalecky I'm working this up but a pull req is unlikely to be ready for at least a couple of weeks. It will take some time to refactor things properly, including the automated tests, and then it needs to go through the review process before it can be merged.

In the meantime, if you *only* need download URLs instead of regular URLs, you can hand-edit the module at [Item.py#220](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/item.py#L220) from this:

```python
        return item.shared_link['url']
```

To this:

```python
        return item.shared_link['download_url']
```

**Do this at your own risk!** The `download_url` parameter is being returned from the Box API so just returning that instead of `url` should work, but only for files. Folders do not have a `download_url`, and since `get_shared_link()` is defined at the Item level (files *and* folders) making this change in your module will throw an exception when requesting a shared link on a folder.

Since my use case only involves generating shared links to files this was an effective stop gap, but it's a dirty hacky thing to do and I should feel terrible for doing it. You should too, but sometimes the real world is impatient. =)
