### ISSUE TITLE
unicode in BoxException

### ISSUE THREAD

**Issue by jmoldow** [box/box-python-sdk#117]
Currently, `BoxException` is defined like this:

``` python
class BoxException(Exception):
    """
    Base class exception for all errors raised from the SDK.
    """
    def __str__(self):
        return self.__unicode__().encode('utf-8') if PY2 else self.__unicode__()
```

This causes infinite recursion on Python2, because the base class `Exception` (as a subclass of `object`) has a `__unicode__` method that references `__str__`. It is, however, fine in the subclass `BoxAPIException` and `BoxOAuthException`, because they define their own `__unicode__` methods.

And this code will break on Python 3 for the bare `BoxException` class and its subclass `BoxNetworkException`, because by default there is no `__unicode__` method on Python 3 (since it has no meaning in that language).

I've started on a refactor to fix this.

**Comment by mattwiller** [comment]
This has been resolved on `master`, and will be released with v2.0.0
