### ISSUE TITLE
folder get_items as generator

### ISSUE THREAD

**Issue by jheld** [box/box-python-sdk#123]
I think it may be a worthwhile processing and memory enhancement to switch out the list comprehension in the folder get_items [translated_object] to instead be a generator of the translated_object per yield.

I can implement this if you think it would be a good idea.

**Comment by Jeff-Meadows** [comment]
I'm not sure you gain a huge amount of memory from this; you need to keep the entire response object in memory as long as the generator is in scope. Do you have some specific performance issues with `get_items()`?

**Comment by jheld** [comment]
Hey Jeff,
Thanks for the response. Looking further, I didn't realize that this was
not a chunked/streaming content on the network. You're right, the data
would already be in memory.

Then again, do you know of any JSON streaming protocols? This is more of a
list-based structure after all, I assume.

**Comment by Jeff-Meadows** [comment]
I've used [ijson](https://pypi.python.org/pypi/ijson/) before. It's clearly not a drop-in replacement for the builtin `json` library, because the SDK isn't written with streaming responses in mind. However, you could do what you want with a little extra effort.

    from boxsdk import DeveloperTokenClient
    from boxsdk.util.translator import Translator
    import ijson

    class StreamableResponse(object):
        """This class needed to get requests and ijson to work together"""
        def __init__(self, response):
            self._response = response

        def read(self, amt=None):
            return self._response.read(amt, decode_content=True)

    client = DeveloperTokenClient()
    folder_url = '0'
    root_folder_items_response = client.make_request('GET', client.get_url('folders/{0}/items'.format(folder_url)), expect_json_response=False, stream=True)
    items = ijson.items(StreamableResponse(root_folder_items_response.network_response.response_as_stream), 'entries.item')
    translated_items = (Translator().translate(item['type'])(client._session, item['id'], item) for item in items)
    for item in translated_items:
        print item
