### ISSUE TITLE
Help to deal with server_error 107 problem. 

### ISSUE THREAD

**Issue by Janey-Wu** [box/box-python-sdk#127]
Hi Team, when I try to run the demo/example.py , after the browser popup an link, I click "Grant" button , then the redirect link page return http://localhost:8080/?error=server_error&error_description=107 . I do not know how to deal with this problem. I am not sure what I can do or configure . Would you like to do me some favor or provide some possible clue to solve the problem ?
note:
I have set the redirect link as   http://localhost:8080   in the application setting page.

**Comment by jmoldow** [comment]
Does the browser redirect to any other pages, between when you click "Grant" and when you are directed to `http://localhost:8080/?error=server_error&error_description=107` ?

Is the `error_description` always `107`?

Can you try out the `LoggingNetwork` class, and copy/paste all the output from it, as well as the output from bottle (which should look something like this)

```
127.0.0.1 - - [12/Apr/2016 01:10:01] "GET /?state=box_csrf_token_state&code=CODE HTTP/1.1" 200 0
```

To use ``LoggingNetwork``, edit `demo/auth.py` and replace

```python
    oauth = oauth_class(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
    )
```

with

```python
    from boxsdk.network.logging_network import LoggingNetwork
    oauth = oauth_class(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        network_layer=LoggingNetwork(),
    )
```

Finally, can you double-check the URL that is opened in the browser (the one with the "Grant" button on it)? It should look something like ``https://app.box.com/api/oauth2/authorize?state=box_csrf_token_state&response_type=code&client_id=CLIENT_ID&redirect_uri=http%3A%2F%2Flocalhost%3A8080``.

**Comment by jmoldow** [comment]
I believe you are getting this error because your enterprise is not authorized to use the application whose `client_id` you're using.

If you try logging in with a free personal account instead of an enterprise user account, you should be able to complete the login successfully.

I don't know why the error is sent in the redirect_url, instead of being displayed on the Box website. I will try to find out if that is a feature or a bug. Either way, it isn't a problem with the SDK.

**Comment by Janey-Wu** [comment]
Thank for your quick response, I tried use a personal free account, then it works well. Yes ,as you mentioned, it turns out that my enterprise account is not authorized. 

About why the error is sent in the redirect_url, instead of on the Box website, I can provide some clue for you. If I pre loged in with my enterprise account, then the error msg will be sent in the redirect_rul, however if not, then after I log in on the popped up log in page, then I can see the error msg shown on the Box website. Hope can help you a little.
