### ISSUE TITLE
BoxSession._renew_session does not set previously refreshed tokens

### ISSUE THREAD

**Issue by ryphill** [box/box-python-sdk#128]
I am using `CooperativelyManagedOAuth2` so that I can use the same oauth tokens for multiple clients but it seems like refreshed tokens do not get updated in the session if the tokens were refreshed by another client. I have two instances of the oauth class using the same tokens and two clients using one of the instances.

For example, say there are two clients initialized with the same tokens but different `CooperativelyManagedOAuth2` instances. The first client makes a request, sees the access token is expired and refreshes the tokens. The tokens in the first client's oauth instance are updated with the new tokens. The second client then makes a request, sees it's access token is expired and tries to refresh the token. The token is already refreshed so it does not try to refresh them again but then does not replace the old tokens so when client two retries the request it will raise a `BoxAPIException`.

**Comment by jmoldow** [comment]
I think I see the problem, but just in case, can you tell me what version of boxsdk you're currently using?

**Comment by ryphill** [comment]
I am on version 1.5.1

**Comment by jmoldow** [comment]
Bugfix is in #134. Will push a new release to PyPI after that gets merged.

**Comment by jmoldow** [comment]
Fixed in v1.5.2 (https://pypi.python.org/pypi/boxsdk/1.5.2).
