### ISSUE TITLE
No redirect uri

### ISSUE THREAD

**Issue by austintrombley** [box/box-python-sdk#129]
I am getting the following error, I built my app not to have a redirect URL (what / why do i need this).  I don't have a website to redirect to? 

error:

There seems to be a problem with this app.

Don't worry, your files are perfectly safe. Get in touch with Box support to get assistance with this app. We're here to help.

Error: redirect_uri_missing

 Show Error Details
response_type=code
state=box_csrf_token_7V16ob7yWPc8USks
client_id=po1imyvnod3iyl4y.......

**Comment by jmoldow** [comment]
See my recent response in #133
