### ISSUE TITLE
Get event stream position from timestamp

### ISSUE THREAD

**Issue by jheld** [box/box-python-sdk#130]
My app would greatly benefit from getting the stream position at a given timestamp. If I make a change to the account while my app is off, I don't see a way in the docs to determine which event stream position I should attach to for my long poll thread. If I have a UNIX timestamp, can I get a matching stream position?

**Comment by jmoldow** [comment]
Hi @jheld 

Unfortunately, the backend that powers the events API is not optimized for this type of scenario. It is mostly focused on getting events to you as quickly as possible, and providing a stream of events that delivers you every event at least once. It is not architected to have a perfect history of your events, or to look back to a particular moment in time.

Instead, what you should do is write your own method for pulling events, and also keep track of the latest stream position. Then, at certain checkpoints in your code, when you've persisted the events or their effects, you can also persist the stream position. That way, after an application restart, you can start by reading the events you haven't yet processed.

In the future, we hope to provide a more customizable method for doing this. For now, you can write your own method that looks something like this:

```python
    def generate_events_with_long_polling(events, stream_position=None, stream_type=UserEventsStreamType.ALL):
        stream_position = stream_position if stream_position is not None else events.get_latest_stream_position(stream_type=stream_type)
        yield [], stream_position
        while True:
            options = events.get_long_poll_options(stream_type=stream_type)
            while True:
                try:
                    long_poll_response = events.long_poll(options, stream_position)
                except Timeout:
                    break
                else:
                    message = long_poll_response.json()['message']
                    if message == 'new_change':
                        next_stream_position = stream_position
                        events = []
                        for event, next_stream_position in events._get_all_events_since(stream_position, stream_type=stream_type):
                            events.append(event)
                        yield events, next_stream_position
                        stream_position = next_stream_position
                        break
                    elif message == 'reconnect':
                        continue
                    else:
                        break
```
