### ISSUE TITLE
ImportError: Cannot import name EnumMeta

### ISSUE THREAD

**Issue by tardis89** [box/box-python-sdk#131]
I am getting an import error when I try and run the box-python-sdk. When I run example.py or a simple script, I get the following error: 'ImportError: cannot import name EnumMeta'

> Traceback (most recent call last):
>   File "example.py", line 5, in <module>
>     from boxsdk import Client
>   File "/usr/local/lib/python2.7/dist-packages/boxsdk-1.5.1-py2.7.egg/boxsdk/__init__.py", line 6, in <module>
>     from .client import *  # pylint:disable=wildcard-import,redefined-builtin
>   File "/usr/local/lib/python2.7/dist-packages/boxsdk-1.5.1-py2.7.egg/boxsdk/client/__init__.py", line 5, in <module>
>     from .client import Client
>   File "/usr/local/lib/python2.7/dist-packages/boxsdk-1.5.1-py2.7.egg/boxsdk/client/client.py", line 12, in <module>
>     from ..object.events import Events
>   File "/usr/local/lib/python2.7/dist-packages/boxsdk-1.5.1-py2.7.egg/boxsdk/object/events.py", line 9, in <module>
>     from boxsdk.util.enum import ExtendableEnumMeta
>   File "/usr/local/lib/python2.7/dist-packages/boxsdk-1.5.1-py2.7.egg/boxsdk/util/enum.py", line 8, in <module>
>     from enum import EnumMeta
> ImportError: cannot import name EnumMeta

I have enum installed along with the boxsdk. I am running python 2.7 and am running boxsdk-1.5.1-py2.7.egg.

**Comment by jmoldow** [comment]
What version of `enum34` do you have installed? (``pip show enum34``).

Can you open a python shell and run

```python
import enum
print enum
print enum.EnumMeta
```

**Comment by tardis89** [comment]
I am running enum34 version 1.1.4

My output is below:
```
Python 2.7.3 (default, Jun 22 2015, 19:43:34) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> print enum
<module 'enum' from '/usr/local/lib/python2.7/dist-packages/enum-0.4.6-py2.7.egg/enum.pyc'>
>>> print enum.EnumMeta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'EnumMeta'
>>> 

```

**Comment by jmoldow** [comment]
It looks like you also have ``https://pypi.python.org/pypi/enum`` installed, at version 0.4.6, which is superseding your install of ``enum34``. You'll need to uninstall ``enum``.

**Comment by tardis89** [comment]
Wow! Thanks! Looks like that was it. A simple uninstall of enum did the trick.
