### ISSUE TITLE
rsa_private_key_passphrase must be documented as only accepting byte strings

### ISSUE THREAD

**Issue by alanwill** [box/box-python-sdk#142]
The `cryptography` library documents that `rsa_private_key_passphrase` must be a `bytes` object: https://cryptography.io/en/latest/hazmat/backends/interfaces/?highlight=load_pem_private_key#cryptography.hazmat.backends.interfaces.PEMSerializationBackend.load_pem_private_key.

Right now, our documentation says `str`.

Original bug report:

Trying to get an access token generated using JWTAuth but failing with the following error stack:

```
From cffi callback <function _pem_password_cb at 0x10c09a230>:
Traceback (most recent call last):
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 95, in _pem_password_cb
    pw_buf[:len(ud.password)] = ud.password
ValueError: right operand length must match slice length
Traceback (most recent call last):
  File "boxtest.py", line 21, in <module>
    rsa_private_key_passphrase = boxPrivateKeyPassphrase
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/boxsdk/auth/jwt_auth.py", line 102, in __init__
    backend=default_backend(),
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 289, in load_pem_private_key
    return b.load_pem_private_key(data, password)
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1069, in load_pem_private_key
    password,
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1265, in _load_key
    self._handle_key_loading_error()
  File "/Users/alan/.virtualenvs/myapp/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1337, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.
```

My code is:

```
# coding: utf-8
from __future__ import (absolute_import, division, print_function, unicode_literals)

from boxsdk import JWTAuth
import random
import string

boxClientId = "xxx"
boxClientSecret = "xxx"
boxEnterpriseId = "xxx"
boxJwtKeyId = "xxx"
boxPrivateKeyPath = "private_key.pem"
boxPrivateKeyPassphrase = "xxx"

auth = JWTAuth(
    client_id = boxClientId,
    client_secret = boxClientSecret,
    enterprise_id = boxEnterpriseId,
    jwt_key_id = boxJwtKeyId,
    rsa_private_key_file_sys_path = boxPrivateKeyPath,
    rsa_private_key_passphrase = boxPrivateKeyPassphrase
)

access_token = auth.authenticate_instance()

print(access_token)
```

And the modules I have installed are:

```
boxsdk (1.5.3)
cffi (1.6.0)
cryptography (1.3.2)
ecdsa (0.13)
enum34 (1.1.6)
future (0.15.2)
idna (2.1)
ipaddress (1.0.16)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
PyJWT (1.4.0)
python-jose (0.6.1)
requests (2.10.0)
requests-toolbelt (0.6.2)
setuptools (18.2)
six (1.10.0)
wheel (0.24.0)
```

Any idea what I'm doing wrong here? I've triple checked my parameters and they are all correct but it looks like it's failing on something related to the passphrase size. I've tried both long and short/simple passphrases to no avail. Also generating the keys using:

`openssl genrsa -aes256 -out private_key.pem 2048`
and
`openssl rsa -pubout -in private_key.pem -out public_key.pem`

**Comment by jmoldow** [comment]
The first `ValueError` is coming from here in the `cffi` library: https://bitbucket.org/cffi/cffi/src/default/c/minibuffer.h#minibuffer.h-59

Which is being invoked from here in the `cryptography` library: https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L96

In the `cffi` code, `PyObject_AsReadBuffer(other, &buffer, &buffer_len)`, it looks like `buffer_len` is set to be greater than `len(other)` when `other` is a Python `unicode` object.

I don't know if this is a bug in `cffi`, or a bug in `cryptography`, or if it isn't a bug.

You can fix it in your code by using `boxPrivateKeyPassphrase = b"xxx"` instead (without the leading `b`, it is a `unicode` string because you are using `unicode_literals`).

**Comment by jmoldow** [comment]
Looks like `cffi` and `cryptography` both document that this needs to be a bytestring:

https://cryptography.io/en/latest/hazmat/backends/interfaces/?highlight=load_pem_private_key#cryptography.hazmat.backends.interfaces.PEMSerializationBackend.load_pem_private_key

http://cffi.readthedocs.io/en/latest/ref.html?highlight=buffer#ffi-buffer-ffi-from-buffer

So our documentation must be updated to say that this must be a `bytes` object (`str` on Python 2).

**Comment by Jeff-Meadows** [comment]
https://github.com/box/box-python-sdk/blob/master/boxsdk/auth/jwt_auth.py#L60

Our docs actually do say this: `Passphrase used to unlock the private key. Do not pass a unicode string - this must be bytes.`

**Comment by Jeff-Meadows** [comment]
Should we change the type from `str` to `six.binary_type`?

Most of our docstrings refer to the Python 2 types (eg `unicode`). Should we overhaul this?

**Comment by alanwill** [comment]
Thanks @jmoldow adding the `b` did it. Been banging my head on this for weeks and such a simple fix. Much appreciated!

**Comment by alanwill** [comment]
For what it's worth IMHO, I think if you convert the unicode to bytes on behalf of the user, it'll be more intuitive especially given the fact that all the other parameters passed are in unicode so it's not immediately obvious that only the passphrase should be in bytes.

**Comment by jmoldow** [comment]
That might not be what we want.

I played around with `openssl genrsa` a bit more. It seems that the passphrase (which can be specified in a number of ways: stdin, or a file, or the command line, or an env variable) can be any sequence of bytes. Not only can the passphrase be ASCII, but it can also be a utf-8 encoded non-ASCII string, or a latin-1 encoded non-ASCII string, etc. If the passphrase happens to be non-ASCII, and wasn't encoded with utf-8, then we won't be able to auto-encode to `bytes`.

No matter what, we should enhance the documentation to say that `bytes` is required. Beyond that, our options are:
1) Do nothing else.
2) Raise a `TypeError` with a helpful message, if the passphrase is not `bytes` (or `str` on python 2).
3) If the passphrase is `unicode`, attempt to encode to `bytes` with encoding `ascii`. If that fails, raise our own `TypeError` with a helpful message.
4) If the passphrase is `unicode`, attempt to encode to `bytes` with encoding `utf-8`. If that fails, raise our own `TypeError` with a helpful message.

3) Would be a nice thing to do, for the benefit of those out there (ourselves included!) that use `unicode_literals`. I could maybe be convinced to do 4), but I lean against it. I think I'd prefer the user do their own encoding: they know best what their passphrase is.

Re @Jeff-Meadows 
> Should we change the type from str to six.binary_type?
>
> Most of our docstrings refer to the Python 2 types (eg unicode). Should we overhaul this?

I don't think changing `unicode` is necessary at this time. We talked about this a while ago, and I think we decided that `unicode` was clear enough, even if it is technically nonsensical on Python 3. We could overhaul this if we wanted to, but it's probably not necessary in response to this issue.

Given that we're using `unicode` to mean the Python text type (where `unicode` doesn't exist on Python 3, but is actually `str`), I think the analogous thing to do here would be to use `bytes` to mean the Python byte string type (where `bytes` doesn't exist on Python 2, but is actually `str`). And then we'd use `str` in the circumstances where the function requires a native string (`str` on both Python 2 and 3).

**Comment by rusiyo** [comment]
I'm also having this same issue, although it doesn't occur on 100% of the times I use JWTAuth. I've seen this issue intermittently, but the stack trace is exactly like the one posted by @alanwill

**Comment by Inetgate** [comment]
Hi! I am experiencing similar issue.
Here is my code: 
`import yaml
import requests
from boxsdk import Client
from boxsdk import JWTAuth
CLIENT_ID = None
CLIENT_SECRET = None
ENTERPRISE_ID = None
JWT_KEY_ID = None
RSA_KEY_PATH = None
RSA_PASSPHRASE = None
with open('getboxfile2.yml', 'r') as ymlfile:
    cfg = yaml.load(ymlfile)
    CLIENT_ID      = cfg['box']['client_id']
    CLIENT_SECRET  = cfg['box']['client_secret']
    ENTERPRISE_ID  = cfg['box']['enterprise_id']
    JWT_KEY_ID     = cfg['box']['jwt_key_id']
    RSA_KEY_PATH   = cfg['box']['rsa_private_key_file_sys_path']
    RSA_PASSPHRASE = cfg['box']['rsa_private_key_passphrase']
auth = JWTAuth(
  client_id=CLIENT_ID,
  client_secret=CLIENT_SECRET,
  enterprise_id=ENTERPRISE_ID,
  jwt_key_id=JWT_KEY_ID,
  rsa_private_key_file_sys_path=RSA_KEY_PATH,
  rsa_private_key_passphrase=RSA_PASSPHRASE
)
access_token = auth.authenticate_instance()
client = Client(auth)
`
When I enter auth = JWTAuth( ...snip...), I get below traceback
`Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/local/lib/python3.6/site-packages/boxsdk/auth/jwt_auth.py", line 104, in __init__
    backend=default_backend(),
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1015, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1202, in _load_key
    raise TypeError("Password must be bytes")
TypeError: Password must be bytes
`
I try to change in /usr/local/lib/python3.5/dist-packages/boxsdk/auth/jwt_auth.py from 'key_file.read()' to 'bytes(key_file.read())', but I encounter same issue.

Also, I try to change b'' in conf file, but issue is not cleared.
