### ISSUE TITLE
Make the error code accessible in BoxOAuthException 

### ISSUE THREAD

**Issue by ryphill** [box/box-python-sdk#145]
In the `BoxOAuthException`, both the error code and error description are both stored in a stringified dictionary. This makes it so that in order check if the oauth exception is an `invalid_request` one would have to do `'invalid_request' in oauth_exception._message` instead of something like `'invalid_request' == oauth_exception.code`.

The `BoxAPIException` separates and exposes the error code and description, it seems like it could be useful to do the same for `BoxOAuthException`.

**Comment by mattwiller** [comment]
This has been resolved on `master`, and will be released with v2.0.0
