### ISSUE TITLE
Using 'now' with generate_events_with_long_polling

### ISSUE THREAD

**Issue by ryphill** [box/box-python-sdk#146]
I'm not sure if this is a bug or just a documentation issue, but if I do `generate_events_with_long_polling(stream_position='now')` I get this api exception:

```
BoxAPIException:
Message: None
Status: 400
Code: None
Request id: None
Headers: {'Content-Length': '0', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'private, no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0'}
URL: https://2.realtime.services.box.net/subscribe?channel=7b0eb546a3e3392fa217&stream_type=all
Method: GET
Context info: None
```

Since `now` is supposed to be a special case for the current stream position it seems like should work the same as doing `generate_events_with_long_polling()`.

I am using version 1.5.2 of the box python sdk.

**Comment by mattwiller** [comment]
I confirmed this appears to be an SDK issue; the SDK does not appear to correctly handle a `stream_position` value of `'now'`.  We'll take a look and fix this on the v2.x branch
