### ISSUE TITLE
"'NoneType' object is not callable" when running on Lambda

### ISSUE THREAD

**Issue by alanwill** [box/box-python-sdk#148]
I'm trying to get this to successfully run in an AWS Lambda function and keep getting the error:

```
Traceback (most recent call last):
  File "handler.py", line 27, in <module>
    rsa_private_key_passphrase = boxPrivateKeyPassphrase
TypeError: 'NoneType' object is not callable
```

The area where it's failing is:

```
    enterpriseAuth = JWTAuth(
        client_id=boxClientId,
        client_secret=boxClientSecret,
        enterprise_id=boxEnterpriseId,
        jwt_key_id=boxJwtKeyId,
        rsa_private_key_file_sys_path=boxPrivateKeyPath,
        rsa_private_key_passphrase=boxPrivateKeyPassphrase
    )
```

I could duplicate it on an EC2 instance with modules packaged with the script in a vendored directory. 

```
.
├── boxsdk
│   ├── auth
│   ├── client
│   ├── network
│   ├── object
│   ├── session
│   └── util
├── boxsdk-1.5.3.dist-info
├── enum
├── enum34-1.1.6.dist-info
├── idna
├── idna-2.1.dist-info
├── ipaddress-1.0.16.dist-info
├── jwt
│   └── contrib
├── pkg_resources
│   ├── extern
│   └── _vendor
├── pyasn1
│   ├── codec
│   ├── compat
│   └── type
├── pyasn1-0.1.9.dist-info
├── pycparser
│   └── ply
├── pycparser-2.14.egg-info
├── PyJWT-1.4.0.dist-info
├── requests
│   └── packages
├── requests-2.10.0.dist-info
├── requests_toolbelt
│   ├── adapters
│   ├── auth
│   ├── cookies
│   ├── downloadutils
│   ├── multipart
│   ├── threaded
│   └── utils
├── requests_toolbelt-0.6.2.dist-info
├── setuptools
│   ├── command
│   └── extern
├── setuptools-24.0.2.dist-info
└── six-1.10.0.dist-info
```

The only way to get it to work on EC2 is by `sudo pip install boxsdk[jwt]` on the system packages after installing a number of dependencies like libffi-devel, gcc and openssl-devel. 

So does anyone know what's missing that I could bundle with the function into Lambda in order to get this working?

**Comment by jmoldow** [comment]
See https://github.com/box/box-python-sdk/blob/master/boxsdk/auth/__init__.py#L10 .

`JWTAuth` is only defined if its dependencies are available (which you get with `pip install boxsdk[jwt]`). If you're using a Python `virtualenv`, you should make sure these dependencies are installed into your `virtualenv` with `pip`. If you're running directly with the system's python, you'll need `sudo pip`.

Compiling the `cryptography` dependency on Linux does require `libffi-devel`, `gcc` and `openssl-devel`: https://github.com/pyca/cryptography/blob/master/docs/installation.rst#building-cryptography-on-linux

I don't know anything about Lambda, so I don't know what would be different about getting it to work on Lambda, as opposed to EC2. In the directory tree you posted, I don't see `cryptography`, which is probably why `JWTAuth` isn't able to be imported and defined.

**Comment by alanwill** [comment]
Turns out the reason this isn't working is due to a limitation in Lambda that prevents a consumer from installing packages in the container.

**Comment by dynamatic** [comment]
Hi Alan,

I am running into the same issue, the only difference is I am getting this error on my mac. Could you please elaborate how you have resolved the issue?

**Comment by manemsiva** [comment]
Installed below commnd:
pip install "boxsdk[jwt]"
