### ISSUE TITLE
Headless OAuth

### ISSUE THREAD

**Issue by csduarte** [box/box-python-sdk#152]
Hi,

I'd like to run an action in a CLI tool. I've used your examples to create a browser popup to complete the oauth. As well as an input of token generated in the developer console.

But I'd like to do this long running on a machine that I'm ssh'd into and won't have the ability to go to the browser. If I go with the token, I'm limited to 1 hour.

Is there any way to achieve this? Hopefully without using something like PhatomJS to fill in the user credentials and pressing accept...

**Comment by Jeff-Meadows** [comment]
Hi Chris. You've got 2 options:

1. Use the browser to complete oauth. This will generate an access token and a refresh token. If you start your app with both tokens, it will run indefinitely, as long as it makes one request every so often (to avoid refresh token expiry, which happens about once every 2 months).
2. Use app users. Create an app user and collaborate it into the content you need to access with your script.
