### ISSUE TITLE
Can we specify the fields we want when fetch object list?

### ISSUE THREAD

**Issue by likel** [box/box-python-sdk#153]
Hi, 
When I ingest a list of folder or files, I want to specify the fields to returned, Is that possible?Thanks.

**Comment by Jeff-Meadows** [comment]
Hi, I assume you are talking about the `folder.get_items()` method?

It takes an optional `fields` parameter, which you can use to pass a list of field names.

**Comment by likel** [comment]
@Jeff-Meadows Not only `folder.get_items()`. We can only ingest a list of items via `folder.get_items()` so far. But we have many other  objects such as user, group, comment, task etc. So for these objects, do we have any plan to add the `get_items()` ? I can see we have these APIs from [https://docs.box.com/reference](https://docs.box.com/reference). Thanks.

**Comment by jmoldow** [comment]
Hi @likel 

We will eventually add those in, but we don't have concrete plans yet.

Until somewhat recently, some of those endpoints were incorrectly documented, saying that they returned all results, when actually they were paging endpoints. This caused us to accidentally create non-paging methods for some of those. For example, see https://github.com/box/box-python-sdk/blob/master/boxsdk/client/client.py#L231 , which claims to return all groups. When actually, the endpoint is (now) documented as being a paging endpoint (https://docs.box.com/reference#groups).

Box also has plans to add a better paging mechanism to its endpoints. You can see this in some of the newer paging endpoints, for example https://docs.box.com/reference#get-device-pins . Before this becomes available, we don't want to jump the gun and write a method that would be backwards incompatible with the new paging mechanism.

I think we could probably come up with a good mechanism that supports both limit/offset, and the upcoming paging mechanism. And if we do that, then we can implement these methods whenever we want. But we haven't had a chance to sit down and design that yet.

For now, if you need to use those endpoints, you can construct your own calls, with `client.make_request()`.

**Comment by likel** [comment]
@jarmallen Really thanks your reply. In fact I implemented that functionality via `client.make_request()` now. In other words, I gave up the high level api provided by sdk. I'm happy if you guys can add these API to SDK. I'm also pleased to contribute code. Thanks again for your kindness.
