### ISSUE TITLE
Censor secrets from logs and exception tracebacks

### ISSUE THREAD

**Issue by jmoldow** [box/box-python-sdk#164]
Information such as:
- client_id
- client_secret
- access_token
- refresh_token
- (less important) names, emails, descriptions, and shared links

should be censored or truncated when logged or put into exception tracebacks. That way, users who copy/paste this information don't risk exposing this sensitive information.

A social solution to this, would be to create a template for Github issues, instructing users to self-censor before copy/pasting anything into Github. https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by mattwiller** [comment]
This has been resolved on `master`, and will be released with v2.0.0
