### ISSUE TITLE
Any way to upload a file with description? Or update a file to add one?

### ISSUE THREAD

**Issue by AzRu** [box/box-python-sdk#171]
Looks like the API doesn't allow a description to be added on upload so I'm not expecting this to be possible in the SDK (https://docs.box.com/reference#upload-a-file)

But I do see that a description can be added with an update (https://docs.box.com/reference#update-a-files-information), however I can't find a method that allows that in the code for the SDK

**Comment by Jeff-Meadows** [comment]
Hi @AzRu you're right, the SDK can't support anything the API doesn't support.

While the SDK doesn't offer a method specific to file description, each `BaseObject` (of which `File` is a subclass) has an `update_info` method. So you can update the description like this:

    updated_file = file_object.update_info({'description': 'new description'})

**Comment by AzRu** [comment]
Thanks for the quick response!
