### ISSUE TITLE
Change authenticate_app_user method 

### ISSUE THREAD

**Issue by spadval** [box/box-python-sdk#174]
With service accounts, you can use the method to authenticate as a managed user, not just app users. Should the method name be changed to better reflect this?

Also we should changed the name from Box Developer Edition to Box Platform (or even Box service accounts)

**Comment by jmoldow** [comment]
@spadval I was actually preparing to push a PR to do exactly that. 😃

**Comment by jmoldow** [comment]
This change is now in v2.0.0a3 (https://pypi.python.org/pypi/boxsdk/2.0.0a3).
