### ISSUE TITLE
Add more detailed documentation and examples for RemoteOAuth2

### ISSUE THREAD

**Issue by jheld** [box/box-python-sdk#179]
Could I get an example snippet for how this type of RemoteOAuth2 client is used? I understand that I'll need a secondary server (or process), to do most of the oauth2 dance, but I'd love to see how the client and this secondary server code should actually look. The README only barely mentions this workflow.

**Comment by jmoldow** [comment]
Sorry for the lack of documentation.

Here's a very simple example, using a single process with two instances of the SDK:

```python

class IntraProcessRemoteOAuth2(RemoteOAuth2):
    def __init__(self, auth_object, **kwargs):
        super(IntraProcessRemoteOAuth2, self).__init__(
            retrieve_access_token=self._retrieve_access_token_auth_object,
            **kwargs
        )
        self._auth_object = auth_object

    def _retrieve_access_token_auth_object(self, access_token_to_refresh):
        access_token, _ = self._auth_object.refresh(access_token_to_refresh)
        return access_token

normal_oauth2_object = OAuth2(...)
remote_oauth2_object = IntraProcessRemoteOAuth2(normal_oauth2_object)
```

If `remote_oauth2_object.refresh()` is called, it will actually perform refresh within `normal_oauth2_object`.

If `normal_oauth2_object.refresh()` is called, `remote_oauth2_object` will still have its old (and now invalid) access token. But next time `remote_oauth2_object.refresh()` is called (which will be done when `BoxSession` realizes that the access token is invalid), it will grab the new access token from `normal_oauth2_object`.

**Comment by jheld** [comment]
@jmoldow that makes sense, and from a local dev testing perspective (if I don't have a live remote server up and running), would work fairly well.

What if the remote is actually on another server, then? I imagine, there would be a RESTful call issued, but it is a bit vague to me still how that flow goes.

I appreciate you taking the time to write these out!

**Comment by jmoldow** [comment]
You need a function that takes the current access token and makes the RESTful call with the access token somewhere in the payload. The response from the server should include the latest access token, and the function should return that access token. Finally, you'll need to pass that function as the `retrieve_access_token` callable in `__init__()`.

Of course, you'll need to manage that REST endpoint securely. You don't want to be handing out access tokens to anyone that asks...

**Comment by jheld** [comment]
I'm sorry for the incessant messages here; this just happens to be the application that I'm learning much of Oauth2 through.

If the user is logging in for the first time, they wouldn't have an `access_token`, yet, so I'm under the assumption that I'd need to ask the server for the `authorization_url`...and use (presumably, as is defined in my dev app console) `localhost` for the redirect_url that is needed to get the access and refresh tokens. So, the user's client will open the URL, sign in, grant access, get the access and refresh tokens, and then need to store them per usual.

It doesn't seem like the current RemoteOAuth2 handler has general support for this workflow -- only the stored tokens callback.

And this is fine, I suppose. I'm mostly just trying to make sure this workflow is correct.

in terms of handing out access tokens, because I'd be forcing the user's client to go through the sign in workflow itself, I think that part is safe.

For the case where the user has these tokens (already logged in), I'd probably be storing an additional secret value from each client, to be sure that only it can make requests with those tokens. Seems reasonable?
