### ISSUE TITLE
Can not authenticate

### ISSUE THREAD

**Issue by thanhngvpt** [box/box-python-sdk#182]
Hi Box Team.
I've try to use your sdk with this code https://dpaste.de/kO5w but i receive this error `Message: b'{"error":"invalid_request","error_description":"No \\"refresh_token\\" parameter found"}'
Status: 400` Please help me how can i authenticate with box
Many thanks.

**Comment by jmoldow** [comment]
You're passing the `access_token` as the third positional argument, but the third positional argument is not `access_token`.

You must use `access_token=access_token`.
