### ISSUE TITLE
Tokens not refreshing? (v1.5.3)

### ISSUE THREAD

**Issue by AzRu** [box/box-python-sdk#188]
I have this in my code that does the initial auth and stores the tokens in the keyring. This should only happen once since I store the tokens.
```
def check_box_auth():
    auth_token = keyring.get_password('BOX_AUTH', 'XXXXXXXX')
    if not auth_token:
        oauth = OAuth2(
            client_id=app.config['BOX_CONFIG']['client_id'],
            client_secret=app.config['BOX_CONFIG']['client_secret'],
            store_tokens=store_box_tokens
        )
        auth_url, csrf_token = oauth.get_authorization_url(app.config['BOX_CONFIG']['redirect_url']) # this opens the link which authorizes it
...
```
Then in my app, when i need to use the client, I have this. read_tokens gets them from the keyring
```
    def __init__(self, type):
        auth_token, refresh_token = self.read_tokens()
        self.oauth = OAuth2(
            client_id=BOX_CONFIG['client_id'],
            client_secret=BOX_CONFIG['client_secret'],
            access_token=auth_token,
            refresh_token=refresh_token,
            store_tokens=store_box_tokens
        )
        if auth_token:
            self.client = Client(self.oauth)
...
```
However, I've been experiencing issues where it seems like the token doesn't automatically refresh

I get errors like this. The XXXXXXXX is the id of the folder where I'm trying to upload a file. I've resorted to doing a manual token refresh where i trigger the initial auth. Once I do that, it works for a while but I end up seeing the same error again.
```
{u'reason': u'invalid_parameter', u'message': u\"Invalid value 'd_XXXXXXXXXXX'. 'parent' with value 'd_XXXXXXXXXX' not found\", u'name': u'parent'}]}\n"}
```

Any idea why this would happen?

**Comment by AzRu** [comment]
Something that might be the culprit here, is since you don't have thumbnail functionality in the SDK, I'm doing it in a manual way. I use the read_token fn to get the token from the keyring, and then I make a requests call

```
r = requests.get(
            'https://api.box.com/2.0/files/{0}/thumbnail.png?min_height=128&min_width=128'.format(file_id),
            headers={'Authorization': 'Bearer {0}'.format(token)}
        )
```
Maybe I need to do a manual refresh after this?

**Comment by Jeff-Meadows** [comment]
First of all, there is an easier way to do thumbnails - use `client.make_request`.

    client.make_request('GET', client.file(file_id).get_url('thumbnail.png'), params={'min_height': 128, 'min_width': 128})

This will use the client's tokens, and do the automatic refresh.

As to your errors, I'm not sure what's leading you to believe the issue has to do with token refresh. Could you show the code that's doing the file uploads? If you use a `LoggingClient`, it'll output each request and response, and we can diagnose what's going on.

**Comment by AzRu** [comment]
Thanks for your answer, I'll change my code to use that. Before your answer, I implemented this after my python requests GET thumbnail and I haven't seen the problem occur since
```
new_auth_token, new_refresh_token = box.oauth.refresh(access_token_to_refresh=auth_token)
store_box_tokens(new_auth_token, new_refresh_token)
```

As for the error, Initially I took it at face value, but the directory with that value did in fact exist. And I've uploaded to it previously. The upload code works fine. I have a parent directory (the id in the error) and would create a directory under it for each user. It failed at the 2nd line below:

```
box = BoxClient('v3')
box_folder = box.client.folder(folder_id=box_folder_id)

for i, _file in enumerate(files):
    _file = files[_file]
    uploaded_file = box_folder.upload_stream(_file, file_name=name)

...
```

Since the error didn't make sense to me, the box_folder_id was a valid folder and the user uploading had permissions to upload to it, I googled around. Found [this](http://stackoverflow.com/questions/29175004/how-do-i-upload-a-file-using-the-box-api-using-app-credentials) and another link that mentions it's due to an access_token not being valid. So I manually refreshed the tokens in my app and tried again. This time it worked. After about an hour, it stopped working. Your tokens expire after an hour. That's why I was led to believe it's to do with tokens not refreshing.

**Comment by AzRu** [comment]
Maybe I'm doing it wrong, but 
```
box.client.make_request(
            'GET', box.client.file(uploaded_file.id).get_url('thumbnail.png'),
            params={'min_height': 128, 'min_width': 128}
        )
```

where box.client is an instance of Client (same one that uploads the file, which succeeds)
throws this error
```
BoxAPIException: 
Message: Non-json response received, while expecting json response.
Status: 200
Code: None
Request id: None
Headers: {'Content-Length': '2267', 'X-Content-Type-Options': 'nosniff', 'Set-Cookie': '__cfduid=d1c37091726af11bf0a1e267f14017e1a1485279757; expires=Wed, 24-Jan-18 17:42:37 GMT; path=/; domain=.boxcdn.net; HttpOnly', 'CF-Cache-Status': 'HIT', 'Expires': 'Fri, 22 Jan 2027 17:42:37 GMT', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare-nginx', 'Last-Modified': 'Thu, 05 Jan 2017 20:19:17 GMT', 'Connection': 'keep-alive', 'Etag': '"586eaa45-8db"', 'Cache-Control': 'public, max-age=315360000', 'Date': 'Tue, 24 Jan 2017 17:42:37 GMT', 'CF-RAY': '3265487338da27ec-YYZ', 'Content-Type': 'image/gif', 'Accept-Ranges': 'bytes'}
URL: https://api.box.com/2.0/files/126753700045/thumbnail.png
Method: GET
Context info: None
```
