### ISSUE TITLE
example.py oauth bottle doesn't complete auth flow

### ISSUE THREAD

**Issue by prexer** [box/box-python-sdk#201]
I'm building a raspberry pi home-security system.  I want to get my auth and refresh tokens and store them away into a keyfile, but I'm doing this all from cmd-line.  I thought the demo example.py program might do that, but it appears not to work, and not have enough instructions to explain where it is failing.  It would be great if there was a way to have it get the auth and refresh tokens, and then have a #todo to implement code to store them somewhere. 

One thing I noticed. The bottle library seems to kick off the auth for the app just fine, but then fails with a "There seems to be a problem with your app."  I suspect it's the redirect_uri that isn't working, since it might be trying to get back to my laptop or raspberry pi device, but the error msg it gives isn't clear, and the instructions on how to use the example.py or the auth.py don't really explain the 5 steps to hook that last mile up.

This may just need a little bit of documentation in the demo folder or the example.py file about how to set it up.

**Comment by Jeff-Meadows** [comment]
The redirect_uri field in your app's configuration needs to be set to `http://localhost`.

This appears to be a change on Box's side - this worked when the demo was written, but it appears not to work anymore for new apps.

I'll close this after documenting this in the demo folder.
