### ISSUE TITLE
api app user @boxdevedition.com how to confirm?

### ISSUE THREAD

**Issue by danieljao** [box/box-python-sdk#203]
I'm able to create an AppUser_1XXX@boxdevedition.com but after inviting the email to be a collaborator, the api user is still not seeing the folders, do i need to confirm the invite?  is there a way to confirm the invite?

**Comment by jmoldow** [comment]
This question is probably better asked in our API developer forum: https://community.box.com/t5/Developer-Forum/bd-p/DeveloperForum

If I had to hazard a guess, I would assume that you can't add app users as collaborators via their email address. You probably can only add them as collaborators via their user ID.
