### ISSUE TITLE
Python boxsdk[jwt] Post request hangs when body is a StringIO

### ISSUE THREAD

**Issue by jmfrank63** [box/box-python-sdk#213]
The issue comes from the requests library as described here:
https://github.com/requests/requests/issues/2872
boxsdk[jwt] is still using an older version so the fix is not incorporated.
There are two possible solutions:
Upgrade to version of the requests library (could break other things though) or ammend the documentation that the file object has to be a true file object and not a StringIO or ByteIO object.

**Comment by jmoldow** [comment]
We do want uploads to be able to use any io object, including StringIO and BytesIO.

Developers running into this problem can do `string_io.seek(0)` if that is what they want.

Also, you can upgrade the requests library at any point. We don't pin to a specific version of the requests library. You can upgrade your version of requests to get that fix. Anyone who uses a version of requests before that bugfix, will have that bug.
