### ISSUE TITLE
Add support to load app config file downloaded from dev console

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-python-sdk#221]
Add support to jwt_auth.py to load a box_config.json file downloaded from the developer console. This would make the python SDK consistent with the node an java sdk's.

node: https://github.com/box/box-node-sdk/blob/3dcfe69ed1354ed85b54eb4b1d4e179c999f4f99/lib/box-node-sdk.js#L126

java: 
https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxConfig.java
https://github.com/box/box-java-sdk/blob/da3332d77c09f1c75afe93184b2a02bb00e84dd8/src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java#L189

**Comment by paulrentschler** [comment]
I would like to see something like this as well and could create a pull request. With the addition of the `rsa_private_key_data` argument to `JWTAuth.__init__()` this seems possible with a class like:

    class JWTAuthPreConfig(object):
        def __init__(self, config=None, config_file=None, **kwargs):
            # config - a dictionary based on the contents of the box_config.json file
            # config_file - a file-like object containing the contents of box_config.json or a path to the box_config.json file to read
            ### TODO: process config or config_file and create an instance of JWTAuth
            return jwtauth_instance

**Comment by BenMitchell1979** [comment]
Will there be any updates to the documentation on how this works.

**Comment by wgottschalk** [comment]
Follow up to this. Really looking forward to having this. When can we expect the 2.0 release? and how can I help?

**Comment by rpkilby** [comment]
Hi. I see there are still several open items in the v2 milestone. Will v2 be cut on October 31st regardless of those items, or will the release be bumped to a later date? If v2 won't be released next week, would it be possible to create another pre-release (2.0.0a13)? Thanks!

**Comment by Jeff-Meadows** [comment]
@rpkilby v2 is going to be cut next week!

**Comment by mattwiller** [comment]
@rpkilby @wgottschalk The v2.0.0 release has just been cut — please give it a try and let us know if you have any issues!

**Comment by rpkilby** [comment]
Thanks for the hard work.
