### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by sacrophyte** [box/box-python-sdk#238]
Where might I find the documentation? The source files under docs are rather incomplete and don't help much. For instance, how would I find more information about client.file() (which is not even listed in the client source file)? How would I get a file by name instead of by id?

**Comment by jmoldow** [comment]
Our documentation is linked from PyPI: http://box-python-sdk.readthedocs.io/en/stable

> For instance, how would I find more information about client.file() (which is not even listed in the client source file)?

http://box-python-sdk.readthedocs.io/en/stable/boxsdk.client.html#boxsdk.client.client.Client.file

> How would I get a file by name instead of by id?

The SDK only supports functionalities that the API supports. There isn't yet an endpoint for getting a file by name. If you want to do that, you have two options:
- Iterate through all of the items in a folder until you see the name you're looking for.
- Use the search API.
  - https://docs.box.com/reference#searching-for-content
  - http://box-python-sdk.readthedocs.io/en/stable/boxsdk.client.html#boxsdk.client.client.Client.search

**Comment by Jeff-Meadows** [comment]
We should link to the docs at readthedocs in our README. We should link to the code from our docs.

**Comment by mattwiller** [comment]
The [usage docs](./docs/usage) and [ReadTheDocs](http://box-python-sdk.readthedocs.io/en/stable) links have been added to the README.
