### ISSUE TITLE
Requests done with JWT authentication keep returning a 404

### ISSUE THREAD

**Issue by msolano00** [box/box-python-sdk#244]
Hello,

I have been struggling for some days with this issue. At the beginning I thought I was doing something wrong but I think there is something else.

I followed the regular documentation for JWT:

```python
from boxsdk import JWTAuth
from boxsdk import Client

auth = JWTAuth(
    client_id='clientID',
    client_secret='clientSecret',
    enterprise_id='ent_ID',
    jwt_key_id='jwtKey',
    rsa_private_key_file_sys_path='/some/path/.ssh/box_private_key.pem',
    rsa_private_key_passphrase='keyPassphrase',
)

access_token = auth.authenticate_instance()

client = Client(auth)

print client.file(file_id='226905808148').get()['name']
```

Now when running this I get the following error:

```python
boxsdk.exception.BoxAPIException: 
Message: Not Found
Status: 404
Code: not_found
Request id: 37750090159cc237ec9612
Headers: {'Content-Length': '244', 'Content-Encoding': 'gzip', 'Age': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Accept-Encoding', 'Server': 'Server', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store', 'Date': 'Wed, 27 Sep 2017 22:17:34 GMT', 'Content-Type': 'application/json'}
URL: https://api.box.com/2.0/files/226905808148
Method: GET
Context info: {u'errors': [{u'reason': u'invalid_parameter', u'message': u"Invalid value 'f_226905808148'. 'item' with value 'f_226905808148' not found", u'name': u'item'}]}
```

I tried different things including a "hack" which was using the access token to validate an http request:

```python
from boxsdk import JWTAuth
import requests

auth = JWTAuth(
    client_id='clientID',
    client_secret='clientSecret',
    enterprise_id='ent_ID',
    jwt_key_id='jwtKey',
    rsa_private_key_file_sys_path='/some/path/.ssh/box_private_key.pem',
    rsa_private_key_passphrase='keyPassphrase',
)

access_token = auth.authenticate_instance()

headers = {
    'Authorization': 'Bearer ' + access_token,
}

r = requests.get('https://api.box.com/2.0/files/226905808148', headers=headers)

print r.text
```

And I got the following error, that matches the previous error:

```json
{
	"type": "error",
	"status": 404,
	"code": "not_found",
	"context_info": {
		"errors": [{
			"reason": "invalid_parameter",
			"name": "item",
			"message": "Invalid value 'f_226905808148'. 'item' with value 'f_226905808148' not found"
		}]
	},
	"help_url": "http:\/\/developers.box.com\/docs\/#errors",
	"message": "Not Found",
	"request_id": "4462211659cc2829437c9"
}
```

I decided to test the same http method but this time with a token generated from the dev console:

```python
console_token = 'some_dev_console_generated_token'

headers = {
    'Authorization': 'Bearer ' + console_token,
}

r = requests.get('https://api.box.com/2.0/files/226905808148', headers=headers)

print r.text
```

And this seems to be fine:

```json
{
	"type": "file",
	"id": "226905808148",
	"file_version": {
		"type": "file_version",
		"id": "239594515476",
		"sha1": "21c41745877c5ad2a44accec48bdb7cf776f3331"
	},
	"sequence_id": "0",
	"etag": "0",
	"sha1": "21c41745877c5ad2a44accec48bdb7cf776f3331",
	"name": "the_raven.txt",
	"description": "",
	"size": 6877,
	"path_collection": {
		"total_count": 3,
		"entries": [{
			"type": "folder",
			"id": "0",
			"sequence_id": null,
			"etag": null,
			"name": "All Files"
		}, {
			"type": "folder",
			"id": "31850680225",
			"sequence_id": "0",
			"etag": "0",
			"name": "ITCOE"
		}, {
			"type": "folder",
			"id": "31850693387",
			"sequence_id": "0",
			"etag": "0",
			"name": "software"
		}]
	},
	"created_at": "2017-09-20T19:37:52-07:00",
	"modified_at": "2017-09-20T19:37:52-07:00",
	"trashed_at": null,
	"purged_at": null,
	"content_created_at": "2017-05-25T20:29:27-07:00",
	"content_modified_at": "2017-05-25T20:29:27-07:00",
	"created_by": {
		"type": "user",
		"id": "242123783",
		"name": "Marvin Solano",
		"login": "Marvin_Solano@a.com"
	},
	"modified_by": {
		"type": "user",
		"id": "242123783",
		"name": "Marvin Solano",
		"login": "Marvin_Solano@a.com"
	},
	"owned_by": {
		"type": "user",
		"id": "242123783",
		"name": "Marvin Solano",
		"login": "Marvin_Solano@a.com"
	},
	"shared_link": null,
	"parent": {
		"type": "folder",
		"id": "31850693387",
		"sequence_id": "0",
		"etag": "0",
		"name": "software"
	},
	"item_status": "active"
}
```

I generated a test token (`access_token = auth.authenticate_instance()`) with the SDK to test it with Postman and I got the same response.

Any ideas of what I might be doing wrong?

Regards
Marvin

**Comment by jmoldow** [comment]
The token generated from the developer console is different than the JWT token.

The token generated from the developer console acts as if it is coming from your application, but it is authenticated as _your_ Box managed user. It is *not* authenticated as the service account.

The token generated by the SDK is authenticated as the service account.

The service account might not have access to that file. Just like normal Box users, it can only see content that it owns, or that has been collaborated with it.

Alternatively, you can authenticate as an app user to access that app user's content. Or, if your application has the right scopes, the service account can use the `As-User` feature to impersonate another user within the same enterprise, and gain access to that user's content.

**Comment by msolano00** [comment]
Hi @jmoldow, thanks for the super prompt response.

The service account is a collaborator (editor) of the folder containing this file. I tested also displaying a list of the items contained in the folder and also tested displaying the information of the folder, both with the same response from the server.

**Comment by jmoldow** [comment]
@msolano00 Did you create this application by yourself, or did a Box employee do any configuration?

My team ran into a very similar problem yesterday. Our problem turned out to be that, when we were configuring the application internally, we accidentally gave it a private scope that messes up the behavior of the app in weird ways. It's possible that your app was accidentally given the same scope.

**Comment by jmoldow** [comment]
@msolano00 Also, can you double-check that the service account is still a collaborator on the folder, and that it didn't get deleted at some point?

And can you tell me, what happens if you do `GET /folders/0/items` with the service account (`client.folder('0').get_items(limit=100)` in the SDK)? Do you see an empty response, or do you see the ancestor folder?

**Comment by msolano00** [comment]
@jmoldow I created the application myself. 

I ran the code you provided me and got an empty array as response.

**Comment by msolano00** [comment]
Hi @jmoldow,

I tried running as another user (my own user)

```python
from boxsdk import JWTAuth
from boxsdk import Client

auth = JWTAuth(
    client_id='clientID',
    client_secret='clientSecret',
    enterprise_id='entID',
    jwt_key_id='jwtKEY',
    rsa_private_key_file_sys_path='/some/path/.ssh/box_private_key.pem',
    rsa_private_key_passphrase='keyPassphrase',
)

access_token = auth.authenticate_instance()

client = Client(auth)

user = client.user(user_id='myOwnID')

listitems = client.as_user(user).folder(folder_id='31850693387').get_items(limit=100, offset=0)

print listitems
```

And I got the following error:

```python
Traceback (most recent call last):
  File "code/test.py", line 19, in <module>
    listitems = client.as_user(user).folder(folder_id='31850693387').get_items(limit=100, offset=0)
  File "/home/user/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/object/folder.py", line 153, in get_items
    box_response = self._session.get(url, params=params)
  File "/home/user/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 395, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/home/user/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 299, in _prepare_and_send_request
    **kwargs
  File "/home/user/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 383, in _make_request
    self._raise_on_unsuccessful_request(network_response, expect_json_response, method, url)
  File "/home/user/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 238, in _raise_on_unsuccessful_request
    context_info=response_json.get('context_info', None),
boxsdk.exception.BoxAPIException: 
Message: Access denied - insufficient permission
Status: 403
Code: access_denied_insufficient_permissions
Request id: 74815239959cd0424d2196
Headers: {'Content-Length': '181', 'Content-Encoding': 'gzip', 'Age': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Accept-Encoding', 'Server': 'Server', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store', 'Date': 'Thu, 28 Sep 2017 14:16:04 GMT', 'Content-Type': 'application/json'}
URL: https://api.box.com/2.0/folders/31850693387/items
Method: GET
Context info: None
```

**Comment by jmoldow** [comment]
That 403 error doesn't have as much info as I wish it did, but I'm guessing it failed because your application isn't configured to do `As-User` for managed users in your enterprise.

Either that, or the managed user belongs to a different enterprise than the service account.

With the JWT service account client, can you try this':

```python
print(client.make_request('GET', "https://api.box.com/2.0/users/me/collaborations?status=accepted").json())
```

Can you see the collaboration object for the file/folder, or is it another empty list?

**Comment by msolano00** [comment]
:(
```
{
  u 'total_count': 0,
  u 'offset': 0,
  u 'limit': 100,
  u 'entries': []
}
```

**Comment by msolano00** [comment]
This is the configuration I have from the developer console:
![image](https://user-images.githubusercontent.com/2273023/30987791-6e7e062a-a455-11e7-8cc7-6080005cceaa.png)

**Comment by jmoldow** [comment]
@msolano00 As the user who originally created the collaboration, can you try

```python
print(user_client.make_request('GET', 'https://api.box.com/2.0/files/FILE_ID/collaborations').json())
```

just to confirm whether the service account collab can or can't be seen?

I'm wondering if you need to set "Application Access" to "Enterprise" in order to be able to accept collaborations on the service account. Let me ask around internally.

**Comment by jmoldow** [comment]
@msolano00 I've been told that you probably need to select "Enterprise" for "Application Access".

After doing that, you'll need to re-authorize your application in your enterprise, in order for the new scope to take affect.

**Comment by jmoldow** [comment]
@msolano00 I'm closing this issue, as it appears to be an app configuration issue, not an SDK issue.

Please try selecting "Enterprise" for "Application Access" (don't forget to re-authorize your app after that), and see if that works.

If you're still having problems, please create a support ticket on https://community.box.com/t5/custom/page/page-id/BoxSupportOptions .

**Comment by msolano00** [comment]
Thanks @jmoldow, as soon as they reauthorize my app I will test it and let you know how it went.

**Comment by msolano00** [comment]
Hello @jmoldow 

After changing my configuration a little I got some "progress", but I am getting the following error:

```python
Traceback (most recent call last):
  File "code/connection.py", line 23, in <module>
    root_folder = client.as_user(service_user).folder(folder_id='0').get()
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/object/item.py", line 126, in get
    return super(Item, self).get(fields=fields, headers=headers)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/object/base_object.py", line 117, in get
    box_response = self._session.get(url, params=params, headers=headers)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 395, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 299, in _prepare_and_send_request
    **kwargs
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 368, in _make_request
    **request_kwargs
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/boxsdk/network/default_network.py", line 23, in request
    return DefaultNetworkResponse(self._session.request(method, url, **kwargs), access_token)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/marvin/Development/Python/box-api/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {As-User: 2690972259} must be of type str or bytes, not <type 'int'>
```

I am running pretty much the previous code with the following lines:

```python
service_user = client.user(2690972259)

root_folder = client.as_user(service_user).folder(folder_id='0').get()
```

Do I have to parse the the user object?

**Comment by msolano00** [comment]
Holy molly, I think its finally working. I had to switch the Application Access to Enterprise, select the Manage enterprise properties in Application Scopes AND turn on all Advanced Features.

I feel its a little of an overkill for what I want to do, so I think I should check this configuration with box support. Anyway, I wanted to put all this in case someone runs into the same issue.

**Comment by jmoldow** [comment]
Thanks for posting your solution @msolano00 .

In your screenshot, you already had "Perform Actions as Users" selected.

So you're saying that, in addition to selecting "Enterprise" as I suggested, you also had to select:
- "Manage enterprise properties"
- "Generate User Access Tokens"

Neither of those seem necessary for the `As-User` header, so I would definitely encourage you to follow up with Box support.

If you could, please post back with your final findings.

**Comment by visualskyrim** [comment]
Hi @jmoldow 
I'm running into this issue just now and I feel this thread might help me out.
I noticed that you've mentioned:

> don't forget to re-authorize your app after that

What do you mean by saying `re-authorize`?
