### ISSUE TITLE
s3 to box

### ISSUE THREAD

**Issue by mostafamantawy** [box/box-python-sdk#250]
Hi I am having an issue while use upload_stream method
I am having this call to get data from s3
response = s3store.getfile(self.TEST_DATA['fileLocation'])
and it's successful but then trying to send the response as it's failed with 
AttributeError: 'dict' object has no attribute 'tell'
I changed that to use chunk
for chunk in iter(lambda: stream.read(self.CHUNK_SIZE), b''):
            yield chunk
ended up with this error
AttributeError: 'generator' object has no attribute 'tell'
then tried sending the bytes from read, got this error
AttributeError: 'str' object has no attribute 'tell'
All of them are failing on boxsdk/session/box_session.py:290
file_stream_positions = dict((name, file_tuple[1].tell()) for name, file_tuple in files.items())
what I need to send to get this working?

**Comment by jmoldow** [comment]
For your original code, with `response = s3store.getfile(self.TEST_DATA['fileLocation'])`, can you show how you were using `response` to invoke the Box SDK?

**Comment by jmoldow** [comment]
Also, what S3 library are you using, and what type of object is `s3store`?

**Comment by mostafamantawy** [comment]
the trick that I found is that you guys expecting a file like object so I used io.Bytes
file_stream = io.BytesIO(stream["Body"].read())
now it's working thanks for the quick reply

**Comment by shabarish591** [comment]
Hello @mostafamantawy  

   may i see the code , How you used to overocme this issue , i am also blocked on same issuse from 2 days . Thanks in advance
