### ISSUE TITLE
File Collaboration API Permission

### ISSUE THREAD

**Issue by aowolabi** [box/box-python-sdk#251]
I am in the process of extending the provided Client interface to create collaborations at the file level for an existing group. The API documentation outlines  the correct parameters for creating a [collaboration](https://api.box.com/2.0/collaborations):

Here is part of the code I wrote to create a collaboration with the following values:
```
import json

def _create_collaboration(self, item, accessible_by, role, can_view_path):
        params = {'notify': False}
        api_url = self._client.get_url('collaborations')
        data = {
            'item': item,
            'accessible_by': accessible_by,
            'role': role,
            'can_view_path': can_view_path
        }
        box_response = self._client.make_request(
            'POST', api_url, expect_json_response=True, params=params, data=json.dumps(data)
        )
        response = box_response.json()
        return Collaboration(self._create_session(), response['id'], response)
```
Where `item`, `accessible_by`, `role` and `can_view_path` have the following structure and value:
```
item = {
  'id': 'file_id',
  'type': 'file'
}

accessible_by = {
  'id': 'group_id',
  'type': 'group'
}

role = 'viewer'

can_view_path = True
```

When I attempt to create a file level collaboration with the `can_view_path` parameter set to `true`, for an existing group, the API returns a `access_denied_insufficient_permissions` 403 exception. In the documentation for the API, there is mention of specific limitations on the `can_view_path`:

>With the can_view_path parameter the user will only see the names of all the folder’s ancestor folders and be able to traverse up and down this path. Only the folder owner can use the can_view_path option.

I am curious to understand how this should work? I get the permission exception when using a `JWT` authenticated user to create all of the folders in the hierarchy, as well as the file I would like to add the group collaboration to. I've also tried using the `as_user` with another user to create the same hierarchy with no luck.

Exception:
```
boxsdk.exception.BoxAPIException:
Message: Access denied - insufficient permission
Status: 403
Code: access_denied_insufficient_permissions
Request id: 12114959585a0a8ae5b7db3
Headers: {'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'BOX-REQUEST-ID': '1vj0g63plkkgh5tesr04bt9utk', 'Date': 'Tue, 14 Nov 2017 06:19:17 GMT', 'Content-Type': 'application/json', 'Age': '0', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive'}
URL: https://api.box.com/2.0/collaborations
Method: POST
Context info: None
```

**Comment by aowolabi** [comment]
I received a response from a Tech Support Engineer, TL;DR `can_view_path` is not supported for file collaborations:
>I'm following up on the errors you're receiving when attempting to create collaborations with the "can_view_path" parameter. I've checked in with our engineering team and confirmed that this parameter is only supported for use when making collaborations on folders, not files, so this error is expected. I'm working with our team to update our developer documentation accordingly.

**Comment by jrmcglynn** [comment]
Ping to please update the documentation! Coming from a developer who just wasted a lot of time trying to figure out why this wasn't working as expected...

**Comment by mattwiller** [comment]
@jrmcglynn Sorry about that!  I opened a PR to update the docs over at #431 — is that what you're looking for?

**Comment by jrmcglynn** [comment]
@mattwiller yep! that'll help the next guy. thanks for taking care of it.
