### ISSUE TITLE
Can't Upload Files using JWTAuth while I am an outside user to the company who owns the app

### ISSUE THREAD

**Issue by evanallan1** [box/box-python-sdk#255]
While using the code below:

```python
oauth = JWTAuth(
                client_id='xxxxxxx', 
                client_secret='xxxxxxxx', 
                enterprise_id='xxxxxx',
                jwt_key_id='xxxxx',
                rsa_private_key_file_sys_path='xxxxxxx',
               )
access_token = oauth.authenticate_instance()
from boxsdk import Client
client = Client(oauth)
shared_folder = client.folder(folder_id='000000000')
upload_file = shared_folder.upload('xxxxxxx.xlsx')
```

I get the following error:
```
BoxAPIException: Message: Not Found
Status: 404
Code: not_found
Request id: el3utgfmeg7a8qgx
Headers: {'Date': 'Tue, 12 Dec 2017 16:26:24 GMT', 'Content-Type': 'application/json', 'Cache-Control': 'no-cache, no-store', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Accept-Encoding', 'Content-Length': '322', 'Age': '0', 'Connection': 'keep-alive'}
URL: https://upload.box.com/api/2.0/files/content
Method: POST
Context info: {'errors': [{'reason': 'invalid_parameter', 'name': 'parent', 'message': "Invalid value 'd_000000000'. 'parent' with value 'd_000000000' not found"}]}
```

It seems like I am getting authenticated by the app, but since I am an outside user to the app I am not being authorized to upload files.

**Comment by jmoldow** [comment]
I don't know what you mean by "I am an outside user".

Only one user is authenticating here: the service account for `enterprise_id='xxxxxx'`. That service account is, by definition, within `enterprise_id='xxxxxx'`.

But that service account is, in most respects, a normal user. It can only access content that it owns, or content that it is collaborated on. It can't see all content within the enterprise.

If you really want to be able to upload a file into a folder, it needs to own or be collaborated on that folder.

If you have more questions or problems with service accounts, please post a question on community.box.com , unless there is a problem specific to the Python SDK.

**Comment by evanallan1** [comment]
Sorry, my explanation was misguided... It seems like the real error is that when I try and upload a file to the folder_id I gave the code, which is the integer I see in the url when I go into the folder I am a collaborator on, the error says it can't find the folder. When I change the folder_id to just be "0" (the root folder) the code works fine and doesn't error out though.
