### ISSUE TITLE
Renaming a file removes its extension

### ISSUE THREAD

**Issue by scherroman** [box/box-python-sdk#256]
Using 

```
client.file(file_id='SOME_FILE_ID').rename('SOME_NEW_NAME')
```
currently removes the file's extension if the extension is not provided in the new name. This is a problem when we do not know the extension of the file we are trying to rename. The only workaround is to first fetch the file's current name, extract the extension, and include that extension in the string passed to the rename command.

Perhaps an optional argument such as 'preserve_extension' could prove useful

```
client.file(file_id='SOME_FILE_ID').rename('SOME_NEW_NAME', preserve_extension=True)
```

Or perhaps even a new method 'rename_basename'

```
client.file(file_id='SOME_FILE_ID').rename_basename('SOME_NEW_NAME')
```

In my experience, you most often want to rename a file's basename, rather than its extension. Box.com itself doesn't actually allow you to rename a file's extension.

**Comment by jmoldow** [comment]
This could potentially be a useful feature to add, but I have a question for you @scherroman : what is your use-case for renaming a file, when you don't know the original name or type of the file?

**Comment by scherroman** [comment]
We are using Box to store artwork/design images uploaded by our company's users via the Box Content Uploader UI Element. Currently, these images are all being uploaded into the same folder for all our users, so after they are successfully uploaded, we use the Box SDK to rename the files by appending the file id to the name, to prevent naming conflicts with any future files uploaded. We then store the ids of those files in our database for later use in our applications. In this case, we are only concerned with renaming the basename of the file, as the extension of the image could be anything, like .tif, .png, .jpg, and so on.

Later on in our workflow, we have bots regularly copy some of those image files to new, dynamically generated folder locations, and completely change the names of the files based on which record in our database the file is associated with. In that scenario, we are only referencing the file by id, and do not care about its current name or extension. We only want to copy the file over to the new location, rename the basename, and preserve the current extension.

**Comment by mattwiller** [comment]
@scherroman I don't believe there's anything special we could do in the SDK to solve this — it would need to be an API change.  At the present time, the only thing we could do is to add a parameter that has the SDK do exactly what you mentioned — reading the file and then renaming with the extension given by the server.  Rather than adding the new parameter and branch to the SDK to do this, it's likely simpler and more flexible just to do it yourself in your own codebase as needed.

**Comment by salazarm** [comment]
I think it would make sense to add this. 
My use case is I upload things in a temporary folder with a unique name. Then later in the process I move it to a unique folder with a fixed name. I need to preserve the original extension. The only way to do that would be to thread that information through along my process or waste time first fetching the meta data for the file. For performance I think renaming the base name would be a helpful so we can avoid threading the extension information (it could be anything, we don't restrict it).
