### ISSUE TITLE
Is this SDK using "edit.boxlocalhost.com'?

### ISSUE THREAD

**Issue by billbine** [box/box-python-sdk#258]
In the application with this SDK, the app needs to access to "edit.boxlocalhost.com".
I know this host is for Box Edit.
Does this SDK need to connect "edit.boxlocalhost.com'? Is this SDK using Box Edit function?

Sometimes I met the problem that the client PC cannot access to the host and cannot work the application.

Could you give me some information and do you have any plan to change this method?

**Comment by jmoldow** [comment]
That domain is only used by the web application, never the SDK.

Please reach out to community.box.com or our Support team for questions about Box Edit.

**Comment by billbine** [comment]
I understood. Thank you a lot.
