### ISSUE TITLE
Should the demo auth.py code demonstrate re-use of old tokens?

### ISSUE THREAD

**Issue by alexei-matveev** [box/box-python-sdk#26]
This makes the authentication example more convoluted, but also more practical.
Not sure if this fits into the scope of the minimal demo.

https://github.com/alexei-matveev/box-python-sdk/commit/e3423cea52e304d164e8f758f14fd359baa2fbbd

Also I am not sure how to find out if the tokens are still live to fall back to web form.

**Comment by jmoldow** [comment]
Hi @alexei-matveev, 

Thanks for the suggestion. But the demo program purposely doesn't do this. We do not want to encourages insecure practices, even if it's just for demo purposes.


> Also I am not sure how to find out if the tokens are still live to fall back to web form.

You have to attempt an API request with the tokens. If the token is expired, the API will respond to tell you such by sending back a 401 Unauthorized response with an invalid_token error code. At this point, you can either fall back to the web form, or refresh the token if you still have the refresh token. See https://developers.box.com/oauth/. ``boxsdk`` does this all automatically.
