### ISSUE TITLE
Add configurable retry after parameter for API calls to Box

### ISSUE THREAD

**Issue by jpan-box** [box/box-python-sdk#260]
Hey Team,

Raising this for a customer (I'm a boxer). Currently, when making API calls that take longer than 1 minute to return a response (e.g. Move Owned Items with large amounts of content under a user), the SDK will retry the API call. This results in a 409 if a folder operation is still occurring on the user, and the call fails.

We should include the option to configure this one minute timeout on the SDK side, to a custom value (5 mins) or no value at all.

Thanks,
Jason

**Comment by carycheng** [comment]
Hey @jpan-box, 

In the Python 2.x.x branch you have the ability to set a timeout value through the `extra_network_parameters`

For example by using
```python
file = client.file("12345")
timeout_value_in_seconds = 300
extra_network_parameters = {'timeout':timeout_value_in_seconds}
get_response = file.get('data', extra_network_parameters=extra_network_parameters)      
```

However, the conflict issue you see on the Move Owned Items call might be surfacing a different issue that is present in the API layer and not the SDK layer. What may be happening is the API is giving a 502 response and so the SDK will try again, when it does the retry that is where the conflict status code comes back.

**Comment by krivi95** [comment]
Hi all,

Is this behavior possible to achieve on the newer versions of boxsdk?

E.g. when retrieving box webhooks: `box_client.get_all_webhooks()`.

Thanks!
