### ISSUE TITLE
Search query failures

### ISSUE THREAD

**Issue by sci-tab** [box/box-python-sdk#266]
Use case: I want to query for all files of a certain type in Box.

Issue: Search returns incorrect results (0) for queries in which the file extension and file name are the same.

It will return correct results with just file name. Ex. It can find the desired files when searching the file name `dat`, but you can imagine many other things might contain that in the name (data) and extension is needed.

I'm able to make the query directly using `https://api.box.com/2.0/search?query=dat&file_extensions=dat` endpoint and using the JS SDK. It fails (returns 0) for python sdk. More documentation for the search endpoint would also be helpful.

Here is my code:

```
 results = client.search(
            filename,
            file_extensions=extension,
            limit=LIMIT,
            offset=offset,
            ancestor_folders=folder,
            result_type='file')
```

Thanks!

**Comment by mattwiller** [comment]
@sci-tab I just tested this in my own account and it seems to be working correctly.  One thing you might want to double-check is the values you're passing for `ancestor_folders` and `file_extensions` should both be `Iterable`.  For example:

```python
results = client.search(
            filename,
            file_extensions=['dat'],
            limit=LIMIT,
            offset=offset,
            ancestor_folders=[client.folder(folder_id)],
            result_type='file')
```
