### ISSUE TITLE
Add update shared link functionality to python SDK

### ISSUE THREAD

**Issue by kaustin754** [box/box-python-sdk#269]
Per Box API Office Hours today, please add update shared link functionality to the python SDK. In particular I'm looking for the 'shared_link.unshared_at' string to set expiration dates on open access links. Thanks!

**Comment by Jeff-Meadows** [comment]
Hi Kevin! You'll see a lot of updates to the Python SDK over the next few months, but in the meantime, you can pretty easily update a shared link using the `update_info` method of `Item`s (`File`s and `Folder`s).

    client.file(<file_id>).update_info(data={'shared_link': {'unshared_at': <new_unshared_at>}})

**Comment by kaustin754** [comment]
Thanks Jeff!
