### ISSUE TITLE
Catch Network exceptions and surface them as Box SDK exceptions

### ISSUE THREAD

**Issue by jmoldow** [box/box-python-sdk#271]
Right now, our use of requests isn't invisible because we don't catch requests exceptions. This means that the user has to either catch requests exceptions too, or these could crash their program.

**Comment by bts-dido** [comment]
@jmoldow 
How can I catch request exception?

I'm seeing request exception message like below while catching BoxAPIException. 

```
"POST https://api.box.com/2.0/folders" 409 312
{'Date': 'Tue, 18 Jun 2019 07:42:42 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'BOX-REQUEST-ID': '0ehidqbgqof5tssmbtrkntj3rti'}
```

I'm using SDK version 2.4.1.

**Comment by bts-dido** [comment]
@jmoldow @mattwiller Any update?

**Comment by mattwiller** [comment]
@bts-dido Is the issue here that you're seeing the logged error response?  If so, you may find the information over at https://github.com/box/box-python-sdk/issues/414 helpful

**Comment by bts-dido** [comment]
Thanks @mattwiller ! That helped.

**Comment by mattwiller** [comment]
@bts-dido Great — glad to hear it!
