### ISSUE TITLE
`boxsdk.exception.BoxAPIException` Documentation Error

### ISSUE THREAD

**Issue by bmccary** [box/box-python-sdk#276]
In [boxsdk/exception.py](../blob/master/boxsdk/exception.py) (line 115 in `master`, but same problem in `1.5`), the documentation of `boxsdk.exception.BoxAPIException` says the return type of the `.code` property is `int`, but I believe it is actually `unicode`. Presumably a copy/paste from the immediately-above `.status` property, whose return type really is `int`.

Additionally, the type of the `code` parameter to the `__init__` of the same class is documented as `unicode` earlier in the file.

I have found the [attrs](http://www.attrs.org/en/stable/) library useful.

**Comment by Jeff-Meadows** [comment]
Fixed in #279
