### ISSUE TITLE
Can't search for files in folders

### ISSUE THREAD

**Issue by surennata** [box/box-python-sdk#286]
I am using the boxsdk[jwt] ver 1.5.5.

After authenticating successfully with JWT I am able to get the folder or file contents if I give the object ID directly.

But when trying to search a folder the below error is thrown.
**_ERROR    Box search failed for all file sequence item 0: expected string or Unicode, int found_**

Seems like the search() method in the Search class is passing the **folder.object_id** as a list of INT in the params.  Whereas it has to be string or Unicode.  In this case passing **folder.id** seems to fix this.

Will this be fixed soon?

**Comment by mattwiller** [comment]
@surennata I was able to correctly search within a folder using the following code:

```python
folder = client.folder('xxxxxxxxx')
results = client.search('test', ancestor_folders=[folder])
```

Could you share a bit more about how you're trying to call the `search()` method and how you're getting the `Folder` object(s) you're passing into it?

**Comment by surennata** [comment]
@mattwiller this is how I use the `search()` method.

```
folder = client.folder(0)
results = client.search('filename', limit=200, offset=0, ancestor_folders=[folder], file_extensions=['folder'])
```
I also tried passing the `result_type` as u'folder' instead of `file_extensions` as a list of string.  I get the same error.

Also I am using an enterprise box account of my organization.

Does this make any difference ?

**Comment by mattwiller** [comment]
@surennata It looks like the problem is that you're passing in the folder ID (`0`) as an `int` — all Box IDs should be strings.  If you pass it as `'0'` instead, searching should work correctly.  Could you give that a try and let me know if that fixes the issue you're seeing?

**Comment by surennata** [comment]
@mattwiller. No that doesn't work either. 
I am able to get the folder and it's contents through `get_items()` method even if I pass integer.

But the issue is with the `search()` method in `boxsdk.object.search.Search` class. 
While updating the `params` of I change `folder.object_id` to `folder.id` everything works fine.

**Comment by surennata** [comment]
@mattwiller  Sorry for the inconvenience caused.  I once again did a clean install of the boxsdk package and tried with string `'0'` instead of integer `0` and the `search()` method worked fine this time.  Looks like my virtualenv had been corrupt for long time.

Once again apologies for raising the incorrect issue and thank you very much for your time and support.

**Comment by mattwiller** [comment]
@surennata No problem — I'm glad you figured out the issue!
