### ISSUE TITLE
Proactively refresh tokens before they expire

### ISSUE THREAD

**Issue by mattwiller** [box/box-python-sdk#289]
In order to prevent errors around tokens becoming invalid, the SDK should pre-emptively refresh access tokens *before* making API calls rather than waiting for a 401 response from the Box API.  This will necessitate some interface changes to the OAuth2 class, and will be a breaking change in the 2.x release.

**Comment by ikwyl6** [comment]
or have a function/call or ability to check if an existing refresh or access token is invalid. Then you know for sure it's invalid and can get a new one.
