### ISSUE TITLE
"TypeError: metaclass conflict" when importing any class from boxsdk

### ISSUE THREAD

**Issue by adiv199** [box/box-python-sdk#300]
Getting the following error when trying to import any class from boxsdk in Python
**TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases** 

boxsdk version : 1.5.5
Python version: 3.5.2
six version: 1.11.0

**Comment by kbroughton** [comment]
I fixed this with
pip install six==1.10.0
