### ISSUE TITLE
Guidline for handling client Oauth in web application

### ISSUE THREAD

**Issue by jdeepee** [box/box-python-sdk#321]
Hi there,

I have functionality on my website which allows Box users to integrate with our service and use our service from within Box. I have a callback URL "/box/callback" which will be called after a user authenticates with Box through our website. From here I store the access token and refresh token in our database for use with subsequent request to our server later. 

In order to make requests to box I am aware I need to create a client object with the oauth class passed to the object. Currently I am initiating an Oauth class with credentials by passing the refresh token and access token retrieved from the database directly into the init constructor. And then I pass the Oauth class into the Client class. However upon making requests using the client I receive an exception telling me there is no access token. This leads me to believe that I am creating the Oauth class incorrectly. 

How should I rebuild the Client class so I can make requests on behalf of my user?

Thanks

**Comment by Jeff-Meadows** [comment]
Could you share the code that you use to construct the `OAuth2` and `Client` classes, and could you also share the exception info you get when trying to make a request?

For debugging purposes, you can also ensure you've created the auth class correctly by accessing its `access_token` property and verifying that it's got an access token set.

**Comment by jdeepee** [comment]
Construct the Oauth like so

`    oauth = OAuth2(
                    client_id=current_app.config["BOX_CLIENT_ID"],
                    client_secret=current_app.config["BOX_CLIENT_SECRET"],
                    refresh_token=user.box_refresh_token,
                    access_token=user.box_access_token
                )`

and the client

`client = Client(oauth=oauth)`

Exception:

`  File "/home/prod/www/biglegal/big_legal/views/integrations.py", line 237, in analyse_box_document
    file_content = client.file(file_id=file_id).content()
  File "/usr/local/lib/python2.7/dist-packages/boxsdk/object/file.py", line 57, in content
    box_response = self._session.get(url, expect_json_response=False)
  File "/usr/local/lib/python2.7/dist-packages/boxsdk/session/box_session.py", line 397, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boxsdk/session/box_session.py", line 300, in _prepare_and_send_request
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/boxsdk/session/box_session.py", line 343, in _make_request
    access_token_will_be_used = self._oauth.access_token
AttributeError: 'NoneType' object has no attribute 'access_token'`

I have verified before initiating the client that access token is set in the Oauth class.
