### ISSUE TITLE
Make use of ._response_object?

### ISSUE THREAD

**Issue by J-Parsons** [box/box-python-sdk#322]
Hi Box team,

On the main README under "Metadata", you recommend retrieving file metadata with:
 ```client.file(file_id='SOME_FILE_ID').metadata().get()```. However, after playing with the SDK and reading some of the source code, it appears that this line is making two API calls and only works for File objects. Why is this preferred over simply taking advantage of an object's ```._response_object``` attribute, which is made available for any BaseObject after a single API request?

**Comment by mattwiller** [comment]
@J-Parsons I just tested the SDK; it only makes one API call when I do `md = client.file(file_id).metadata().get()`.  You can verify this for yourself using the `DevelopmentClient`, which logs all the API calls made by the SDK.
