### ISSUE TITLE
How can I use the box-python-sdk to "Get Memberships for User"?

### ISSUE THREAD

**Issue by erikgui** [box/box-python-sdk#338]
Hello Box team,
According to the API reference, there's an API to retrieve the memberships for a given user:
```
https://api.box.com/2.0/users/user_id/memberships
```
How can I use that with this SDK?
Thanks

**Comment by mattwiller** [comment]
@erikgui We have a pull request we're currently working on that covers this functionality in #326 — that should make it into the next 2.x release.  In the meantime, you should be able to make the request manually by doing something like this:

```python
url = 'https://api.box.com/2.0/users/{0}/memberships'.format(user_id)
response_body = client.make_request('GET', url).json()
groups = response_body['entries']
```

**Comment by erikgui** [comment]
Thank you for your response and guidance @mattwiller! This works for me!
