### ISSUE TITLE
SSLError:

### ISSUE THREAD

**Issue by sapreakshay** [box/box-python-sdk#339]
We are currently seeing this error:
SSLError: HTTPSConnectionPool(host='api.box.com', port=443): Max retries exceeded with url: /2.0/users/me (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

import keyring
from boxsdk import OAuth2
from boxsdk import Client

CLIENT_ID = 'REDACTED'
CLIENT_SECRET = 'REDACTED'

def read_tokens():
    """Reads authorisation tokens from keyring"""
    # Use keyring to read the tokens
    auth_token = keyring.get_password('Box_Auth', 'vbillava@deloitte.com')
    refresh_token = keyring.get_password('Box_Refresh', 'vbillava@deloitte.com')
    return auth_token, refresh_token

def store_tokens(access_token, refresh_token):
    """Callback function when Box SDK refreshes tokens"""
    # Use keyring to store the tokens
    keyring.set_password('Box_Auth', 'vbillava@deloitte.com', access_token)
    keyring.set_password('Box_Refresh', 'vbillava@deloitte.com', refresh_token)

def main():
    """Authentication against Box Example"""

    # Retrieve tokens from secure store
    access_token, refresh_token = read_tokens()

    # Set up authorisation using the tokens we've retrieved
    oauth = OAuth2(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        access_token=access_token,
        refresh_token=refresh_token,
        store_tokens=store_tokens,
    )

    # Create the SDK client
    client = Client(oauth)
    # Get current user details and display
    current_user = client.user(user_id='me').get()
    print('Box User:', current_user.name)

if __name__ == '__main__':
    main()

**Comment by mattwiller** [comment]
@sapreakshay Are you still seeing this error?  An SSL error like that may indicate an issue in the network path between your program and the Box API — is there some sort of network middlebox on your network?

Also, you should change your client secret for your application; I've redacted it from your post but it was up for a whole week and someone may have seen it.  With that secret, anyone else could issue access tokens on behalf of your application.

**Comment by ShivamBhirud** [comment]
Hi Matt, I am having the same issue as mentioned in this post. Why does having a network middleware like a VPN should be a problem? Can we make it work even while using a VPN? Thanks!
