### ISSUE TITLE
urllib.request.Request() does NOT contain the critical `code` parameter

### ISSUE THREAD

**Issue by rbelew** [box/box-python-sdk#342]
[echo-ing a query to community.box, hanging from a few months ago, at the suggestion of support@box]

https://community.box.com/t5/Platform-and-Development-Forum/OAuth2-via-script-python3-urllib-request-Request-auth-url-not/m-p/58625

I'm trying to use box's API to access public files (provided by my
local police department).  I've established a box application to do
this, have its credentials, and am now writing a python3 app using
boxsdk, following the documentation here:
https://developer.box.com/docs/authenticate-with-oauth-2

>> CurrOAuth = boxsdk.OAuth2(
	    client_id = myCID,
	    client_secret = mySecret,
	)
>> auth_url, csrf_token = CurrOAuth.get_authorization_url('https://app.box.com')

So far so good.  But i must be interpretting your instructions for
Step 2, redirecting the user,  incorrectly.  Its last step is

	 return redirect(auth_url)

?? Which (library's) `redirect()` function do you have in mind?

The first instruction of Step 3 is:

	When the user is redirected back to your application redirect_uri, a
	code and state parameter will also be present in the querystring
	parameters.

if I paste `auth_url` into a browser, i'm indeed directed (after
logging in to box) to my home folder.  however, when i try to
script this using python3's urlib:

>> request = urllib.request.Request(auth_url)
>> u = opener.open(request)
>> u.geturl()
'https://app.box.com/api/oauth2/authorize?state=box_csrf_token_*MORE-RANDOM_CSRF*&response_type=code&client_id=*ClIENT-ID*&redirect_uri=https%3A%2F%2Fapp.box.com'

(i've elided the actual *MORE-RANDOM_CSRF* and *ClIENT-ID*)

the redirect returns exactly the original `auth_url`, and does NOT
contain the critical `code` parameter you mention in Step 3, and
so cannot get the access and refresh tokens.

what am i missing, please?

**Comment by mattwiller** [comment]
@rbelew The standard OAuth2 web flow requires the user to visit the `auth_url` in their browser and type in their credentials in order for your application to get an access token on their behalf.  This assumes that your code is running on a web server in response to a user request; it is that web request that you would respond to with a redirect to the `auth_url`.  Then, after the user goes through the Box authentication web flow, Box will call the `redirect_uri` — which should point to one of your application's URLs — with the `code` query parameter, which you can exchange for an access token.

Please see the [Box OAuth2 docs](https://developer.box.com/docs/authenticate-with-oauth-2) for more information.

**Comment by rbelew** [comment]
thanks for your quick response @mattwiller .  i am trying to establish a regular, AUTOMATED  "harvest" of new files posted by a city agency.  Your description of "standard OAuth2 web flow" makes it sound as if a MANUAL intervention (user visiting via browser) is required, which misses my goal.  What other process can you recommend?

**Comment by mattwiller** [comment]
@rbelew The alternative would be to use [Server auth with JWT](https://developer.box.com/v2.0/docs/authenticate-with-jwt) — this method does not require manual user input, and relies instead on a private key associated with your application.

**Comment by rbelew** [comment]
thanks again @mattwiller !    JSON Web Tokens does seem like what i'm looking for.  To confirm, your link sent me to "Authenticate with JWT (SDK)" but it says:

> Manually extracting this information from the config file, or manually generating keys is currently required for Python and Ruby.

so for python the [Authenticate with JWT (API)](https://developer.box.com/v2.0/docs/construct-jwt-claim-manually) and [JWT Application Setup](https://developer.box.com/docs/setting-up-a-jwt-app#section-step-2-generate-a-public-private-keypair) dscriptions seem the methods for me to use?

**Comment by mattwiller** [comment]
That sounds right to me!
