### ISSUE TITLE
folder.get_items() limit param seems not working for me

### ISSUE THREAD

**Issue by joanff** [box/box-python-sdk#366]
the limit on this function seems not working?    
@api_call
    def get_items(self, limit=None, offset=0, marker=None, use_marker=False, sort=None, direction=None, fields=None):

even when I give limit = 10
this still gives me more than 10

**Comment by carycheng** [comment]
Hey @joanff, 

You might want to try the below snippet:
```python
    folder = client.folder('12345').get_items(limit=10)
    folder_items = []
    for x in range(10):
        folder_items.append(folder.next())
```

The reason why you are getting more than 10 items even when you specify the limit is that the limit actually refers to the limit on items you get back from the API per page of the iterator. The limit does not specify the total items you are to retrieve from the API.

I hope this helps and if you have any other issues, please let us know. Thank you!

**Comment by joanff** [comment]
then how do I limit my pointer only iterate on this page, don go to next page?????
so I get 10 only. (i thought that's what limit means right? why do i need to explicitly right 10 in a for loop to limit it????)

**Comment by joanff** [comment]
> Hey @joanff,
> 
> You might want to try the below snippet:
> 
> ```python
>     folder = client.folder('12345').get_items(limit=10)
>     folder_items = []
>     for x in range(10):
>         folder_items.append(folder.next())
> ```
> 
> The reason why you are getting more than 10 items even when you specify the limit is that the limit actually refers to the limit on items you get back from the API per page of the iterator. The limit does not specify the total items you are to retrieve from the API.
> 
> I hope this helps and if you have any other issues, please let us know. Thank you!

Then how do I limit my pointer only iterate on this page, don go to next page, so that I get 10 back only. (i thought that's what limit means right? why do i need to explicitly write 10 in a for loop to limit it????)

**Comment by carycheng** [comment]
Hey @joanff, 

There is no way to retrieve an iterator that only produces 10 items from the API. The iterator will always return all items in the folder you specified if you keep calling `next()`. The limit that you specify in the `get_items()` call refers to the limit on items per page on the iterator. This is useful for performance tuning purposes. For example if you know the item you are searching for is in the range of the first ten or the first twenty then you can use the `limit` field to cut down on all the items per iterator, benefiting your performance. So in this case, when you specify `limit=10` you are specifying that each page of your iterator will contain ten items not retrieve ten items from the API.

If you really want to limit items, maybe using [itertools](https://docs.python.org/3/library/itertools.html) will solve your issue.

Something like this: 
`items = itertools.islice(get_items(..., limit=limit), limit)`

You can read more about the islice functionality [here](https://docs.python.org/3/library/itertools.html#itertools.islice)

**Comment by joanff** [comment]
@carycheng thanks!! understand now.
Totally confused by the limit word, I thought it was not working as it should.
Before the upgrade to 2.0.0, the limit works on the length of the return.
