### ISSUE TITLE
I have a question is there a way to possibly move files from amazon s3 to Box without having to go through the intermediate step of downloading the file to local machine,

### ISSUE THREAD

**Issue by shabarish591** [box/box-python-sdk#377]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Box Python SDK: // Replace with the version of the Python SDK you're using.  
Python: // Replace with the version of Python your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Traceback
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @shabarish591, 

As long as you can retrieve a stream from S3 you can upload to Box with with the `file.upload_stream()` method found [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#upload-a-file)

We are not entirely sure of the endpoints provided by the S3 but as long as you are able to retrieve a stream you will be able to move files from Box without necessarily downloading the file locally.

**Comment by aryus96** [comment]
> 
> 
> Hey @shabarish591,
> 
> As long as you can retrieve a stream from S3 you can upload to Box with with the `file.upload_stream()` method found [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#upload-a-file)
> 
> We are not entirely sure of the endpoints provided by the S3 but as long as you are able to retrieve a stream you will be able to move files from Box without necessarily downloading the file locally.

Is `upload_stream()` method creating also the right folder architectures ?

**Comment by shrutivardhan** [comment]
@shabarish591  were you able to find a solution? I am new to box and am looking for a solution for a similar use case.
Thanks!

**Comment by amine-mouffok** [comment]
Hello,
Same request here. I need to move files from Box to Amazon S3 and was wandering whether you found a solution to the mentioned above problem?
