### ISSUE TITLE
Upload Byte Stream

### ISSUE THREAD

**Issue by davidkazuhiro** [box/box-python-sdk#380]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm using pandas to generate an excel file.
The output is a `io.BytesIO()` stream in memory.
I want to upload it directly to Box but the Python SDK only supports file paths or `io.StringIO()` streams.

If I pass a `io.BytesIO()` I get the error `AttributeError: 'bytes' object has no attribute 'tell'`

Can it be made possible to upload byte streams?
(If it is possible, I didn't see it in the docs, so maybe an example could be included?)

### Versions Used
Box Python SDK: 2.0.0
Python: 3.7.1

### Steps to Reproduce

1. Install Dependencies

```
pip install boxsdk==2.0.0 pandas==0.23.4 openpyxl==2.5.12
```

2. Run python script
```
import io

from boxsdk import Client, OAuth2
import pandas

output = io.BytesIO()
writer = pandas.ExcelWriter(output, engine='openpyxl')
pandas.Series().to_excel(writer, sheet_name='Sheet1', header=True)
writer.save()
oauth2 = OAuth2(CLIENT, KEY, access_token=TOKEN)
client = Client(oauth2)
box_file = client.folder('0').upload_stream(output.getvalue(), 'test.xlsx')
```

### Error Message, Including Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/boxsdk/util/api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boxsdk/object/folder.py", line 285, in upload_stream
    file_response = self._session.post(url, data=data, files=files, expect_json_response=False).json()
  File "/usr/local/lib/python3.7/site-packages/boxsdk/session/session.py", line 97, in post
    return self.request('POST', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boxsdk/session/session.py", line 143, in request
    response = self._prepare_and_send_request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boxsdk/session/session.py", line 347, in _prepare_and_send_request
    kwargs['file_stream_positions'] = dict((name, file_tuple[1].tell()) for name, file_tuple in files.items())
  File "/usr/local/lib/python3.7/site-packages/boxsdk/session/session.py", line 347, in <genexpr>
    kwargs['file_stream_positions'] = dict((name, file_tuple[1].tell()) for name, file_tuple in files.items())
AttributeError: 'bytes' object has no attribute 'tell'
```

**Comment by Jeff-Meadows** [comment]
Hi @davidkazuhiro , `BytesIO` is supported, but in this line `box_file = client.folder('0').upload_stream(output.getvalue(), 'test.xlsx')` you're passing `bytes` (because of the call to `getvalue()`. Just pass the `BytesIO` object directly, without calling getvalue, and the SDK should be able to handle it.

**Comment by davidkazuhiro** [comment]
![](https://i.kym-cdn.com/photos/images/original/000/925/410/4cc.jpg)

thanks @Jeff-Meadows
