### ISSUE TITLE
accessing 'modified_at' param field as described in API 

### ISSUE THREAD

**Issue by rbelew** [box/box-python-sdk#386]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

- https://developer.box.com/v2.0/reference#get-folder-info
- https://developer.box.com/v2.0/reference#file-object

i’ve found this note from back in August’18:
https://community.box.com/t5/Platform-and-Development-Forum/Python-parsing-file-object/m-p/60381/highlight/true#M5116

### Description of the Issue
 i'm also trying to make use of the "modified_at" attribute, for both folders and files, and via the python SDK. 

when i try:
```
   CurrBoxClient.folder(folder_id=12399999).get(params={'fields': 'modified_at'})

   TypeError: get() got an unexpected keyword argument 'params'
```

### Versions Used
Box Python SDK: 1.5.5
Python: 3.6.5

### Steps to Reproduce

try on any folder/file accessed via id.

### Error Message, Including Traceback

TypeError: get() got an unexpected keyword argument 'params'

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @rbelew, 

The key for additional params is actually just `fields`.

So something like this should work: 

```python
folder = client.folder(folder_id='12345').get(fields=['modified_at'])
```

The note is from manually constructing a request and in that case the key is `params`. Apologies for the confusion!

For additional context, please refer to our docs [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/folders.md#get-information-about-a-folder)

Let us know if you come across any other issues!

Happy Holidays

**Comment by rbelew** [comment]
super, i had been using the v1.5 SDK; this works!
