### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'from_settings_file'

### ISSUE THREAD

**Issue by droidzone** [box/box-python-sdk#387]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am getting the error:
`AttributeError: 'NoneType' object has no attribute 'from_settings_file'
`

My complete code:
```
from boxsdk import JWTAuth, Client
auth = JWTAuth.from_settings_file('/home/joel/peroorkada/staticfiles/conf/box.json')
client = Client(auth)
service_account = client.user().get()
print('Service Account user ID is {0}'.format(me.id))
```

I've verified the settings file with cat. It exists.
When importing the module and checking its methods:
```
>>> from boxsdk import JWTAuth, Client
>>> dir(JWTAuth)
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

```

### Versions Used
Box Python SDK: 2.0.0
Python: 3.6.7

### Error Message, Including Traceback
$python3 ./testbox1.py n
Traceback (most recent call last):
  File "./testbox1.py", line 26, in <module>
    auth = JWTAuth.from_settings_file('/home/joel/peroorkada/staticfiles/conf/box.json')
AttributeError: 'NoneType' object has no attribute 'from_settings_file'

**Comment by carycheng** [comment]
Hey @droidzone, 

I just tried the below snippet and was able to instantiate a service account:

```python
from boxsdk import JWTAuth, Client

auth = JWTAuth.from_settings_file('/path/to/settings.json')
client = Client(auth)
service_account = client.user().get()
print('Service Account user ID is {0}'.format(service_account.id))
```

One thing to note is when I run

```python
from boxsdk import JWTAuth, Client

dir(JWTAuth)
```

I can see the method `from_settings_file()` present

<img width="338" alt="screen shot 2018-12-25 at 3 13 56 pm" src="https://user-images.githubusercontent.com/6364733/50427279-7be10700-0858-11e9-8c06-4ce561361ecf.png">


Can you verify again that you are using Python SDK 2.0?

**Comment by mattwiller** [comment]
@droidzone The Python SDK can be installed in two flavors: one with JWT auth and one without.  Could you also verify that you've installed `boxsdk[jwt]` and not just `boxsdk` (which does not include the JWT auth classes and libraries)?

**Comment by droidzone** [comment]
Thanks a lot, @mattwiller 
That was it. Adding `boxsdk[jwt]>=2.0.0` to requirements.txt solved it!

**Comment by ParvathiRajan** [comment]
Is this closed?

I could see that my version is `boxsdk[jwt]>=2.0.0` but 

![image](https://user-images.githubusercontent.com/39371408/72000767-029d3200-326a-11ea-8c2a-42529534a2d4.png)

And when I check `dir(JWTAuth)` I could see only below functions:

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

**Comment by stephencweiss** [comment]
In case anyone comes across this like I did -- you need to _only_ have `boxsdk["jwt"]` as a dependency in `requirements.txt`. It is _not_ in addition to `boxsdk`.

I.e. do this:
```
# requirements.txt
boxsdk["jwt"]
...
```
not this

```
# requirements.txt
boxsdk
boxsdk["jwt"]
...
```

**Comment by rsmedigodella** [comment]
I had the same issue and below code solved my problem

`config = JWTAuth.from_settings_file(settings_file_sys_path='file path')`
