### ISSUE TITLE
Folder.get_items function `limit` argument seems to be changing `offset` instead

### ISSUE THREAD

**Issue by erewok** [box/box-python-sdk#388]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue.

### Description of the Issue

`get_items(limit=...)` function call with the `limit` kwarg increments `offset` and returns *all* items in a folder instead of `limit` amount.

### Versions Used
Box Python SDK: 2.0.0
Python: 3.6/3.7

### Steps to Reproduce
```python
folder = box_client.folder(SOME_FOLDER_ID)
items = list(folder.get_items(limit=10))
... # Runs forever because it wants to download everything from the folder
```

Here are the logged API calls from the above:

```sh
{"message": "\u001b[32m\"GET https://api.box.com/2.0/folders/SOME_FOLDER_ID/items?limit=10&offset=0\" ...
{"message": "\u001b[32m\"GET https://api.box.com/2.0/folders/SOME_FOLDER_ID/items?limit=10&offset=10\" ...
{"message": "\u001b[32m\"GET https://api.box.com/2.0/folders/SOME_FOLDER_ID/items?limit=10&offset=20\" ...
{"message": "\u001b[32m\"GET https://api.box.com/2.0/folders/SOME_FOLDER_ID/items?limit=10&offset=30\" ...
```

It increments the `offset` by 10 every time. Is this is the intended behavior? It was not the behavior pre-v2.0.0 release, I realize with the change to returning iterators, which seems like a sound decision. However, changing the meaning of `limit` is surprising, to say the least.

**Here's what I'm expecting to get back**: 10 items *total*.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@erewok This is expected behavior — the `limit` parameter tells the SDK how many items to fetch at a time, but the iterator you get back from `folder.get_items()` will always iterate through the entire collection of items.  Please see #366 for more information, including sample code for getting only the first N items out of the iterator.

**Comment by erewok** [comment]
hmm. I would bet that other people upgrading will be bitten by this too. I'd also request a feature in the SDK to return only n items total because `limit` is a poorly worded argname here, especially when I can see repeated, individual API calls with only the offset. Seems like the SDK should surface the ability to make *only* the following request in an obvious way:

`"GET https://api.box.com/2.0/folders/SOME_FOLDER_ID/items?limit=10&offset=0\"`

The iterator part is fine (calling `next`), but this is otherwise confusing. 

Indeed, I'm less likely to care about the implementation detail of how many items the SDK specifies it should receive on *each call from the API* except in resource-constrained environments.

**Comment by carycheng** [comment]
Hey @erewok,

This is something we will consider in the future. Although `limit` might not be as well named, to change it would be a breaking change so it is not something we can put on our immediate backlog.

As for the iterator, it is something we will definitely look into for the future. However, as for now what we can do is to make sure to document the use of `iterator` explicitly so we can cut back on the confusion and frustration potentially brought to users.
