### ISSUE TITLE
Event object to python dict using`response_object` method. Throws TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by DavidQN** [box/box-python-sdk#390]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Since the event object no longer returns a python dict and rather an Event object. I am trying turn this event object to a python dict.

The method `response_object()` given to an [event object](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/base_api_json_object.py) does not convert the `event object` to a Python `dict` as stated in the 2.0 [release notes](https://github.com/box/box-python-sdk/releases) (under the search query: `response_object`) and instead throws a thread_lock error.

Looking at this it seems to be an issue on the Python package `copy`'s end or perhaps I may be using the `response_object()` method incorrectly.

### Versions Used

Box Python SDK: 2.0
Python: 3.6.1

### Steps to Reproduce

```python
def events_to_json(spoof_as_user):
    """
    Turn event object to python dict for json.dumps usage

    :param spoof_as_user:
        Client acting as a user using "as_user" method
    """

    # Retrieve all user events as iteratable
    all_events = spoof_as_user.events().get_events()

    # Grab first event within the events iteratable
    event_obj = all_events['entries'][0]

    # Format event object to a python dictionary
    print("Turn event object JSON readable using response_method(): {0} ".format(event_obj.response_object()))

```

### Error Message, Including Traceback

```
Traceback (most recent call last):
  File "example.py", line 576, in <module>
    main()
  File "example.py", line 565, in main
    events_to_json(user_01_as_user)
  File "example.py", line 505, in events_to_json
    print("Turn event object JSON readable using response_method(): {0} ".format(event_obj.response_object()))
  File "/Users/example/myENV/lib/python3.6/site-packages/boxsdk/object/base_api_json_object.py", line 156, in response_object
    return copy.deepcopy(self._response_object)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/example/myENV/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

**Comment by jmoldow** [comment]
To help debug this, can you print out `event_obj._response_object` and post it here (you can redact private information).

That exception message makes it sound like there's something in that object that we don't expect to be there. Need to figure out what that is, and why it's there.

**Comment by DavidQN** [comment]
```json
{'type': 'event',
'event_id': '--REDACTED--',
'created_by': <Box User - '--REDACTED ID--' ('--REDACTED--')>, 'created_at': '2019-01-14T11:17:49-08:00',
'recorded_at': '2019-01-14T11:17:51-08:00',
'event_type': 'ITEM_CREATE',
'session_id': ''--REDACTED--'',
'source': <Box Folder - '--REDACTED ID--' ('--REDACTED--')>}
```
When I checked the '_response_object' previously there was nothing that I didn't expect, since in the [documentation](https://developer.box.com/v2.0/reference#event-object) the example display is:
```json
{
    "type": "event",
    "event_id": "f82c3ba03e41f7e8a7608363cc6c0390183c3f83",
    "created_by": {
        "type": "user",
        "id": "17738362",
        "name": "sean rose",
        "login": "sean@box.com"
    },
    "created_at": "2012-12-12T10:53:43-08:00",
    "recorded_at": "2012-12-12T10:53:48-08:00",
    "event_type": "ITEM_CREATE",
    "session_id": "70090280850c8d2a1933c1",
    "source": {
        "type": "folder",
        "id": "11446498",
        "sequence_id": "0",
        "etag": "0",
        "name": "Pictures",
        "created_at": "2012-12-12T10:53:43-08:00",
        "modified_at": "2012-12-12T10:53:43-08:00",
        "description": null,
        "size": 0,
        "created_by": {
            "type": "user",
            "id": "17738362",
            "name": "sean rose",
            "login": "sean@box.com"
        },
        "action_by": {                
            "type": "user",                
            "id": "3147382778",                
            "name": "daniel smith",                 
            "login": "daniel@domain.com" 
        },
        "modified_by": {
            "type": "user",
            "id": "17738362",
            "name": "sean rose",
            "login": "sean@box.com"
        },
        "owned_by": {
            "type": "user",
            "id": "17738362",
            "name": "sean rose",
            "login": "sean@box.com"
        },
        "shared_link": null,
        "parent": {
            "type": "folder",
            "id": "0",
            "sequence_id": null,
            "etag": null,
            "name": "All Files"
        },
        "item_status": "active",
        "synced": false
    }
}
```
with the `created_by` and `source` attributes being an object, which in this case being `Box user`, `Box folder` objects.

**Comment by jmoldow** [comment]
We made two changes in the new SDK, which combined cause this issue:
- The introduction of `Event`, as you noted.
- The recursive translation of objects into smart objects (#140, #306)

If it weren't for that second point, the `deepcopy` would just be deepcopying a plain dictionary containing only plain data. But now, the dictionary contains other smart objects, which contain an `OAuth2` object, which contains a `threading.Lock` that cannot be copied.

Ways we can fix this:
- We can remove the `deepcopy`, and just return the underlying mapping. The risk here is that the developer might expect this to be a copy, start mutating it, and then run into bugs because this also mutates the smart object.
- We can replace the `copy.deepcopy` with a shallow `copy.copy`. This would be slightly less risky than the previous idea, but still has the same general drawback.
- We can implement `__copy__` and `__deepcopy__` on `OAuth2`, so that when we do the copy, we reuse the existing `threading.Lock` instead of attempting to copy it.
- We can implement our own deepcopy for `response_object()`, so that while we're traversing the data, if we hit another smart object, we call its `response_object()` instead of calling `deepcopy` on it. That will avoid the attempted copy of the lock.
