### ISSUE TITLE
Search function result is not correct

### ISSUE THREAD

**Issue by joanff** [box/box-python-sdk#391]
### Description of the Issue
Question 1:
I use web-api to search the file is there.
But using sdk the file is not there.
Is there any reason?

### Versions Used
Box Python SDK: // 2.0.0
Python: // python 2.7

### Error Message, Including Traceback

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @joanff, 

There could be many reasons the web app search comes back with different results from the sdk. The primary culprit that comes to mind is token scoping. With the token you are using are you sure that the user/token has access to that specific file or folder you are searching for?

**Comment by joanff** [comment]
Hi Cary,
So i'm using this to get client.
JWTAuth(
            client_id="id",
            client_secret="secret",
            enterprise_id="ent_id",
            jwt_key_id="1111111",
            rsa_private_key_file_sys_path=KEY_PATH,
            rsa_private_key_passphrase="2222222"
        )

and then client.as.user('userid')
Is this promised to be synced with web api result?

or can you show me example how to use store_token in JWTAuth?
I saw in the new documentation, there is a param in JWTAuth():
store_tokens=your_store_tokens_callback_method
how should I def your_store_tokens_callback_method() ?

**Comment by carycheng** [comment]
Hey @joanff,

There could be many issues at place here but we will try to filter down the possible causes.

1.) What is the user you are as-usering into? Is it the same user you are logging in as and can you verify that this user has access to the content you are searching for?

2.) What is the scope of the token you are using?

3.) Please note that there is an indexing delay of newly uploaded files not showing up in search for ~10 minutes.

Thank you!

**Comment by carycheng** [comment]
Thanks @joanff! Let us know if you run into any other issues, thanks!
