### ISSUE TITLE
FEATURE REQUEST: Batch/Bulk updates on Box SDK

### ISSUE THREAD

**Issue by CarolynWebster** [box/box-python-sdk#395]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
FEATURE REQUEST: I have a lot of occasions where I want to bulk/batch update group memberships, create users, create folders, etc, and having to make an individual API call for each instance is time consuming. I know batch is out on a few other sdks, any ideas of when it will be available on python?

### Versions Used
Box Python SDK: 2.0.0
Python: 2.7.15

**Comment by carycheng** [comment]
Hey @CarolynWebster,

Thank you for the input! We will implement the batch command when it is generally available. Before then, since it has not yet been generally released we cannot put this into the SDK just yet.

Thank you!

**Comment by CarolynWebster** [comment]
Is there any way to do this with the make_request()?
[https://github.com/box/box-python-sdk#making-api-calls-manually](https://github.com/box/box-python-sdk#making-api-calls-manually)

**Comment by carycheng** [comment]
Hey @CarolynWebster, 

Technically you can, however, caveat being it is not GA'd so we cannot support it if there were breaking changes to the API. We would advise against using it for now.
