### ISSUE TITLE
boxsdk 2.2.1 is incompatible with requests-toolbelt 0.9.1 

### ISSUE THREAD

**Issue by breakaway83** [box/box-python-sdk#408]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
boxsdk 2.2.1 has requirement requests-toolbelt<0.9.0,>=0.4.0, but you'll have requests-toolbelt 0.9.1 which is incompatible.

### Versions Used
Box Python SDK: 2.2.1  
Python: 2.7.15

### Steps to Reproduce
requirements.txt:
boxsdk>=1.5.3
requests-toolbelt>=0.4.0

pip install -r requirements.txt

### Error Message, Including Traceback
boxsdk 2.2.1 has requirement requests-toolbelt<0.9.0,>=0.4.0, but you'll have requests-toolbelt 0.9.1 which is incompatible.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @breakaway83,

Just to clarify, do you mean the SDK is pulling in requests-toolbelt 0.9.1 when you install or are you using requests-toolbelt 0.9.1 and need support for it in the sdk?

Thanks!

**Comment by breakaway83** [comment]
When I build boxsdk together with requests-toolbelt, it shows the warning.
I guess it is the latter:
"using requests-toolbelt 0.9.1 and need support for it in the sdk"

Weimin

**Comment by carycheng** [comment]
Hey @breakaway83,

We've filed a ticket for this in our backlog and will keep you updated once we've completed this!

**Comment by breakaway83** [comment]
Thanks.

Weimin

**Comment by carycheng** [comment]
Hey @breakaway83,

Thank you for your patience! We just release v2.2.2 of the boxsdk with updated restrictions to allow requests-toolbelt v0.9.1.

Please check it out and let us know if you run into any issues, thanks!

**Comment by breakaway83** [comment]
Thanks. Looks like it is working now.

Weimin

**Comment by carycheng** [comment]
@breakaway83,

Glad to hear Weimin! I'm going to close this ticket now.

If you come across any other issues please do not hesitate to reach out.

Thanks!
