### ISSUE TITLE
Feature Request: collaborate_with_login should allow you to add a Personal Message

### ISSUE THREAD

**Issue by mitchya1** [box/box-python-sdk#411]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When inviting a collaborator to a folder or file object via the API or SDK, you don't have the option to send a Personal Message as you do in the web application.

### Versions Used
Box Python SDK: Latest 
Python: 3.6.6

### Steps to Reproduce
Read the documentation and note that there isn't a parameter that allows you to add a Personal Message (that I've found, at least).

### Error Message, Including Traceback
N/A

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @mitchya1,

Today this feature does not exist in the API so we unfortunately cannot add this to the SDK at this time. However, we just filed a ticket with the appropriate team to address this and will keep you updated.

Let us know if you have any issues using the SDK!
