### ISSUE TITLE
The get all users in enterprise API needs to be pageable

### ISSUE THREAD

**Issue by aptxkid** [box/box-python-sdk#42]
Right now it just return a list of :class:`User`

**Comment by AllanMarcus** [comment]
Sorry to hijack this thread, but can you post the code you use to get the list of all users in the enterprise?

**Comment by jmoldow** [comment]
The `Client` class has a `users()` method that returns this list. You must be an enterprise admin for this to work. See https://box-content.readme.io/reference#get-all-users-in-an-enterprise for more information.

In the future, please direct questions to oss@box.com. We use Github issues and their comments primarily for tracking project issues and enhancements.
