### ISSUE TITLE
I have some questions about metadata.

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#420]
I have checked that the SDK documentation about metadata usage.
I wander why the SDK's function does not use a displayName for template and fields.

As the examples of the SDK usage:

file_obj = client.file(file_id='11111')
file_metadata = file_obj.metadata(scope='enterprise', template='myMetadata')

I've known that the template parameter not is a displayName for my metadata.
So I hove to use the json_response = client.make_request(...) to check up my metadata template with a displayName.

I hope the SDK easy to use visually...

### Versions Used
Box Python SDK: version 2.3.2.  
Python: version 3.6.8.

**Comment by carycheng** [comment]
Hey @c-rei,

One thing you could try doing is making a `get_metadata_templates()` call to retrieve all metadata template entries. From there you can filter for the metadata template with your particular display name.

Something like this:
```python
templates = client.get_metadata_templates()
for template in templates:
    print('Metadata template {0} is in enterprise scope'.format(template.templateKey))
```

https://github.com/box/box-python-sdk/blob/master/docs/usage/metadata.md#get-enterprise-metadata-templates

**Comment by c-rei** [comment]
Hey @carycheng 

Thank you very much for your many helps.

Your sample code looks good, I'll try it in my program.

**Comment by c-rei** [comment]
Hey @carycheng 

Instead of json_response = client.make_request(...), the function get_metadata_templates worked good.
So I'll close this issue.

Thanks.
