### ISSUE TITLE
Get Enterprise Users not returning total_count and user_ type is not working too

### ISSUE THREAD

**Issue by khurshidrpvv** [box/box-python-sdk#422]
I am trying to use get enterprise user's pagination, but response doesn't have `total_count` field.  
`user_type='managed'` has no effect too, it is returning all app users as well as enterprise users
`users = client.users(limit=1000, offset=0, filter_term=None, user_type='managed', fields=fields)`  

`print(vars(users))`  
```
#output  
{'_session': <boxsdk.session.session.AuthorizedSession object at 0x7f7119193400>, '_url': 'https://api.box.com/2.0/users', '_limit': 1000, '_fields': ['type', 'id', 'name', 'login', 'created_at', 'modified_at', 'language', 'timezone', 'space_amount', 'space_used', 'max_upload_size', 'status', 'job_title', 'phone', 'address', 'avatar_url', 'role', 'tracking_codes', 'can_see_managed_users', 'is_sync_enabled', 'is_external_collab_restricted', 'is_exempt_from_device_limits', 'is_exempt_from_login_verification', 'enterprise', 'my_tags', 'hostname', 'is_platform_access_only'], '_additional_params': {}, '_return_full_pages': False, '_has_retrieved_all_items': False, '_all_items': None, '_offset': 0}
```  

```
for user in users:
  print(user.login)
  #output  
  AppUser_793593_kf2pXqj6Yb@boxdevedition.com
  khursheed.test.user@box.com
```

**Comment by carycheng** [comment]
Hey @khurshidrpvv,

Unfortunately the total_count field is not exposed with the iterator. However, you can get back the total_count if you make a [manual call](https://github.com/box/box-python-sdk/blob/master/boxsdk/session/session.py#L93) as that returns a JSON object.

Something like this:

```python
client.make_request('GET', 'https://api.box.com/2.0/users')  
```

will give you back the JSON object with all fields.

However, the attribute `user_type` cannot act as a filter term and that is on the API side. As it stands, the best way to filter by `managed` users vs `app` users would be to retrieve all enterprise users as you are doing and while looping filter out users with `@boxdeveedition.com` email.

Please let us know if you run into any issues, thanks!

**Comment by khurshidrpvv** [comment]
@carycheng 
**manaul call** not working with keyword args.

`client.make_request('GET', 'https://api.box.com/2.0/users', limit=1000, offset=0, fields=fields)`
`Request "GET https://api.box.com/2.0/users" failed with TypeError exception: TypeError("request() got an unexpected keyword argument 'limit'",)
`  
After removing all keyword args i get `<Box Response[200]>` not json result.  

I think with `client.users()` pagination can be done manually, check if the number of results returned by iterator equals to limit, then call `client.users()` again with, updated offset.  
or is there any way to get all users in single request ?

**Comment by carycheng** [comment]
Hey @khurshidrpvv,

Sorry about that, I think there was a bit of a confusion. The third parameter for `make_request()` is actually a body for sending over requests that contains a body. I see that you are trying to access query params and that should be constructed into the url because the third parameter does not act as a builder.

Something like this:

```python
client.make_request('GET', 'https://api.box.com/2.0/users?limit=1000&offset=0&fields=login,id')
````

The reason why <Box Response[200]> shows up depends on the client you are using. If you are doing a test and would like to have logging switched on, you can use DevelopmentClient to instantiate your client in order to make this call. Please note that this switches on logging globally but will show you the results immediately in your console.

However, if this is production or you would not like to use logging then after you get a response you have to loop through it.

```python
users = client.make_request('GET', 'https://api.box.com/2.0/users?limit=1000&offset=0&fields=login,id')
for user in users:
  //do something here
```

**Comment by khurshidrpvv** [comment]
@carycheng Thank you very much.

**Comment by Jeff-Meadows** [comment]
@khurshidrpvv you can send in your query string parameters using the `params` keyword to `make_request`:

    client.make_request('GET', client.get_url('users'), params=dict(limit=1000, offset=0, fields='login,id'))

**Comment by supermitch** [comment]
Wouldn't it be relatively simple to add the total_count to the actual objects, rather than forcing us to write json GETs? I want to run an expensive search query, and I also don't think I can access the total_count through the Search object?
