### ISSUE TITLE
update_contents module does not seem to work in Python SDK 2

### ISSUE THREAD

**Issue by sathwiksrs** [box/box-python-sdk#428]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
"update_contents" module does not seem to work in Python SDK 2

I am trying to use update_contents module to upload a file that already exists in Box. I am doing it as mentioned [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#get-a-files-information): 
The expected behavior is to update the contents and the version of file in Box. It used to work for versions prior to 2.x.

### Versions Used
Box Python SDK: 
Python: 

### Steps to Reproduce
client = Client(oauth)
client.file(file_id).update_contents(local_file)
Refer:
https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#upload-a-new-version-of-a-file

### Error Message, Including Traceback
Message: Item with the same name already exists
Status: 409
Code: item_name_in_use
Request ID: 6bdj8dg32td4n83v
Headers: {'Content-Length': '465', 'Age': '0', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Encoding', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store', 'Date': 'Wed, 15 May 2019 23:40:43 GMT', 'Content-Type': 'application/json'}
URL: https://upload.box.com/api/2.0/files/content
Method: POST
Context Info: {u'conflicts': {u'sha1': u'52fb8a0a76d2d3a9eec66f7b03debd6afb8a6376', u'name': u'test.ksh', u'file_version': {u'sha1': u'52fb8a0a76d2d3a9eec66f7b03debd6afb8a6376', u'type': u'file_version', u'id': u'485119370731'}, u'sequence_id': u'3', u'etag': u'3', u'type': u'file', u'id': u'458388594143'}}

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@sathwiksrs Thank you for letting us know!  It looks like this method is calling the wrong API endpoint; we'll fix it in the next version of the SDK.

**Comment by sathwiksrs** [comment]
I tested my code again and looks like there was something wrong in my code, So the Error I pasted before is invalid. I fixed my code and the update_contents module works as expected.
Can you please verify if there is actually an issue sdk code. If not please close the Issue.
Sorry if I have raised a false alarm.

**Comment by carycheng** [comment]
Thanks @sathwiksrs, we didn't end up finding any bugs but thank you for reaching out. If you have any other issues please let us know!
