### ISSUE TITLE
Complete user API coverage

### ISSUE THREAD

**Issue by aptxkid** [box/box-python-sdk#43]
User object exists, but it can't do anything yet.

File versions can't be manipulated, and old versions can't be restored.

**Comment by dann815** [comment]
Second this request.  I can't very well tell what User is capable of if I have to traverse to BaseObject.  It would be really nice to be able to code complete on the User object too.

**Comment by Jeff-Meadows** [comment]
Sorry, @dann815 , that's not what this issue is about.

If you just want to explore the objects, I'd suggest python's ``dir()``.

    user = client.user()
    dir(user)

If you want to exclude python builtin attributes, then try:

    [d for d in dir(user) if not d.startswith('__')]

**Comment by dann815** [comment]
@Jeff-Meadows What is the plan for the User object then?

**Comment by Jeff-Meadows** [comment]
@dann815 There are certain User-specific actions allowed by the API that the SDK doesn't explicitly support:

- email aliases
- (admin only) move user's folder, change user properties, roll user out of enterprise
- change login email

Right now, any of these are possible by using ``client.make_request`` with the correct HTTP verb, URL, and parameters, but it would be a lot easier if the SDK supported these actions natively.

**Comment by mattwiller** [comment]
All [User functionality](https://github.com/box/box-python-sdk/blob/master/docs/usage/user.md) should now be supported in the SDK as of v2.0.0
