### ISSUE TITLE
box-python-sdk client.users vs API call issue

### ISSUE THREAD

**Issue by gwaters** [box/box-python-sdk#430]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I have a problem trying to get information on external users from the box sdk. I request the fields (what I would call attributes) about a user, the fields are not being populated by the users function. However if I just use python requests and query the api directly with the same fields I do get the data. Fields I am interested in: id, login, name.

### Expectation:
From the box sdk when I use box.client.users(**kwargs), I expect to get an collection of objects, where each user object will have the fields requested. 

Docs I looked at an used:
https://box-python-sdk.readthedocs.io/en/latest/_modules/boxsdk/client/client.html?highlight=external

sample code:
```
        useful_attributes = ['name', 'login', 'id', 'type']
        response_fields = str.join(',', useful_attributes)
        kwargs = {'user_type': 'external', 'filter_term': email, 'offset': 0, 'limit': 100, 'fields': response_fields}
        user_collection = self.client.users(**kwargs)
        for user in user_collection:
           print(user.id)
           print(user.name)
```
I do get the user's id, but I dont get name or any of the other fields that I requested. I have run vars and pprint on the object itself and the collection, and the pprint on the collection looks to be a construction of my query. I should mention that when I query self.client.users that are NOT user_type:external and use default parameters the collection object seems fine and has the fields of each user.

Again if you pass this to the API, you get a nested response with the info requested!!
example api code:
```
        useful_attributes = ['name', 'login', 'id', 'type']
        response_fields = str.join(',', useful_attributes)
        kwargs = {'user_type': 'external', 'filter_term': email, 'offset': 0, 'limit': 100, 'fields': response_fields}
        base_url = API.BASE_API_URL
        url = '{0}/users'.format(base_url)
        response = self.client.make_request('GET', url, params=kwargs)
```
I might be using the collection incorrectly or something I am not seeing, but right now it appears to be a bug to me, since it works with non external user type.

### Versions Used
Box Python SDK: 2.3.2
Python: 3.5.2

Thanks for your help, and let me know what else I put here to help.
-Gary

**Comment by carycheng** [comment]
Thank you for writing in @gwaters,

We will look into this and update you!

**Comment by carycheng** [comment]
Hey @gwaters,

Thanks for bearing with us! I think the problem stems from the line

```python
response_fields = str.join(',', useful_attributes)
```

The format for fields is [`an iterable of unicode`](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.client.html#boxsdk.client.client.Client.users)

Something like this should work:

```python
        useful_attributes = ['name', 'login', 'id', 'type']
        kwargs = {'user_type': 'external', 'filter_term': email, 'offset': 0, 'limit': 100, 'fields': useful_attributes}
        user_collection = self.client.users(**kwargs)
        for user in user_collection:
           print(user.id)
           print(user.name)
```

Please give that a try and let us know if you run into any other issues

Thank you!

**Comment by gwaters** [comment]
Wow, I missed that. *face palm* Thanks Cary!
