### ISSUE TITLE
Add Group Admin membership with 'configurable_permissions=None'

### ISSUE THREAD

**Issue by eirerocks** [box/box-python-sdk#432]
### Description of the Issue
**Problem**: I am attempting to add a managed user as 'Group Admin' member but ensure that they have **no additional configurable permissions**

_Please refer to Box community [post](https://community.box.com/t5/Platform-and-Development-Forum/Python-SDK-Add-Group-Admin-membership-with-configurable/m-p/70770?collapse_discussion=true&filter=location&location=category:English&q=configurable_permissions&search_type=thread):_ 

### Versions Used
Box Python SDK: boxsdk==2.4.1
Python: 3.7.3

### Steps to Reproduce
1. Attempt to add a managed user as Group Admin role to an existing group
2. Attempt to pass no additional configurable permissions i.e.

     - create new user accounts
     - manage group member accounts
     - run reports on group activity
     - Instant login to group member accounts

3. Check Group Admin role permission in users profile in Admin console (search for user, select group user is admin for / click on cog to view 'Access Level' 

**Desired Outcome**:  All of these Access Levels are unchecked when first adding Group Admin role

### My project code

```Python
def createGroupMembership(groupID, boxUserId):
    ''' for given group add user ID as a member '''

    try:
        user = sa_client.user(boxUserId)
        role = 'admin'
        membership = sa_client.group(group_id=groupID).add_member(
            user, role, configurable_permissions=None)
```
### Error Message, Including Traceback
No Error messages - The group membership is successfully created but '**configurable_permissions=None**' is being ignored. 

I suspect this issue could be linked to similar issue for shared link[ 'unshared_at' bug 424](https://github.com/box/box-python-sdk/issues/424?_pjax=%23js-repo-pjax-container) which was recently fixed

**Comment by carycheng** [comment]
Hey @eirerocks, 

Thanks for the callout! We have a pr for this that you can see here at #433

**Comment by carycheng** [comment]
Hey @eirerocks, the pr has been approved and merged, this will go out with our release targeted for Thursday. Always appreciate the callouts!

**Comment by carycheng** [comment]
Hey @eirerocks, v2.5.0 of the Python SDK went out today with the changes. Let us know if that fixes the problem, thank you!

https://pypi.org/project/boxsdk/2.5.0/

**Comment by eirerocks** [comment]
Hi @carycheng - tested v2.5.0 in my project and it worked a treat! Appreciate the quick turnaround on this new build. Feel free to mark this issue as closed / complete!

**Comment by carycheng** [comment]
Anytime @eirerocks! Always appreciate the catches in the Python SDK, let us know if you come across other issues, thanks!
