### ISSUE TITLE
`search.md` docs file is not in `usage` dir

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#444]
### Description of the Issue
The file `search.md` (https://github.com/box/box-python-sdk/blob/master/docs/search.md) is not in `usage` folder (https://github.com/box/box-python-sdk/tree/master/docs/usage) like every other file.

**Comment by carycheng** [comment]
Appreciate the call out @supermitch! We will move it to the usage folder

**Comment by mattwiller** [comment]
@supermitch I went ahead and moved `search.md` to the correct folder — thanks for letting us know it was misplaced!
