### ISSUE TITLE
Deprecation warnings for collections.abc imports

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#445]
# Description of the Issue

You are probably aware, but a head's up that when I run `pytest` I am getting three similar deprecation warnings:

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

These imports should be updated:
https://docs.python.org/3.8/library/collections.abc.html#collections.abc.Mapping

The note in 3.7 docs:
> Changed in version 3.3: Moved Collections Abstract Base Classes to the `collections.abc` module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.

`boxsdk/util/log.py:5`
    `from collections import Mapping`

`boxsdk/pagination/page.py:5`
    `from collections import Sequence`

`boxsdk/pagination/box_object_collection.py:14`
    `class BoxObjectCollection(collections.Iterator, object):`

### Versions Used
Box Python SDK: 2.6.0
Python: 3.7.2

### Steps to Reproduce

Write a test that imports boxsdk

**Comment by carycheng** [comment]
Hey @supermitch,

Thanks for bringing this to our attention! We will absolutely be updating the imports to support 3.8, we are flushing out our support for the Python SDK as 2.7 is sunset, by that time we will be doing a new release after examining/updating all our dependencies.

Thank you!
