### ISSUE TITLE
Question: Bulk download?

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#447]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I need to download all data for "Termed User" which amounts to some 17 TB of data, apparently. I contacted Box support and was told that essentially they knew of no other way than via the API. I've read through all the usage and haven't see any references to bulk download functionality. Obviously the time it will take to download that amount of data is significant, so I'm looking for help.

1. Is individual file download the best option?
2. Does the Python SDK automatically respect API rate limits?
3. I haven't seen any examples of parallel requests (e.g. using `request-futures`), is there a built-in way to make parallel requests?

**Comment by sujaygarlanka** [comment]
One option is to use the Box CLI (https://github.com/box/boxcli). It has the option to download a folder by passing in a folder ID (https://github.com/box/boxcli/blob/master/docs/folders.md#box-foldersdownload-id). This is implemented synchronously.

The other option is to use the Python SDK or other SDK to implement functionality to download a folder by individually downloading files. This will also give you the option of implementing it in a way that makes parallel requests. Currently, we don't have native functionality that does this.

Rate limits of calls per second won't be surpassed if calls are made synchronously. However, you will have to worry about rate limits if you make calls in parallel. Also, total rate limits per day may or may not be hit depending on the number of files you are downloading.

**Comment by supermitch** [comment]
Ok, thank you for the quick reply. Do you know if Box CLI has any functionality to resume a failed download? With that size of data I'm expecting it to crash at some point.

**Comment by sujaygarlanka** [comment]
The CLI does not have the ability to resume a failed download. If it fails at some point, the error thrown will alert you to where it fails, and you would have to re-download the folder that failed. The other option would be break up the folder downloads into fewer folders at a time. Sorry, but there are no better options right now. We are looking into adding a zip download endpoint for a folder, but it isn't available yet.

**Comment by sujaygarlanka** [comment]
Can I close this issue?

**Comment by supermitch** [comment]
I think I have no further questions. I will do a per-file download with a custom script. Thank you.
