### ISSUE TITLE
File.copy() missing api_call decorator

### ISSUE THREAD

**Issue by ben-reilly** [box/box-python-sdk#452]
I noticed that `File.copy()`, which overrides `Item.copy()` to add an optional version check, does not have an `@api_call` decorator, which prevents the use of `extra_network_parameters`. Is this omission intentional?

See here:
https://github.com/box/box-python-sdk/blob/ea0ad05e6208fda262199658a2b6290eb9b5a747/boxsdk/object/file.py#L678-L681

Compare with:
https://github.com/box/box-python-sdk/blob/1cec692f01631b158d0de9c97477262e302e1037/boxsdk/object/item.py#L147-L151

**Comment by nidoran** [comment]
Hi @ben-reilly, yes, the decorator was missing. I added it in this PR
https://github.com/box/box-python-sdk/pull/453
Thanks

**Comment by ben-reilly** [comment]
Thanks Albert!
