### ISSUE TITLE
Recursive folder download?

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#454]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Is there any functionality for recursive folder download? I cannot find it in the official API or the python-SDK docs, but seems like a very standard operation. Is it possible?

### Versions Used
Box Python SDK: 2.6.0
Python: 3.7.x

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @supermitch,
This functionality is not available currently, but I believe something similar ("download folder as a zip file") is on the roadmap for the near future!  It should appear as a new endpoint in the API documentation, first, and later in the SDK.  I'll reply back here in the next day or so with a ball park timeline for you.

**Comment by supermitch** [comment]
Great. Does the SDK have any plans to implement features not directly available in the API? It seems the SDK is so far very "feature parity", including what you've described. If not, perhaps a new repo that wraps this one would be a good idea.

**Comment by PJSimon** [comment]
@supermitch Great suggestion!  I created a ticket for adding a convenience method in the SDK to do the work of making recursive download calls, for each item in a folder.  I'll review it with my team soon!

With our development of the new iOS SDK in Swift (releasing soon), we have also expanded the SDK to include more convenience methods that go beyond the API endpoints.  In the future, we will be replicating these convenience methods for parity across all the Box SDKs that we support.

**Comment by supermitch** [comment]
Thanks for the reply, and thanks for the great code.

**Comment by PJSimon** [comment]
Hi @supermitch!  The team working on adding a "download folder as a zip file" API endpoint is looking to have it in Beta in December and publicly released in February!

**Comment by aberenyi** [comment]
Hey @PJSimon - sorry about the necrobumped issue, but I was wondering whether this feature (i.e. download folder as a zip file) will make its way to the other SDKs as well?
At the moment it's a pain in the back to download folders regardless the actual channel (i.e. API or SDK) and it would be really nice if the node.js SDK could have this feature too.

It's almost February - looking forward to seeing this in the changelog!
