### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'total_count'

### ISSUE THREAD

**Issue by NorihitoInoue** [box/box-python-sdk#462]
I checked box-python-sdk/docs/usage/folders.md, and run the script.
The code below returned AttributeError.
I wrote the script as written in "Get Information About a Folder" section.

```
folder = client.folder(folder_id='xxxxxx').get()
print('Folder "{0}" has {1} items in it'.format(
    folder.name,
    folder.item_collection.total_count,
))
```

I changed the 4th line to ```folder.item_collection['total_count']``` and it worked.
Is it a typo?

**Comment by carycheng** [comment]
Hey @NorihitoInoue this is a typo and we will fix it in the docs, thank you for pointing this out!

Please continue accessing properties on item_collection with bracket notation. 

Thank you

**Comment by NorihitoInoue** [comment]
Thanks you!
