### ISSUE TITLE
get_admin_events Function Fails When Optional event_types Parameter is Omitted

### ISSUE THREAD

**Issue by aculler** [box/box-python-sdk#463]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When using the [get_admin_events](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#99) function, if you do not provide the `event_types` parameter (listed as optional) then it fails trying to pass `None` to a `join()` call [here](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L132).

### Versions Used
Box Python SDK: 2.6.1
Python: 3.7.3

### Steps to Reproduce
1. Create an authenticated client object (we're using JWT)
2. Create an `events` object using `client.events()`
3. Attempt to pull admin events using a command similar to `events.get_admin_events(limit=10, created_after='2019-10-31T08:00:00-0000')`. Both of those arguments are optional, but they were my test values, so they're probably worth using to reproduce.

### Error Message, Including Traceback
```
>>> events.get_admin_events(limit=10, created_after='2019-10-31T08:00:00-0000')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path/to/project/venv/lib/python3.7/site-packages/boxsdk/util/api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
  File "/path/to/project/venv/lib/python3.7/site-packages/boxsdk/object/events.py", line 132, in get_admin_events
    'event_type': ','.join(event_types),
TypeError: can only join an iterable
```

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by aculler** [comment]
This is a simple fix. I'll have a PR open shortly.

**Comment by aculler** [comment]
It's probably worth noting that I tested manually making the request that the `get_admin_events` function makes, fully omitting the `event_types` parameter from the request and it completes successfully:

```
>>> params = {'created_after': '2019-10-31T08:00:00-0000', 'created_before': None, 'stream_type': 'admin_logs', 'limit': 10}
>>> events._session.get(events.get_url(), params=params)
<Box Response[200]>
```

**Comment by aculler** [comment]
I have the PR opened. However, per the documentation (https://github.com/box/box-python-sdk/blob/master/CONTRIBUTING.rst#step-8-send-the-pull-request) there should be an "Upcoming" section in the HISTORY.rst and I didn't see one, so I didn't add this fix to it. If that should be added, please let me know where to add it and I will, but it's a pretty minor fix.

**Comment by sujaygarlanka** [comment]
Hey @aculler,

Thanks for the pull request! Just reviewed it, and it looks good. Before I merge the change, could you add an Upcoming section below the Release History header and add your change?

**Comment by aculler** [comment]
Hey @sujaygarlanka,

I've added that and pushed it to the branch. Thanks so much!

**Comment by aculler** [comment]
@sujaygarlanka I'm not sure why the CI failed on that run. Only the HISTORY.rst was changed.
