### ISSUE TITLE
hiding text when using folder.get_items()

### ISSUE THREAD

**Issue by keweik** [box/box-python-sdk#465]
I would like to hide the text when running the folder.get_items(), is this possible?

**Comment by sujaygarlanka** [comment]
What text are you referring to? The code in our docs is the following:
`items = client.folder(folder_id='0').get_items()
for item in items:
    print('{0} {1} is named "{2}"'.format(item.type.capitalize(), item.id, item.name))`
If you are using that, then removing the print statement will remove any text that is printed out.
