### ISSUE TITLE
Any reason why my root folder is empty?

### ISSUE THREAD

**Issue by keweik** [box/box-python-sdk#466]
I used JTW authentication where i downloaded the file after making the public key, and read it in python, but when i run: 
`client.root_folder().get()`
i get 
`<Box Folder - 0 (Alle filer)>`

**Comment by cbetta** [comment]
Hi @keweik. When you use JWT auth, you are not authenticated by default as a regular use (e.g. you) but as a service account This service account has its own root folder, which is empty.

You can read more about our user model here.

https://developer.box.com/en/guides/authentication/user-types/

You can act on behalf of another user (e.g. yourself) using the As-User header. https://developer.box.com/en/guides/authentication/jwt/as-user/

**Comment by keweik** [comment]
Thanks for the replay @cbetta! 

So as a user of Box, i will not be able to access the Box folders using the JWT auth?
[](https://community.box.com/t5/Developer-Troubleshooting/API-Content-API-403-quot-access-denied-insufficient-permissions/ta-p/48536)

**Comment by cbetta** [comment]
You can, you just need to use the as-user header to switch user. Please see the guide I provided for details.

**Comment by carycheng** [comment]
Hey @keweik, @cbetta is absolutely right, to give a python specific implementation for @cbetta's suggestion you can use:

```python
user_to_impersonate = client.user(user_id='USER_ID_GOES_HERE')
user_client = client.as_user(user_to_impersonate)
```

For more information and context please refer to [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#as-user)

**Comment by PJSimon** [comment]
@keweik I'm going to go ahead and close this issue as it appears resolved.  If you have any further questions, please don't hesitate to re-open it and let us know!
