### ISSUE TITLE
How to disable logging in network layer.??

### ISSUE THREAD

**Issue by farehakaukab1** [box/box-python-sdk#467]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue
### Versions Used

Box Python SDK:  2.6.0
Python: 3.6

### Steps to Reproduce
        from boxsdk import Client, JWTAuth
        sdk = JWTAuth.from_settings_file(env.JWT_TOKEN_PATH)
        logger.warning("Box sdk token verified")
        client = Client(sdk)
        response = client.make_request("GET", events_api_url)

### Error Message, Including Traceback
I dont want to see these logs

[2019-11-26T10:31:51+0500] INFO boxsdk.network.default_network "GET https://api.box.com/2.0/events/?stream_type=admin_logs&limit=500&stream_position=1152923079311515440" 200 74
{'Date': 'Tue, 26 Nov 2019 05:31:50 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'BOX-REQUEST-ID': '093095e9e3f476fbc4d1a1dfcd284ed7e'}
{'chunk_size': 0, 'entries': [], 'next_stream_position': '1152923079311515440'}

**Comment by PJSimon** [comment]
Hi, @farehakaukab1! Thanks for submitting this issue. This week is the Thanksgiving holiday, so we will take a look next week and get back to you.

**Comment by dtrodger** [comment]
@farehakaukab1 controlling what logs are sent to stdout should be configured when you setup your logger. This is a common design that can be used for much more than suppressing box sdk logs. The snippet below will configure your logger to send only error level logs and above to a file handler, so box sdk logs wont be sent to stdout and you'll still be able to capture important box sdk logs in a file.

`
LOGGING_CONFIG = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'stdout': {
            'level': 'INFO',
            'formatter': 'standard',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout'
        },
        'error_file_handler': {
          'level': 'ERROR',
          'formatter': 'standard',
          'class': 'logging.RotatingFileHandler',
          'filename': error.log,
          'mode': w,
          'maxBytes': 10485760,
          'backupCount': 20,
          'encoding': utf8
        },
    },
    'loggers': {
        '': {
            'handlers': ['stdout', 'error_file_handler'],
            'level': 'INFO',
            'propagate': False
        },
        'boxsdk': {
            'handlers': ['error_file_handler'],
            'level': 'ERROR',
            'propagate': False
        }
    }
}
logging.config.dictConfig(LOGGING_CONFIG)
log = logging.getLogger(__name__)
`

**Comment by mjunaidrazzaq323** [comment]
You can do this to set logging level to WARN or ERROR
`logging.getLogger("boxsdk.network.default_network").setLevel(logging.WARNING)`
