### ISSUE TITLE
Add seamless shared item headers

### ISSUE THREAD

**Issue by ianunruh** [box/box-python-sdk#47]
To interact with shared items from the API, the `BoxApi: shared_link=SHARED_LINK` header must be included with requests.

My idea here would be to add a `_headers` dict to `BaseObject`. Then when `get_shared_item` is called with the share URL, it passes the header down to the `Folder` or `File` object. When requests are made on these items (`File#content`, `File#download_to`, `Folder#get_items`), they would use the `BoxApi` header and pass the header down recursively to subitems (when applicable).

Another, less generic solution would be to add `_shared_link` to `Item` and craft the headers from that.

**Comment by Jeff-Meadows** [comment]
Hi Ian, I hope #54 provides a seamless experience with shared items. If not, feel free to reopen and explain why not!
