### ISSUE TITLE
Documentation for add_email_alias needs to be better

### ISSUE THREAD

**Issue by gwaters** [box/box-python-sdk#470]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Problems trying to add an email alias to an account.
The documentation leads you to believe you can add valid email aliases to an account, but this is not without caveats. With an error of "Invalid value", you would think that your are not using the documented function correctly or your alias is not in the correct format, but that is not the case. For an enterprise account, I wanted to use an alternate subdomain, fun.example.com or perhaps my @gmail.com email address, both come back with "invalid value". After some lucky trial error, it was determine that the alias has to be in the exact domain of the account (example.com, and not fun.example.com or @gmail.com) Note: my email domain is not example.com, and I did really try using my valid email domain and valid sub domain. 
Can you update the docs to let people know that the if you get invalid value, that it has to be your current domain or something ? Or have the error be more specific.

### Versions Used
Box Python SDK: 2.4.1
Python: 3.6.7

### Steps to Reproduce

My Code (user id and email are replaced with real emails and ids):

        user_id = '3333'
        email='someone@email.com'
        user = self.client.user(user_id)
        print(type(user))
        print(email)
        alias = user.add_email_alias(email)
        return alias

### Error Message, Including Traceback
<class 'boxsdk.object.user.User'>
someone@email.com
"POST https://api.box.com/2.0/users/218950850/email_aliases" 400 298
{'Date': 'Mon, 23 Dec 2019 22:15:14 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'BOX-REQUEST-ID': '0c772a7c7fd97fe7d43835910b23ffb2a'}
{'code': '---uest',
 'context_info': {'errors': [{'message': 'Invalid value '
                                         "'someone@email.com'.",
                              'name': 'email',
                              'reason': 'invalid_parameter'}]},
 'help_url': 'http://developers.box.com/docs/#errors',
 'message': 'Bad Request',
 'request_id': 't7dxynga7eglqh1i',
 'status': 400,
 'type': 'error'}

[sdk-docs]: ./docs/usage
SDK Docs Example:
Add Email Alias
To add an email alias for a user, call the user.add_email_alias(email) method with the email address to add as an email alias for the user. This will allow the user to log in and be collaborated by this email in addition to their login email address. The method returns an EmailAlias object.

user_id = '33333'
user = client.user(user_id)
email_alias = user.add_email_alias('alias@example.com')

[api-docs]: https://developer.box.com/docs
source:
    def add_email_alias(self, email):
        """
        Adds a new email alias to the given user's account.

        :param email:
            The email alias to add to the user.
        :type email:
            `unicode`
        :returns:
            The new email alias object
        :rtype:
            :class:`EmailAlias`
        """
        url = self.get_url('email_aliases')
        body = {
            'email': email,
        }
        response = self._session.post(url, data=json.dumps(body)).json()
        return self.translator.translate(
            session=self._session,
            response_object=response,
        )

**Comment by PJSimon** [comment]
Hi @gwaters!
Thanks for creating this issue!

We're going to be slow to respond to issues this week and next, due to the Christmas and New Years holidays, but I just wanted to let you know that we received your message. 

If you need this escalated, please let us know, otherwise we will talk to you again in early January!

Thanks again! 

Patrick

**Comment by gwaters** [comment]
Merry Christmas Guys =D
Have a good one!

-Gary

**Comment by sujaygarlanka** [comment]
@gwaters Added documentation to help with this issue here: https://github.com/box/box-python-sdk/blob/master/docs/usage/user.md#add-email-alias. Thanks for the feedback!
