### ISSUE TITLE
How to validate a client?

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#480]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am doing the following:

1. Get JWT client using file config (works)
2. Get a user `user = jwt_client.user(user_id)`
3. Get a user client: `self.user_client = jwt_client.as_user(user)`

Surprisingly, this works entirely even if I use `None` as my user ID! Both the `user` object *and* the `user_client` are created successfully.

Which leads me to my question: What is the easiest way to verify that a `client` has been correctly initialized?

In the docs, all I see is `client.user(<some id>).get()` as a test. I realize that I could `get()` the user in step 2 (at least to validate the user exists) but that doesn't actually prove the client was created successfully.

Later, the client (if it was created _incorrectly_) just causes the SDK to return 404s when I try to find a specific folder! Which is extremely confusing.

Thoughts?

### Versions Used
Box Python SDK: 2.6.0
Python: 3.7.2

### Steps to Reproduce
See above

### Error Message, Including Traceback
Here's the response. All it tells me is that a folder cannot be found:
```
<Box User - None>  # Note! None ID passed here (intentionally), but user object exists.
<boxsdk.client.client.Client object at 0x110936080>  # Note! Client objects exists.
"GET https://api.box.com/2.0/folders/846/items?offset=0" 404 322
{'Date': 'Wed, 15 Jan 2020 00:45:46 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'BOX-REQUEST-ID': '0c49f27f592c72'}
{'code': '---ound',
 'context_info': {'errors': [{'message': "Invalid value 'd_846'. "
                                         "'folder' with value 'd_846' "
                                         'not found',
                              'name': 'folder',
                              'reason': 'invalid_parameter'}]},
 'help_url': 'http://developers.box.com/docs/#errors',
 'message': 'Not Found',
 'request_id': 'k9h7im',
 'status': 404,
 'type': 'error'}
```

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @supermitch,

We'll take a look at this and get back to you soon!

Thanks,

Patrick

**Comment by sujaygarlanka** [comment]
Hello @supermitch, The only way to test whether the client and user were correctly created is to make a call and read the error. We have no validation logic to check whether the user ID passed in is none. Beyond that, there is little validation we can do in the SDK other than to make an API call. We leave this validation to developer to avoid any extra API calls.

**Comment by supermitch** [comment]
Ok. And what are your thoughts on a 401 or 403 instead of a 404, when the User Client is invalid? I guess I don't know the inner workings of the user client, but in this case the issue is clearly one of permissions, no? Seems like the misleading error is perhaps the bigger issue. You say make a call and read the error but that doesn't actually validate the client.

**Comment by sujaygarlanka** [comment]
@supermitch In your case, since you are passing in an invalid user ID, the API endpoint could be checking for a folder for that user ID and not find it because the user doesn't exist. If you make the `client.user(<some id>).get()`, you should get an appropriate error that will help you determine whether the user is valid. To address your earlier concern, if your client is invalid, you should get a different error than if your user is invalid.

**Comment by sujaygarlanka** [comment]
@supermitch Can I close this issue?
