### ISSUE TITLE
How to create a shared link with a custom name?

### ISSUE THREAD

**Issue by manfredlotz** [box/box-python-sdk#492]
Using boxsdk 2.7.1 I am unable to find how to create a `non private custom URL` pointing to a file. 

In the browser for a file I can click on `Share` and then click on `Link Settings` where I can create a custom url and specify the name I like (of course the name must be unique).

Is there a way to achieve this with boxsdk. Thanks a lot.

**Comment by PJSimon** [comment]
@manfredlotz 
https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#create-a-shared-link

In the future, when creating an issue, please include the template text, especially regarding checking the box for:
> - [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

Thanks!

**Comment by manfredlotz** [comment]
Sorry for not including the template text. The link you gave me was the first thing I tried before opening the question here.

But it doesn't help to solve my issue as it just gives me a link. 

I want to be able to specify my own name as I can do when I do this in the browser. 

In the browser I can click `Link Settings` and in the new window I can activate `Publish content broadly with a custom, non-private URL`. Then I have a possibility to enter a custom path with 12 or more characters.
