### ISSUE TITLE
Upcoming changes to Box Metadata API response format

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#496]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Versions Used
Box Python SDK: 
Python: 

### Error Message, Including Traceback

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/

**Comment by c-rei** [comment]
I received an e-mail from The Box Team about upcoming changes to metadata related features in the Box API. The schedule for this issue is below.
Phase1 - Beginning on or after April 23,2020
  Datetime field values stored in Box metadata templates and instances will be returned in a more consistent format, etc.
Phase2 - Beginning on or after May 21, 2020
  Error codes and messages returned in response to invalid metadata API calls will change to be simpler and more consistent.

My request is that could you give us a new version of the box python sdk for those changes until above dead line?

Best regards.

**Comment by sujaygarlanka** [comment]
@c-rei The Python SDK currently supports these two changes. 
- The SDK returns the json object from the response, so you will have access to the consistent Datetime format. 
- Also, for invalid metadata API calls, the SDK returns the error codes and messages.

**Comment by c-rei** [comment]
@sujaygarlanka 
Thank you for your response.
