### ISSUE TITLE
Events.get_admin_events has no "stream_position" parameter

### ISSUE THREAD

**Issue by putopavel** [box/box-python-sdk#498]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I observed that from the [Get Enterprise Events guide](https://developer.box.com/guides/events/for-enterprise/) and [events API reference](https://developer.box.com/reference/get-events/) in order to get all the logs from an enterprise you need to specify the `stream_type` query parameter to `admin_logs` in the API request. This can be achieved using the [`Events.get_admin_events`](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L99-L140) function call. However, this function does not accept a `stream_position` argument as [`Events.get_events`](https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L62) does, which makes it impossible to iterate these admin logs response (as explained in [this forum post](https://community.box.com/t5/Platform-and-Development-Forum/help-with-event-stream/m-p/35970)). Given this problem, the only thing I can do is:

1. Get the logs from a very little time range by using the `created_after` and `created_before` query parameters hoping that there are no more and I obtained all of them in a single call.
2. Not using the Python SDK, leveraging the collection of these logs by the REST API.

### Versions Used
Box Python SDK: 2.7.1
Python: 3.7.7

### Steps to Reproduce

1. Create a `Client` instance.
2. Check that when calling `client.events().get_admin_events` there is no possibility to add a `stream_position` parameter.

### Error Message, Including Traceback

If you try to pass the `stream_position` parameter, you get the following error:

```python
>>> events = client.events().get_admin_events(created_after="2020-04-20T07:48:28-07:00", created_before="2020-04-22T07:48:28-07:00", stream_position="1152923092173566334")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/pavel/.local/share/virtualenvs/box-collector-ljaeMLeM/lib/python3.7/site-packages/boxsdk/util/api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
TypeError: get_admin_events() got an unexpected keyword argument 'stream_position'
```

### Extra
By the way, I think that the examples shown in [Get Enterprise Events guide](https://developer.box.com/guides/events/for-enterprise/) are exactly the same that in [Get User Events guide](https://developer.box.com/guides/events/for-user/) for all cURL, Python and Node, so I think that the first guide must be changed.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/

**Comment by putopavel** [comment]
I finally solved it by getting the session myself and making the API call:

```python
events = client.events()
box_response = events..session.get(
    events.get_url(),
    params={
        "stream_type": "admin_logs",
        "created_after": created_after,
        "created_before": created_before,
        "stream_position": stream_position,
    },
)
```

box_response will be a requests Response object.

**Comment by putopavel** [comment]
Don't you at least consider adding that parameter to the library? It might be the case that some other people might need this as well.

**Comment by arsabolsky** [comment]
Yes, I agree. It makes no sense that this is not a parameter.
