### ISSUE TITLE
Primary Access Token or OAuth2 Refresh

### ISSUE THREAD

**Issue by BryanAM** [box/box-python-sdk#499]
Hi,

I'm new to boxsdk and Auth in general. I've been working with the BOX api to query specific files and directories.

I have used the python-sdk to make API calls successfully using OAuth2 and the developer token. However, I need the token (or my general session) to last longer than 60mins. I noticed I can make an application of type "App Token (Server Auth)"  and utilize the primary and or secondary token However, I wasn't able to find any documentation on how to connect with the API with that type of application. 

I did read through the authentication.md and attempted the Box View Authentication with App Tokens but no success. I get an error message that seems to indicate it doesn't like my primary token.

```
...
WWW-Authenticate': 'Bearer realm="Service",
error="invalid_token", 
error_description="The access token provided is invalid."', 
```

My setup for OAuth2 is simple and I'm using .env variables. Is there an easy way to utilize the primary tokens with OAuth2? 
```
auth = OAuth2(
  client_id=CID, 
  client_secret=CS, 
  access_token=ATOK
)
CLIENT = Client(auth)
```

**Comment by PJSimon** [comment]
Hi @BryanAM !  Thanks for opening this Issue.  We'll take a look ASAP!

**Comment by sujaygarlanka** [comment]
@BryanAM If you want a long lasting token, I would recommend using JWT authentication. The instructions for doing this in the Python SDK can be found [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#server-auth-with-jwt). The only other thing that needs to be done is to get the JWT config file. This can be downloaded from the developer console when you change your app Auth method from OAuth to JWT. More information about JWT can be found on our dev [docs](https://developer.box.com/guides/authentication/jwt/). I hope this helps. If you have any follow up questions, feel free to re-open this issue.
