### ISSUE TITLE
Use third-party LRU Cache Instead

### ISSUE THREAD

**Issue by aptxkid** [box/box-python-sdk#5]
There are several Python LRU Cache packages:
- https://github.com/jlhutch/pylru
- http://pythonhosted.org/cachetools/

**Comment by aptxkid** [comment]
Our own implementation of the LRU cache serves our purpose and usage pretty well. I don't think either pylru or cachetools is a better fit even though they are both awesome implementations of LRU cache in Python.

**Comment by kunalparmar** [comment]
@aptxkid can you elaborate on why these (or any other) do not meet our requirements?

**Comment by jmoldow** [comment]
Can we consider using a backport of the Python 3 ``@lru_cache``? For example, https://pypi.python.org/pypi/backports.functools_lru_cache/1.0.1

**Comment by aptxkid** [comment]
@kunalparmar One needs to explicitly specify a value in both pylru and cachetools. But we only need to cache `event_id` at this moment. I consider `cache[event_id] = None` more confusing than `cache.set(event_id)` for just caching an event_id.

**Comment by kunalparmar** [comment]
@aptxkid you could store any value you'd like. I would imagine the code to be -
```python
...
for event, next_stream_position in self._get_all_events_since(stream_position):
    event_id = event['event_id']
    try:
        event_ids[event_id]
    except KeyError:
        yield event
        event_ids[event_id] = event_id
...
```
OR
```python
...
for event, next_stream_position in self._get_all_events_since(stream_position):
    event_id = event['event_id']
    if event_id not in event_ids:
        yield event
        event_ids[event_id] = event_id
...
```

**Comment by Jeff-Meadows** [comment]
I see no need to refactor this at this time. Closing for now until we need to cache something else and a more complete solution might be an improvement over what we have.
