### ISSUE TITLE
An error about file.content(byte_range=(offset, block)

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#508]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I want to make a checksum for a big file on the Box.
So I writes some code like below ### Steps to Reproduce,

My file size is 5892641, I got it with below:
report_file = client.file(file_id='656476963503').get()
report_file.size => 5892641

But when I tried that report_file.content(byte_range=(131073, 2048 * md5.block_size),
that just is a second read, (md5.block_size = 64) I got an error like below ### Error Messages, Including Traceback

What's wrong with my code or some other causes?

### Versions Used
Box Python SDK: 2.8.0
Python:  3.6.10

### Steps to Reproduce
import hashlib

 offset = 0
 md5 = hashlib.md5()
 while offset < report_file.size:
     chunk = report_file.content(byte_range=(offset, 2048 * md5.block_size))
     md5.update(chunk)
     offset += len(chunk)

### Error Messages, Including Traceback
[31m"GET https://dl.boxcloud.com/d/1/b1!dg350ZXXGR0mUJFv8PtAV7C9Pz73Stnfu2HaWoR_SVMa31CxLF6TKDZoJjzarpOOgDUNLwxrxuuh4l8HQy6oK1OoU8lXkKSqMwXewbLQHcQPOImgE_FAzOL8KbClSwta35SgKAo_Clwzjf-Zm06MRXjp5RsJ9BeraPG6c6HehiLRXlgHL9f1fav57y9sxCM_VqDkfkdcd0lpDL3uaDF64BOD4hGvjusEHgxqQcokAAtGl4DYJiDVnM2ui5yz4OsuFSeW_8N1hCU67mgdmoInI3dAG-sKX-Ckw_QWefjR7cPnvk8OgMobpvuZXmm2MqjO1R0xdvvu6i_7w7jrP8KTk1tTWWlU5aNf-yot8oMXnsBtbKYzYrDq5OPI9SZDoCZFv5TM8WtielgIJEZmsesTCMeWySFZF7fHgTRhnPxPfeiMJrSUtlN-SmZRqczvznFeMNylokqY_Bt3cG133ch6l3Mg73HzeiJQZY5kz46yBfjzeIKHm4PB_qgEFlZwxT3SQ_zGmnEA3DSTFHPNlqpcmFI-e73-tNG6q0yIsZTBPBMc95ucGTtrYWGJOLAXIyD6Uzf00Zj8N7pL6mvbemQnlaDT6pUGqlhJLM4cuhecW4G3JH8nj4xjZA1W0OLgWX_iqxq-Xo9qahXx4XdEpksxe6CcQKUob9R3P6D-oMFqgkgbE3Se29-MKwxnI5kfvS_wrhLGtFrgNCBbtSknpLjDvqHbiYYn27Ty8pB5dxU5VdskmWLU3Y_YqrcOyzNL0Vg_J7QIPlKjNURD9mNP2gVqnT7nNzI7n_UTbrIFVbtom1M75PbLAz9Sy2KxfNUP1_cAM4rREmMHm3Ah9BKPxWZdQX9CZDj4GlP6LHKWpOYhu7StyRSJTDcLE_5jtrkEAeHxCKDwPBmGv7DBriQm3-xxCC17id4_fzZe2n3paZUh2_qlfZkCYMWNDVoepTJzEiiXolC0kN9XhgsYCnv0FJkC8DawsmYtQqKhXIJ6e6Elw-tG1w1OMbd2oDyVKNrloNQd10xq3KCbUHPR8BvRi73X2W2qHtixUqwq39F8rTxedfJ1y6kdeMePWvN2T7bboj5fXoVOCUjEPmWi2e-b13_cQZAfZ8EYhrF-0lQcd_zxGBmCjoJBqov-7A88_rVhxrmLvEiucnKkFNgfS9fy90b4ErpoGUtnw3dpSmlOgS8QR2WPimZcdxCQ6UM6jr7OU2zgT66FcptZAKcmrCzplM7tQyJTzYFr2QfeScKaEH8teODA7q6-69IyY0aBsXurCT-z4IBH_okvwsBPhumDmsrEdCBxPv5IPDoFdkdEzzXVQFPSL9hurqfQD8Hp-o_J/download" 400 0
{'Date': 'Tue, 05 May 2020 07:07:37 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000'}
b''
[0m
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\util\api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\object\file.py", line 154, in content
    box_response = self._session.get(url, expect_json_response=False, params=params, headers=headers)
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\session\session.py", line 102, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\session\session.py", line 158, in request
    response = self._prepare_and_send_request(method, url, **kwargs)
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\session\session.py", line 406, in _prepare_and_send_request
    self._raise_on_unsuccessful_request(network_response, request)
  File "C:\Users\ChangQun\AppData\Local\anaconda3\envs\py36\lib\site-packages\boxsdk\session\session.py", line 329, in _raise_on_unsuccessful_request
    network_response=network_response
boxsdk.exception.BoxAPIException: Message: None
Status: 400
Code: None
Request ID: None
Headers: {'Date': 'Tue, 05 May 2020 07:07:37 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000'}
URL: https://api.box.com/2.0/files/656476963503/content
Method: GET
Context Info: None

[sdk-docs]: https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#download-a-file

**Comment by Jeff-Meadows** [comment]
not sure why you get the error on the byte range request, but you don't need to use byte range in order to calculate the hash. for that, you can just use the `download_to` method with a "stream" that just calculates your hash.

    class HashingStream:
        def __init__(self):
            self._hash = hashlib.sha1()

        def write(self, chunk):
            self._hash.update(chunk)

        @property
        def sha1(self):
            return self._hash.hexdigest()

    stream = HashingStream()
    report_file.download_to(stream)
    print(stream.sha1)

**Comment by c-rei** [comment]
Thank you for your response. I'll try that advised from you.
But I'm worry that if I have a big file, the calculation may be crush.

**Comment by c-rei** [comment]
I tried your method, it works smoothly and rapidly.
Thank a lot.
