### ISSUE TITLE
SSL verify

### ISSUE THREAD

**Issue by YoungBim** [box/box-python-sdk#513]
https://github.com/box/box-python-sdk/blob/6a7a94182f2d525cebd9c7f473c36544f06fc3fd/boxsdk/object/file.py#L291

I'm trying to use the update function of box. In order to avoid an "SSL error" I need to pass a parameter "verify=false" to this post... I hacked locally my pip package to have it working, would be great if this parameter could be passed directly from parent functions.

**Comment by PJSimon** [comment]
Hi @YoungBim ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by sujaygarlanka** [comment]
@YoungBim Thank you for the feedback! We looked into this, and we don't plan on adding the verify parameter to the method. Our two reasons for this are that it is not a commonly used and we would like to only include parameters we think are likely to be used and we want to encourage people to use https to make requests to our API. For the case where people would like to disable SSL, we have the option for them to make manual requests with the SDK. If you have any further questions or comments, feel free to re-open this issue.
