### ISSUE TITLE
Downscope token to a folder and getting 'The target resource is invalid' 400 error

### ISSUE THREAD

**Issue by jennuineness** [box/box-python-sdk#532]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
    * https://support.box.com/hc/en-us/community/posts/360049156614-How-to-get-a-Downscoped-Token-for-a-file-or-folder
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I created a Custom App configured with the App Token (Server Authentication) method in the Box developer console. I am having a difficult time downscoping my access token to a specific **folder**. Downscoping to the **file** works though. 

I followed this document using the Python SDK:
https://developer.box.com/guides/authentication/access-tokens/downscope/

The call works with curl and Postman; however, I am unable to get it working via the Python SDK or the Python requests library.

### Steps to Reproduce
```
from boxsdk import Client, OAuth2

auth = OAuth2(
    client_id="CLIENT_ID"
    client_secret="",
    access_token="CLIENT_APP_TOKEN",
)

client = Client(auth)

target_folder = client.folder(folder_id='FOLDER_ID_HERE')
token_info = client.downscope_token(['item_preview'], target_folder)
print('Got downscoped access token: {0}'.format(token_info.access_token))
```

### Expected Behavior
I expected a print output of the downscoped token.

### Error Message, Including Stack Trace
```
boxsdk.network.default_network:default_network.py:270 "POST https://api.box.com/oauth2/token" 400 82
{'Date': 'Fri, 21 Aug 2020 19:00:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'box_visitor_id=5f4019c11980b3.93255485; expires=Sat, 21-Aug-2021 19:00:17 GMT; Max-Age=31536000; path=/; domain=.box.com; secure, bv=OPS-43932; expires=Fri, 28-Aug-2020 19:00:17 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure, cn=54; expires=Sat, 21-Aug-2021 19:00:17 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure, site_preference=desktop; path=/; domain=.box.com; secure', 'Cache-Control': 'no-store'}
{'error': 'invalid_resource',
 'error_description': 'The target resource is invalid.'}
```

### Versions Used
Python SDK: `boxsdk==2.9.0`
Python: `Python 3.7.3`

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by jennuineness** [comment]
Hi @PJSimon ! I just wanted to report that downscoping a token to the folder is working now. I am not entirely sure what happened but the requests are now working in both the box Python SDK and the requests library.

**Comment by PJSimon** [comment]
@jennuineness , we really appreciate you circling back with us on this to close the Issue.  If you determine what the cause was, please let us know, even if it was a local configuration issue or similar.  

We were able to verify that the downscoping functionality at least works.  :^)

The next thing we would have suggested is to look at the token you are using to create your client.  With curl and Postman, you are probably using a Dev Token, so that could explain why there's (was) a discrepancy with your Python app.

As this is now closed, we're not going to investigate further, but would love to hear back if / when you find out what it was.  If not, no worries.

Thanks again!

**Comment by beaero** [comment]
I am facing the same issue. My downscope code works if I use the developer key but not the json config. Double verified, everything in my config is fine and it does create an access token. I am using trial version as of now. Anything to do with that?
