### ISSUE TITLE
Delete Trash of all Users in Client

### ISSUE THREAD

**Issue by StefanMarchand** [box/box-python-sdk#537]
Hello all, I'm trying to delete the Trash of all users of a client if the files in the trash are older than 90 days old. The documentation for getting all trash for users seems to only get the trash for the current user:

trashed_items = client.trash().get_items()
for trashed_item in trashed_items:
    print('The item ID is {0} and the item name is {1}'.format(trashed_item.id, trashed_item.name))

Is there a way to iterate over each user for a client and delete those trashcan items? I'm using the python SDK.

**Comment by sujaygarlanka** [comment]
@StefanMarchand To delete the trash of all users, you have get all the users as described [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/user.md#get-enterprise-users), customize the client for each user using the code shown [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/user.md#get-enterprise-users) and then execute the code you have above with as-user client. Hope this helps! If you have any follow up questions, feel free to re-open this issue.

**Comment by StefanMarchand** [comment]
Thanks for the help! When I run the client.trash().permanently_delete_item(trashed_item) method with as_user i get an 403 error "not authorized". And when I try to delete the files as an admin I get 404 not found. Is there a way to delete other users trashed files as an admin?
