### ISSUE TITLE
Api call to trash items continues endlessly

### ISSUE THREAD

**Issue by StefanMarchand** [box/box-python-sdk#538]
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I'm using the Box Api to get all of the trash for all users of a client and save a few fields to a .csv file. When I run the code below the code will run as expected for a little while than gets stuck and appears to re-run the request with a continually increasing offset each run. I'm using the python SDK.

Code:
import csv
    from boxsdk import DevelopmentClient
    
    client = DevelopmentClient()
    users = client.users(user_type='all')
    
    
    with open('trash.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Owner email", "file name", "trashed date"])
        
    
        for user in users:
            
            user_to_impersonate = client.user(user_id=user.id)
            user_client = client.as_user(user_to_impersonate)
            trashed_items = user_client.trash().get_items(fields=('trashed_at', 'name'))
            if trashed_items is not None:
                for trashed_item in trashed_items:
                    writer.writerow([user.login, trashed_item.name, trashed_item.trashed_at])

Log:
GET https://api.box.com/2.0/folders/trash/items {'headers': {'As-User': '286262453',
             'Authorization': '---Cxpm',
             'User-Agent': 'box-python-sdk-2.9.0',
             'X-Box-UA': 'agent=box-python-sdk/2.9.0; env=python/3.6.10'},
 'params': {'fields': 'trashed_at,name', 'limit': 100, 'offset': 9700}}
"GET https://api.box.com/2.0/folders/trash/items?limit=100&fields=trashed_at%2Cname&offset=9700" 200 134
{'Date': 'Sat, 12 Sep 2020 01:15:37 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'BOX-REQUEST-ID': '0c6ae3ad5096a3860859466155738eb30'}
{'entries': [],
 'limit': 100,
 'offset': 9700,
 'order': [{'by': 'type', 'direction': 'ASC'},
           {'by': 'name', 'direction': 'ASC'}],
 'total_count': 10162}

GET https://api.box.com/2.0/folders/trash/items {'headers': {'As-User': '286262453',
             'Authorization': '---Cxpm',
             'User-Agent': 'box-python-sdk-2.9.0',
             'X-Box-UA': 'agent=box-python-sdk/2.9.0; env=python/3.6.10'},
 'params': {'fields': 'trashed_at,name', 'limit': 100, 'offset': 9800}}
"GET https://api.box.com/2.0/folders/trash/items?limit=100&fields=trashed_at%2Cname&offset=9800" 200 134
{'Date': 'Sat, 12 Sep 2020 01:16:06 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'gzip', 'BOX-REQUEST-ID': '1b8e69d88cecd2bc78622506801531996'}
{'entries': [],
 'limit': 100,
 'offset': 9800,
 'order': [{'by': 'type', 'direction': 'ASC'},
           {'by': 'name', 'direction': 'ASC'}],
 'total_count': 10162}

GET https://api.box.com/2.0/folders/trash/items {'headers': {'As-User': '286262453',
             'Authorization': '---Cxpm',
             'User-Agent': 'box-python-sdk-2.9.0',
             'X-Box-UA': 'agent=box-python-sdk/2.9.0; env=python/3.6.10'},
 'params': {'fields': 'trashed_at,name', 'limit': 100, 'offset': 9900}}

### Versions Used
Python SDK: 
Python: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@StefanMarchand It could be that one user has a very large trash collection. The list trash items method in the python SDK hits the following API [endpoint](https://developer.box.com/reference/get-folders-trash-items/). This API endpoint returns a certain number of items. The method will get the remaining items by changing the offset and making a request if the total number of items exceeds the number returned. This paging is described [here](https://developer.box.com/guides/api-calls/pagination/offset-based/).
