### ISSUE TITLE
How to get access_token expires_at with Python

### ISSUE THREAD

**Issue by mindej** [box/box-python-sdk#545]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

How to get access_token expires_at with Python? Now I am refreshing token every time I return it to the user. Witch is increasing the load on Box API backend.

**Comment by sujaygarlanka** [comment]
@mindej You should not have to worry about refreshing the token. The SDK will take care of that for you if you use JWT or OAuth. More can be found [here](https://developer.box.com/guides/authentication/) and [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#ways-to-authenticate). If this doesn't fix your issue, feel free to re-open this.

**Comment by mindej** [comment]
@sujaygarlanka I am using python box SDK together UI-Elements (content picker https://developer.box.com/guides/embed/ui-elements/picker/)
I am storing authenticated users tokens in DB and returning access token to the front end. 
The problem will be when the user has connected to our BOX application some weeks ago, then I assumed that the acsess_token will be invalid.
To prevent this I am refreshing the token and then sending it to the front end to consume it in a UI-Elements

**Comment by sujaygarlanka** [comment]
@mindej An access token is valid for at minimum 60 minutes and maximum a few minutes passed an hour. So if its been more than an hour, then I would refresh the token.
