### ISSUE TITLE
How do I issue a refresh token and use it in Python3 ?

### ISSUE THREAD

**Issue by alkhalifas** [box/box-python-sdk#563]
Hello,

I currently use the enterprise Box API to processes a few items using a developer access token which is only available for 60 minutes. I need to run a process that will take much longer than 60 minutes, and I was told the only way to do this is by using a refresh token.

How do I get a refresh token, and how can I implement it to extend my session in Python?

Thanks

**Comment by sujaygarlanka** [comment]
@alkhalifas Our SDK handles refreshing the token if you use JWT or OAuth. The docs to use it are [here](https://classroom.github.com/a/3ROlwNei). An explanation of JWT and setting it up can be found [here](https://developer.box.com/guides/authentication/jwt/). Feel free to re-open this if you have any follow-up questions. Hope this helps!

**Comment by RevathiB12** [comment]
Is it feasible to refresh token with OAuth?
