### ISSUE TITLE
Abount Traditional 3-Legged OAuth2

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#570]
I've made some applications refer to the demo sample code on the localhost.
But when I run a application on the other PC as a web server, and access it on the other client PC through the intranet, because your sample code used webbrowser.open(auth_url) like below, so I can't get an OAuth2's authentication at the client.
Is there any way I can run my application on the server PC in the intranet, and I can access it from the other PC with an OAuth2's authentication. I like to use bottle as my web server just like your sample code.
      
   oauth = oauth_class(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
    )
    auth_url, csrf_token = oauth.get_authorization_url('http://localhost:8080')
    webbrowser.open(auth_url)

**Comment by sujaygarlanka** [comment]
@c-rei Not sure what you are asking here. Could you please elaborate or if this is no longer a concern, could you close this question. Thanks!
