### ISSUE TITLE
About the expiration of OAuth2

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#571]
Dear Sir:
I have a question about the expiration of OAuth2.
I make a authorization with Traditional 3-Legged OAuth2 just like your  example, I run a long processing over one hour after authorized, so I want to known do I must refresh my access token in every hour when I continue to run a long processing?
And how can I to check the expiration of my access token?

Thanks your any response.

**Comment by sujaygarlanka** [comment]
@c-rei If you are simply trying to create a script making API calls, I recommend using JWT authentication. The SDK will automatically refresh the token. Information on how to setup your app to use JWT can be found [here](https://developer.box.com/guides/authentication/jwt/). Once that is done, you have the Python SDK use JWT by following the instructions [here](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#server-auth-with-jwt).

**Comment by c-rei** [comment]
Sir,

thanks for your response.

I have to use OAuth2 authorization for our customs in my applications, I just worry  when they run a long processing, an access token will be expire on the way. So I want to known what can I to do to avoid it?
