### ISSUE TITLE
App Token Authorization Failed with Error: Missing client_id and clinet_secret

### ISSUE THREAD

**Issue by wanting0wang** [box/box-python-sdk#575]
I created an app and wanted to use app token authorization. I have the token generated.

Following the guide (https://developer.box.com/guides/authentication/app-token/with-sdk/#initializing-an-sdk-client), I tried to authenticate:
<img width="837" alt="Screen Shot 2021-02-06 at 16 05 08" src="https://user-images.githubusercontent.com/25274600/107129684-1c59e000-6895-11eb-9405-d7f7bb6047dd.png">

What is the right way to authenticate the client using app token?

Thank you!

**Comment by sujaygarlanka** [comment]
Hello @wanting0wang,

Pass in none for the client id and and client secret like below 
```
auth = OAuth2(
    client_id=None,
    client_secret=None,
    access_token='fndskafjkelgejrlwrew'
)
client = Client(auth)
```
