### ISSUE TITLE
How can I use return data of metadata query

### ISSUE THREAD

**Issue by YoOtagaki** [box/box-python-sdk#576]
client.search().query(None, limit=100, offset=0, metadata_filters=metadata_search_filters)

Should this be as below?

items = client.search().query(None, limit=100, offset=0, metadata_filters=metadata_search_filters)
 
And   the code below makes error  "'Search' object has no attribute 'metadata_query': AttributeError".

items = client.search().metadata_query(......)

**Comment by PJSimon** [comment]
Thanks for submitting this Issue.  Unfortunately, it is missing the required checkbox fields that are normally provided in the template when you initially create an Issue:

- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

Please perform each step above to research your Issue before submitting it to our team.  If you are still unable to resolve it, please re-create this Issue and check off those boxes when you submit it!  Thanks for helping to streamline our process!

[sdk-docs]: ../tree/master/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues
