### ISSUE TITLE
How can I refer return data of metadata query

### ISSUE THREAD

**Issue by YoOtagaki** [box/box-python-sdk#577]
- [Check] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [Check] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [Check] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [Check] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I cannot use metadata_query with the message.

'Search' object has no attribute 'metadata_query': AttributeError
Traceback (most recent call last):
  File "/var/task/DevCode/lambda_function.py", line 26, in lambda_handler
    items = client.search().metadata_query(
AttributeError: 'Search' object has no attribute 'metadata_query'

### Steps to Reproduce

This is my code.

def lambda_handler(event, context):
    # TODO implement
    
    import json
   
    from boxsdk.config import Proxy
    
    Proxy.URL = 'http://proxy-lb.namc.local:8088'
    
    from boxsdk import JWTAuth
    from boxsdk import Client
    from boxsdk.object.collaboration import CollaborationRole
    
    config = JWTAuth.from_settings_file('config.json')
    
    client = Client(config)
        
    user_to_impersonate = client.user(user_id='14230190874')
    user_client = client.as_user(user_to_impersonate)
    
    from_template = 'enterprise_xxxxxxxx.documentation_list'

    fields = ['type', 'id', 'name', 'enterprise_xxxxxxxx.documentation_list.basis']
    limit = 100
    items = client.search().metadata_query(
        from_template,
        limit,
        fields
    )
    for item in items:
        print('The item ID is {0} and the item name is {1}'.format(item.id, item.name))

### Expected Behavior
I want to use Metadata Search or Metadata Query.
But I cannot find any example how to refer return data of Metadata Search. 
And Metadata Query makes error.

### Error Message, Including Stack Trace

Response
{
    "errorType": "AttributeError",
    "errorMessage": "'Search' object has no attribute 'metadata_query'",
    "stackTrace": [
        "  File \"/var/task/DevCode/lambda_function.py\", line 26, in lambda_handler\n    items = client.search().metadata_query(\n"
    ]
}

Function Logs
'Search' object has no attribute 'metadata_query': AttributeError
Traceback (most recent call last):
  File "/var/task/DevCode/lambda_function.py", line 26, in lambda_handler
    items = client.search().metadata_query(
AttributeError: 'Search' object has no attribute 'metadata_query'

### Versions Used
Python SDK: <2.11.0>
Python: <3.6.12>

**Comment by sujaygarlanka** [comment]
Hello @YoOtagaki, This is because we have merged it into our master branch, but have not done release of this code yet. We will be doing a release of this within the next week or so. We apologize for any inconvenience.

**Comment by YoOtagaki** [comment]
Hi @sujaygarlanka  Thanks, I'm waiting for the release.

**Comment by YoOtagaki** [comment]
@sujaygarlanka  When will you release the version which include metadata_query?
