### ISSUE TITLE
struggling to authenticate App user with JWTAuth 

### ISSUE THREAD

**Issue by inap-bannai** [box/box-python-sdk#579]
- [✔︎] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.

### Description of the Issue

Hi I'm currently using Box sdk and I'm trying to authenticate App user and make calls with it. I've followed [this instruction](https://github.com/box/box-python-sdk/blob/master/docs/usage/authentication.md#server-auth-with-jwt) but this couldn't help.
 

### Steps to Reproduce
・I tried like below, however I got an error `TypeError: __init__() missing 1 required positional argument: 'enterprise_id'`, so although I thought it is not necessary, I added `enterprise_id = None` as arg, then
・next I got an error like the screenshot I added, which is saying `Cannot obstain user token based on enterprise configuration for your app` 

Could you help me out how to get around these issues? 

```python
app_user = service_account_client.user(user_id='APP_USER_ID')

app_user_auth = JWTAuth(
    client_id='YOUR_CLIENT_ID',
    client_secret='YOUR_CLIENT_SECRET',
    user=app_user,
    jwt_key_id='YOUR_JWT_KEY_ID',
    rsa_private_key_file_sys_path='CERT.PEM',
    rsa_private_key_passphrase='PASSPHRASE',
    store_tokens=your_store_tokens_callback_method,
)
app_user_auth.authenticate_user()
app_user_client = Client(app_user_auth)
```

### Screenshots
![Screen Shot 2021-03-05 at 0 54 10](https://user-images.githubusercontent.com/60955529/109991177-6d9ea780-7d4d-11eb-9f49-447d79fe2d21.png)

### Versions Used
Python SDK: 3.6.8
Python: ==2.11.0

**Comment by swfree** [comment]
Hi @inap-bannai, to authenticate with an app user, there is a setting you'll need to enable in your app's configuration. You can follow the directions here to [enable the "Generate user access tokens" setting](https://developer.box.com/guides/authentication/jwt/user-access-tokens/#preconditions). After you've enabled it, you'll also need to [re-authorize your application](https://developer.box.com/guides/applications/custom-apps/app-approval/#re-authorization-on-changes).

And thank you for finding out that `enterprise_id=None` was missing from our example in the docs, we'll add that in.

**Comment by inap-bannai** [comment]
Hello @swfree, thank you for taking the time to help me out and that works! I didn't re-authenticate my app.

**Comment by swfree** [comment]
Great, glad to hear it worked!
