### ISSUE TITLE
AttributeError: 'Search' object has no attribute 'metadata_query'

### ISSUE THREAD

**Issue by Giorgosi** [box/box-python-sdk#591]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When trying to run the metadata_query I obtain the following error:
******************
   items = client.search().metadata_query(
AttributeError: 'Search' object has no attribute 'metadata_query'
******************
I followed the steps in the link below just replacing with my enterprise values and and existing templatekey
https://github.com/box/box-python-sdk/blob/main/docs/usage/search.md#metadata-query

### Versions Used
boxsdk version 2.11.0
python version 3.9.4

**Comment by swfree** [comment]
Hi @Giorgosi,

The metadata query functionality was added recently and has not been released yet ([see release docs](https://github.com/box/box-python-sdk/blob/main/HISTORY.rst#next-release)). Our next release is coming soon!

Thanks,
@swfree
