### ISSUE TITLE
Pass a custom state instead of csrf_token during the Oauth2 process.

### ISSUE THREAD

**Issue by LesPrimus** [box/box-python-sdk#594]
Hi

First off thanks for this library very helpful.

My question is:
Is it possible to pass a custom **state** string, instead of the auto-generated one (csrf_token), during the Oauth2 process?

Like this:
```
oauth = OAuth2(
    client_id='YOUR_CLIENT_ID', 
    client_secret='YOUR_CLIENT_SECRET',
    store_tokens=your_store_tokens_callback_method
)
```

```
auth_url, csrf_token = oauth.get_authorization_url('http://YOUR_REDIRECT_URL', state=<custom_state>)
```

The doc [here](https://developer.box.com/reference/get-authorize/#param-state) says otherwise.

**Comment by Jeff-Meadows** [comment]
You can subclass the `OAuth2` class and override its `_get_csrf_token` method to return whatever you want.
