### ISSUE TITLE
Metadata query functionality

### ISSUE THREAD

**Issue by Giorgosi** [box/box-python-sdk#595]
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I'm testing the new metadata query functionality just included in the new release 2.12.0. Query retrieves correctly all files for a specific metadata template based on the quey params. Now I am trying to pull the metadata values linked to the files but the query fails.

This is the query I am using:
######Query###########
from_template = 'enterprise_xxxxxx.templatekey'
ancestor_folder_id = '0'
query = 'fieldkey = :val'
query_params = {'val': 'fieldvalue'}
fields = ['id', 'name', 'metadata.enterprise_xxxxxx.templatekey.fieldkey']

items = client.search().metadata_query(from_template, ancestor_folder_id, query=query, query_params=query_params, use_index=None, order_by=None, marker=None, limit=limit, fields=fields)

for item in items:
    print('metadata value= ',item.metadata.enterprise_xxxxxx.templatekey.fieldkey)

#################
ERROR:
I am receiving the following result referencing to the last row (the print):
AttributeError: 'dict' object has no attribute 'enterprise_xxxxxx'
#################

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by swfree** [comment]
Hi @Giorgosi,

Thanks for submitting this issue. You can find some examples of how to access the [values in the response in this unit test](https://github.com/box/box-python-sdk/blob/main/test/unit/object/test_search.py#L380). Can you try out accessing the values in the same way as in the unit test?

Thanks,
@swfree

**Comment by Giorgosi** [comment]
Thanks, this worked after calling the metadata value field using the following syntax picked from the unit test:
item2['metadata']['enterprise_67890']['catalogImages']['$parent']

**Comment by swfree** [comment]
Great, glad to hear that worked!
