### ISSUE TITLE
IndexError raised from get_thumbnail_representation

### ISSUE THREAD

**Issue by DaveSawyer** [box/box-python-sdk#596]
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
If a file is old and has no representations or if you ask for dimensions that are not available, the SDK crashes with an index error. It assumes there will always be at least one representation returned.

### Steps to Reproduce
Included unit test in patch that shows the error if you pass unexpected dimensions

### Expected Behavior
0 bytes returned

### Error Message, Including Stack Trace
>       url = representation[0]['content']['url_template']
E       IndexError: list index out of range

### Versions Used
Python SDK: 2.12
Python: 3.7

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by PJSimon** [comment]
Hi @DaveSawyer ,

Thanks for submitting this Issue! We will address it in our next sprint (SDK-1677)!

@PJSimon

**Comment by DaveSawyer** [comment]
Great! I look forward to switching from the thumbnail API to the representations API in the next release of Box Drive
