### ISSUE TITLE
Client.create_webhook fails to create a webhook

### ISSUE THREAD

**Issue by kiyoto** [box/box-python-sdk#607]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Steps to Reproduce

1. Environment: Python 3.6.5 on MacOS BigSur 11.4, boxsdk v.2.12.1
2. Authenticate via OAuth2 and call the following method: `Client.create_webhook(f, ['FILE.UPLOADED'], url)` where f is a folder object and url is a URL of choice (can be anything).
3. The SDK returns the following error

```
----> 1 wh = client.create_webhook(f, ['FILE.UPLOADED'], url)

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/util/api_call_decorator.py in call(instance, *args, **kwargs)
     69 
     70             method = self._func_that_makes_an_api_call.__get__(instance, owner)
---> 71             return method(*args, **kwargs)
     72 
     73         # Since the caller passed a non-`None` instance to `__get__()`, they

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/client/client.py in create_webhook(self, target, triggers, address)
    680             'address': address,
    681         }
--> 682         box_response = self._session.post(url, data=json.dumps(webhook_attributes))
    683         response = box_response.json()
    684         return self.translator.translate(

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/session/session.py in post(self, url, **kwargs)
    110             `unicode`
    111         """
--> 112         return self.request('POST', url, **kwargs)
    113 
    114     def put(self, url, **kwargs):

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/session/session.py in request(self, method, url, **kwargs)
    156             `unicode`
    157         """
--> 158         response = self._prepare_and_send_request(method, url, **kwargs)
    159         return self.box_response_constructor(response)
    160 

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/session/session.py in _prepare_and_send_request(self, method, url, headers, auto_session_renewal, expect_json_response, **kwargs)
    404             network_response = retry(request, **kwargs)
    405 
--> 406         self._raise_on_unsuccessful_request(network_response, request)
    407 
    408         return network_response

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boxsdk/session/session.py in _raise_on_unsuccessful_request(network_response, request)
    327                 method=request.method,
    328                 context_info=response_json.get('context_info', None),
--> 329                 network_response=network_response
    330             )
    331         if request.expect_json_response and not is_json_response(network_response):

BoxAPIException: Message: Bad Request
Status: 400
Code: bad_request
Request ID: cfwc58gs4vpisleh
Headers: {'Date': 'Sun, 04 Jul 2021 06:01:19 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-cache, no-store', 'BOX-REQUEST-ID': '0db012a93e55aa435aac348800729cbae'}
URL: https://api.box.com/2.0/webhooks
Method: POST
Context Info: {'errors': [{'reason': 'invalid_parameter', 'name': 'targetId', 'message': "Invalid data type: '123053531579'"}]}
```

### Expected Behavior
I expected the above code to work because 1. the same API call directly called from cURL worked 2. I followed the code sample for Python on the docs page.

### Error Message, Including Stack Trace

Inlined above.

### Screenshots
N/A

### Versions Used
Python SDK: 2.12.1
Python: 3.6.5

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hi @kiyoto 

Thanks for reporting the issue. I couldn't reproduce it with the steps provided, but we'll look into this deeper and get back to you ASAP. In the meantime could you provide us a full code sample (with the client and folder initialization etc.)?

Thanks,
@mwwoda

**Comment by mwwoda** [comment]
Hi @kiyoto 

It is still an issue?

**Comment by mwwoda** [comment]
I'm closing this one due to inactivity. Feel free to reopen if it is still an issue!
