### ISSUE TITLE
 '_RSAPrivateKey' object has no attribute 'sign'

### ISSUE THREAD

**Issue by peternye** [box/box-python-sdk#611]
- [x ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When trying to access the folder structure from a Linux server, it sometimes succeeds, and sometimes I get:
File "/dist/shows/shared/lib/python2.7/site-packages/jwt/api_jws.py" in encode
114. signature = alg_obj.sign(signing_input, key)

File "/dist/shows/shared/lib/python2.7/site-packages/jwt/algorithms.py" in sign
313. return key.sign(msg, padding.PKCS1v15(), self.hash_alg())

Exception Type: AttributeError at /attachments/add/red/international/internationalizr/712768/
Exception Value: '_RSAPrivateKey' object has no attribute 'sign'

This seems to happen more often when the browser request to the server is coming from a Mac Big Sur.   This doesn't make sense, since it is still the Linux server issuing the Box call.

### Steps to Reproduce
rootFolder = self.client.folder(folder_id='0')
where self.client is the box client

### Versions Used
Python SDK: 2.12.1
Python: 2.7.5

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hi @peternye 

Which version of `cryptography` are you using? Can you run `pip list` and post the packages versions? You could try to upgrade `cryptography` as the problem could be related to that.

Thanks,
@mwwoda

**Comment by mwwoda** [comment]
Hi @peternye 

Is it still an issue?

Thanks,
@mwwoda

**Comment by peternye** [comment]
Yes, still not working.

**Comment by mwwoda** [comment]
@peternye can you do the steps mentioned above?

> Which version of cryptography are you using? Can you run pip list and post the packages versions? You could try to upgrade cryptography as the problem could be related to that.

**Comment by peternye** [comment]
Here are the versions we're using:

cryptography                     1.7.2         
jwcrypto                         0.4.2         
pycrypto                         2.6.1

**Comment by mwwoda** [comment]
This issue could be related to the old cryptography version. Could you try to upgrade it to 3.x.x version? You can use the latests for python 2.7 to which is 3.3.2.

**Comment by peternye** [comment]
I'm having problems getting this installed; waiting for help from Systems.

**Comment by peternye** [comment]
I upgraded to cryptography 3.3.2 and boxsdk 2.12.1.   I'm now getting:

**Comment by mwwoda** [comment]
This is probably the same issue as here https://github.com/box/box-python-sdk/issues/387. Refer to https://github.com/box/box-python-sdk#server-to-server-auth-with-jwt if you want to use JWT.

**Comment by peternye** [comment]
Worked!  pip install "boxsdk[jwt]" did it.
