### ISSUE TITLE
Get items by full path

### ISSUE THREAD

**Issue by steverecio** [box/box-python-sdk#612]
It would be great if this library included a utility to get a file/folder by its full path

Ie. `client.get_item('/path/to/some/resource')`

The search function can somewhat work here but it seems to return non-exact matches which makes it difficult to use as a replacement.

For folder paths, having a get_or_create would be incredibly useful as well.

**Comment by mhagmajer** [comment]
Hi @steverecio! Thanks for submitting a feature request. I've added it to our team backlog. We'll update the ticket as we work on it.

**Comment by steverecio** [comment]
Thank you. Here is some sample code I wrote to the address the issue in case its useful to anyone:

```
    def get_folder(self, path, create=False):
        client = self.get_client()
        parts = path.lstrip('/').split(os.sep)
        folder = client.folder(folder_id='0')
        for part in parts:
            results = [f for f in folder.get_items() if f.name == part]
            if results:
                folder = client.folder(folder_id=results[0].id)
            else:
                if not create:
                    return None  # not found
                folder = folder.create_subfolder(part)

        return folder
```

**Comment by mgrytsai** [comment]
Thanks for submitting the proposal, however, it should be addressed by underlying API and not SDK.

There is an existing request to product team. Please upvote and comment on this [Product Request](https://pulse.box.com/forums/909778/suggestions/36108841)
