### ISSUE TITLE
Search API - returns nothing - permissions issue?

### ISSUE THREAD

**Issue by gwaters-caltech** [box/box-python-sdk#613]
After much experimentation, I have determined that I cant run a search from an custom app using JWT.

I have granted the app all the check boxes, and app has been authorized by an admin, and yet I still cant get search to work correctly.

Other functions work correctly like client.user().get() 
Or changing users to inactive, changing quotas, deactivating, deleting users, all work fine.

What doesnt work:

items =client.search().query(query='file_i_know_exists', type="file", limit=100, file_extensions='pdf', owner_user_ids=["11111"], scope="user_content", fields='name' )
simpler searches dont work as well:
items =client.search().query(query='file_i_know_exists')

 If I use OAUTH and my own developer token from the dev console (60 minute lifespan), the same lines of code work correctly if I search inside my account. I havent tried searching other accounts, but I doubt it works. That runs as me, and not as the app itself, so that is not a viable solution. ( I ran user.get and it shows my ID) 

So my question is, how do I allow my app the ability to run these searches? Do I need to generate a token as the user I am searching ?

Thanks so much,
Gary
PS: Mods, please mark this as a question, I know how to submit issues, but I am not sure how I get that pink question icon.

**Comment by Jeff-Meadows** [comment]
JWT and app users are a little tricky when dealing with content. Service accounts[1] and app users[2] (the two types of "user" JWT can authorize) have their own folder tree, which is separate from content within the enterprise. These accounts start out with an empty tree, but they can create their own content, or be collaborated onto existing content.

After that (plus some potential search indexing delay), the search endpoint should start returning the data you expect.


[1] https://developer.box.com/guides/getting-started/user-types/service-account/#folder-tree-and-collaboration
[2] https://developer.box.com/guides/getting-started/user-types/app-users/#folder-tree-and-collaboration

**Comment by gwaters-caltech** [comment]
Ah this why I cant search from the service account:
>> The Service Account can not access any other user's information or content
That explains it.
Thanks Jeff.
