### ISSUE TITLE
Access Statistics on Files for share links

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#634]
I known I can get a preview count and download count with below codes.
I downloaded this file with share link just one time, but I got 3 counts for download_count.
So I think a download count includes a preview count, is't right?

Thanks any help.
 
>>> file_id = '123456'
>>> shared_link = client.file(file_id).get().shared_link
>>> shared_link['preview_count'] 
2
>>> shared_link['download_count']
3
>>>

Versions Used
Python SDK: 2.12.1
Python: 3.8.10

**Comment by mwwoda** [comment]
Hi @c-rei 

Thanks for reaching out to us! The download_count shouldn't include the preview_count. It should only increment when file is downloaded. From my tests, it behaves this way. Are you sure you only downloaded this file once? Did you download the file from the browser or from the SDK?

Thanks,
Mateusz

**Comment by c-rei** [comment]
Hi @Mateusz

Thanks for your response.
For confirmation, I've got the access statistics with Box Report, that looks attached image.
So there are one download and two previews from anonymous use with shared link. That's all.
 
I should explain some Japanese like below:
日付＝date, ユーザー名＝User Name, ユーザーメール=User mail, 操作＝Action, 対象＝Target, 詳細＝Details
匿名＝Anonymous, 以前のコラボレータ＝Previous collaborator, プレビュー＝Preview, ダウンロード＝Download

![log](https://user-images.githubusercontent.com/26074496/143329577-a6ec5e08-eaaf-44f2-a5f2-dbfe014da594.png)

Thanks,
c-rei

**Comment by c-rei** [comment]
And I found that if I use a word file for shared link, I can get correct preview and download count each,
but if I use a pdf file or a Excel file, I got a download count that includes a preview count.

Thanks,
c-rei

**Comment by mwwoda** [comment]
Yes, I can indeed see this happening with a .pdf and .xlsx files. For some unknown reason the download count is incremented when the link is accessed. It seems to be a problem with the API itself. From the SDK side, we only return the API response in this case. I will contact the team responsible for SharedLinks internally to see if they are aware of this issue. If you further help with this issue you can try contacting support via https://support.box.com/hc/en-us/requests/new. 

Thanks,
Mateusz
