### ISSUE TITLE
How to get a event log with new features

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#647]
I've found some new features about event log like below on the usage docs,

events = client.events()
    .get_admin_events(created_after='2019-07-01T22:02:24-07:00')

But when I use it to get events, it just retrieved the first 100 events.
So I want to known how to get all events for historical querying. 

### Versions Used
Python SDK: 2.14.0
Python: 3.8.10

**Comment by arjankowski** [comment]
Hi @c-rei 

Thanks for submitting this issue.

It's look like we have a bug in our API for `get_admin_events` method.

To get more events from `get_admin_events` we should be able to call it again with `stream_position` parameter as it is in `get_events` method. As a `stream_position` argument we should put returned value from last call from `next_stream_position` field.

But actually our current implementation of `get_admin_events` method doesn't support `stream_position` argument what is a bug.
We will fix this ASAP and let you know.

Sorry for inconvenience!

**Comment by c-rei** [comment]
Dear arjankowski

Thanks your responses. I'll try the new get_admin_events.
And Let you known the results.

Regards

**Comment by c-rei** [comment]
Hi,

I've tried the fix(Events)! ... get_admin_events, it looks good.
I think then I can get the events continually with stream_position and next_stream_position.
Thanks a lot.

Regards,
