### ISSUE TITLE
Do not freeze `cryptography` version

### ISSUE THREAD

**Issue by alexlitvinenko** [box/box-python-sdk#667]
I've tried to update my dependencies and faced:

> There are incompatible versions in the resolved dependencies:
>   cryptography (from azure-storage==0.36.0->-r requirements.in (line 48))
>   cryptography<3.5.0,>=3 (**from boxsdk[jwt]**==3.0.1->-r requirements.in (line 45))
>   cryptography>=35.0 (from pyOpenSSL==22.0.0->Scrapy==2.0.1->-r requirements.in (line 68))
>   cryptography>=2.0 (from Scrapy==2.0.1->-r requirements.in (line 68))
>   cryptography (from service-identity==21.1.0->Scrapy==2.0.1->-r requirements.in (line 68))
>   cryptography>=2.3 (from jwcrypto==1.0->django-oauth-toolkit==1.5.0->-r requirements.in (line 25))

Currently `boxsdk[jwt]` prevents me from keeping my dependencies up-to-date.

The issue has been introduced in https://github.com/box/box-python-sdk/blob/c5b43e53f671aa1fc665daa42d13ad0ea14f6083/setup.py#L61

According to [Author](https://github.com/box/box-python-sdk/pull/636) of the change:
> This limit is set, because >=3.5.0 versions require Rust

So, what is the plan? Wait until `cryptography` removes `rust` from dependencies?
https://cryptography.io/en/latest/faq/#why-does-cryptography-require-rust

**Comment by lukaszsocha2** [comment]
Hi,
the reason for freezing cryptography library was failing build for pypy on Travis (wasn't able to install rust). We are moving build to Github Actions to avoid this problem. Cryptography library will be back to the most recent version in the next release.
Regards
