### ISSUE TITLE
oauth is not giving a assertion error 

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#67]
the code runs fine till this part but i am not sure what is the  THE_CSRF_TOKEN that i need to put in i am sure there is an obvious thing that i am missing but i cant seem to figure it out

assert 'THE_CSRF_TOKEN_YOU_GOT' == csrf_token
access_token, refresh_token = oauth.authenticate('YOUR_AUTH_CODE')

i get all the other functionalities of the sdk to work but without this one i cant automate

**Comment by jmoldow** [comment]
When you go through the /authorize workflow, it is best practice for your application to insert a randomly generated token as the ``state`` parameter. https://box-content.readme.io/reference#authorize

Then, after the redirect occurs, before calling ``authenticate()`` with the received auth code, you should assert that the ``state`` param you received in the payload of the redirect request matches the expected ``state`` value that you had passed. This is a way to assure you that the response was not forged.

Check out https://github.com/box/box-python-sdk/blob/634b6d6a85de85f3f4076d6cf8d5883053c971da/demo/auth.py#L57 for an example of this.

See also http://tools.ietf.org/html/rfc6749#section-10.12 for more information.

If you are handling the redirect in the same Python session that made the authorize call, then you can just check the value of ``csrf_token`` that you had generated earlier in the session, as is done in our demo that I linked to.

If you're making a server-based application, then you'll need some way to store the csrf token you generated, and look it up when you receive a redirect.
