### ISSUE TITLE
Chunked upload does'nt work with SDK version 3.0.0...

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk#671]
When I used below code to chunked upload a big file, it is working with SDK version 2.14.0, but when I update
SDK version to 3.0.0, it does'nt work.

### my code
chunked_uploader = some_folder.get_chunked_uploader(file_path)
uploaded_file = chunked_uploader.start()

### error detail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\virtual\box\lib\site-packages\boxsdk\util\chunked_uploader.py", line 43, in start
    self._upload()
  File "C:\virtual\box\lib\site-packages\boxsdk\util\chunked_uploader.py", line 90, in _upload
    next_part = self._inflight_part or self._get_next_part()
  File "C:\virtual\box\lib\site-packages\boxsdk\util\chunked_uploader.py", line 112, in _get_next_part
    bytes_read = self._content_stream.read(self._upload_session.part_size - copied_length)
ValueError: read of closed file

### Versions Used
Python SDK: 3.0.0
Python: 3.8.8

**Comment by oomorinobu** [comment]
I faced with the same program.
I used the following workaround to get around the problem.

#### work around
```
chunked_uploader = some_folder.get_chunked_uploader(file_path)
chunked_uploader._content_stream = open(file_path, "rb")
uploaded_file = chunked_uploader.start()
```

**Comment by oomorinobu** [comment]
I think the root cause is that the start method is not included in the with statement, and the file is closed when it is used.

**Comment by c-rei** [comment]
Hi, oomorinobu

Thanks your comments and your sample code.
I will try it with your sample code.

But I think the new version SDK has a bug about chunked upload.

**Comment by oomorinobu** [comment]
I agree with your opinion.
I thought it was caused by the following commit changes

https://github.com/box/box-python-sdk/commit/2208047b0d4c14656ad408a079b2b298220675a2

boxsdk/object/folder.py
boxsdk/object/file.py
