### ISSUE TITLE
download_to module 

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#68]
hey 
I have been trying to download a folder full of files on to my system I tried to use the down_to function in the file module

i have to questions 
1) writeable_stream= the destination of the file right ? and where do i specify the file i want to download
2) is there a way to download the folder or no

def download_to(self, writeable_stream):
        """
        Download the file; write it to the given stream.
        :param writeable_stream:
            A file-like object where bytes can be written into.
        :type writeable_stream:
            `file`
        """
        url = self.get_url('content')
        box_response = self._session.get(url, expect_json_response=False, stream=True)
        for chunk in box_response.network_response.response_as_stream.stream(decode_content=True):
            writeable_stream.write(chunk)

**Comment by Jeff-Meadows** [comment]
Hi.

`writeable_stream` is any open file-like stream. If you want to download a file to disk, the code would look something like this:

    with open('path_to_file.jpg', 'wb') as open_file:
        client.file('FILE_ID').download_to(open_file)

Unfortunately, downloading an entire folder at once is not currently supported by the Box API, so we couldn't put it in the SDK. If and when that feature does become available, we'll definitely add it to the SDK.

**Comment by danyal123** [comment]
thank you very much for the timely response

**Comment by danyal123** [comment]
i am trying to download the contents of folder which are all files to the my hard drive and this is the code i have been using i have tried different variations of it but all of them print only the last item in the list to all the files i want the name of the file in box to be matched in my machine. 

for i in seed:
    new_download=open(i,'w')
    print (i)
    new_download.close()
    open_file=open(i,'wb')
    for k in seed_id:
        client.file(k).download_to(open_file)
        print (k)
    open_file.close()

**Comment by jmoldow** [comment]
@danyal123 : answered in #78.
