### ISSUE TITLE
Drop 'coding = utf-8' comments

### ISSUE THREAD

**Issue by adamchainz** [box/box-python-sdk#694]
You can tidy up your code a bit by dropping these comments as they're only needed on Python 2. Python 3 reads files as utf-8 by default. [pyupgrade](https://github.com/asottile/pyupgrade/#-coding--comment) can drop these comments for you, and update syntax in other ways too.

**Comment by arjankowski** [comment]
Thank @adamchainz for this issue!

We added this to our  internal jira with number SDK-2003 and will plan to address this soon.
