### ISSUE TITLE
Overwrite Box files that require "chunked_upload"

### ISSUE THREAD

**Issue by lhoggatt17** [box/box-python-sdk#709]
### Is your feature request related to a problem? Please describe.

The python SDK is great, however there is a missing feature that other SDKs appear to have. When uploading a 'small' file, you can upload a new file, or update/overwrite the version on an existing file. This is awesome! 

However, for large (chunked uploads) there is currently no way to 'overwrite' an existing Box file / update the version. It would be great to have this functionality, similar to what is already in the Java SDK (see [here](https://developer.box.com/guides/uploads/chunked/with-sdks/)). 

### Describe the solution you'd like

I'd like if there was an option to overwrite an existing large file that requires a chunked_upload.

### Describe alternatives you've considered

This feature is missing in the Python SDK.

**Comment by antusus** [comment]
Hi @lhoggatt17 ,

Thanks for submitting this Issue! I've created internal ticket to add this to Python SDK. We will let you know when this is done.

@antusus

**Comment by lhoggatt17** [comment]
I was reading an area of the documentation, and it appears this functionality might already exist:

> The SDK provides a method of automatically handling a chunked upload; simply call [chunked_upload.start()](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.chunked_uploader.ChunkedUploader.start) with the path to the file you wish to upload from the [File](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.file.File) with [file.get_chunked_uploader(file_path, rename_file=False)](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.file.File.get_chunked_uploader) method to retrieve a [ChunkedUploader](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.chunked_uploader.ChunkedUploader) object for a new version upload or from the [Folder](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.folder.Folder) with [folder.get_chunked_uploader(file_path)](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.folder.Folder.get_chunked_uploader) method to retrieve a [ChunkedUploader](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.chunked_uploader.ChunkedUploader) object for a new file upload. You can also return a [ChunkedUploader](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.chunked_uploader.ChunkedUploader) object by creating a [UploadSession](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.upload_session.UploadSession) object first and calling the method, [upload_session.get_chunked_upload(file_path)](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.upload_session.UploadSession.get_chunked_uploader) or [upload_session.get_chunked_uploader_for_stream(content_stream, file_size)](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.upload_session.UploadSession.get_chunked_uploader_for_stream). Calling the method [chunked_upload.start()](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.chunked_uploader.ChunkedUploader.start) will kick off the chunked upload process and return the [File](https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#boxsdk.object.file.File) object that was uploaded.

From my understanding, if you say 'folder.get_chunked_uploader', you'll upload a new large file. If you say 'eixting_file.get_chunked_uploader', you'll upload a new version of the large file? 

If this behavior sounds correct, feel free to close the issue. Thanks!

**Comment by antusus** [comment]
Hi @lhoggatt17,
Thanks for reaching out. I've tried that and yes this works as expected:
```python
chunked_uploader = client.folder("0").get_chunked_uploader(path_to_large_file)
uploaded_file = chunked_uploader.start()
print(f'File "{uploaded_file.name}" uploaded to Box with file ID {uploaded_file.id}')
```
Will return the ID of the file created. Then if you want to update the file:
```python
chunked_uploader = client.file(big_file_id).get_chunked_uploader(path_to_large_file)
uploaded_file = chunked_uploader.start()
print(f'File "{uploaded_file.name}" uploaded to Box with file ID {uploaded_file.id}')
```
Prints the same ID and you will see that there is new version of a file.
I'll close the issue. If you would find any problems feel free to reopen the issue or create a new one.
