### ISSUE TITLE
upload_session commit not returning None when there is a 202

### ISSUE THREAD

**Issue by isaacHuh** [box/box-python-sdk#715]
Upload Session commit is not returning None when there is a 202
https://github.com/box/box-python-sdk/blob/44ca6db747ee246b811ed6a329f2ed63f543a32d/boxsdk/object/upload_session.py#L134
post is prob raising the exception with a 202 so this line doesn't get hit

Versions Used
Python SDK: 3.1.0
Python: 3.8.8

**Comment by lukaszsocha2** [comment]
Hi @isaacHuh,
Thanks for submitting this Issue! We will take a look and get back to you ASAP!
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @isaacHuh,
let me know if this pr solves your issue ?
@lukaszsocha2
