### ISSUE TITLE
NewConnectionError [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by DJanyavula** [box/box-python-sdk#739]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Some of my many upload to Box requests using python Box SDK are failing with error below:

### Error Message, Including Stack Trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x40cf0fbbd0>: Failed to establish a new connection: [Errno 110] Connection timed out
```

### Versions Used
Python SDK: 
Python: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hi @DJanyavula 
Thanks for reaching out to us!

Can you provide a little more information about the problem so we can investigate it further?

- What version of Python are you using? (Looking at stacktrack, I'm guessing it's 3.7)
- Which version of the SDK are you using?
- How can we reproduce this problem? Maybe you could also provide some sample code?
- Could you define what you mean by "many" requests? How many?
- How often does this happen (occasionally or always)?

Thanks

**Comment by arifty** [comment]
Hi @mwwoda , 

Is there any update on this ? Just fyi, we have upgraded the boxsdk version to **3.3.0** and now instead of timeout error, the api call gets hanging without finishing. It even kept running for 2 days and I had to cancel the execution.

**Comment by lukaszsocha2** [comment]
Hi @arifty,
today I also wasn't able to replicate this issue on my side, therefore I prepared a simple bash script with uploads all files from a local folder to box folder using curl command. If this script will block the same as using SDK, then we could exclude SDK code as the root of the problem and try to find it either in the network layer or the upload service.

```
path_to_folder_with_files="/Absolute/path/to/your/local/folder"
developer_token="..."
folder_id="box folder id"

for path in "$path_to_folder_with_files"/*
do
  filename="$(basename -- $path)"
  curl -i -X POST "https://upload.box.com/api/2.0/files/content" \
                               -H "Authorization: Bearer $developer_token" \
                               -H "Content-Type: multipart/form-data" \
                               -F attributes="{\"name\":\"$filename\", \"parent\":{\"id\":\"$folder_id\"}}" \
                               -F file=@"$path"
done
```

To make it work you should replace values of `path_to_folder_with_files`, `developer_token` and `folder_id` variables. Also can you tell me what it the size of the files you try to upload? Is there any pattern that the execution blocks on small or big files?
Waiting for your answer to continue investigation.
Best,
@lukaszsocha2
