### ISSUE TITLE
wrong URL path to FOLDER

### ISSUE THREAD

**Issue by jcreem1** [box/box-python-sdk#741]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
-Trying to call get_folder = client.folder(folder_id = 'folder_id').get() and getting a 404 response. 
-The GET response in the error indicates the URL to the folders sub directory but it lists it as the following - I mask a few things to prevent identification:
-"GET [https://[my domain].app.box.com/folders/[folder_id]" 404 0
- My Box account URL shows the file path to the folder as https://[my domain].app.box.com/folder/[folder_id]
- The difference being the folders vs folder sub directory
- Is this causing the response to fail? If so, is there an adjustment in the source code I can make to call /folder/ not /folders/?  
-
### Steps to Reproduce
- run client.folder(folder_id = 'folder_id').get()
- see error

### Expected Behavior
- list content of folder after providing folder_id

### Error Message, Including Stack Trace
-"GET [https://[my domain].app.box.com/folders/[folder_id]"](https://[my domain].app.box.com/folders/[folder_id]%22) 404 0
{'Date': 'Fri, 10 Jun 2022 15:48:06 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000'}
b''

### Versions Used
Python SDK: boxsdk==3.3.0
Python: Python 3.10.4

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
HI @jcreem1 
Thanks for reaching out to us!

I see in your stacktrace that the SDK tried to call
`https://[my domain].app.box.com`
which is rather unusual, as by default the sdk uses the following base url
`https://api.box.com/2.0`
Have you changed the SDK's default BASE_API_URL address (or other configuration)? This could be the reason why you are getting a 404 response.


>  Is this causing the response to fail? If so, is there an adjustment in the source code I can make to call /folder/ not /folders/?

No. `/folders/:folderId` endpoint in the API returns information about the given folder. You could see the example here https://developer.box.com/reference/get-folders-id/. You could also try the cURL example on this website to see if the problem is with the SDK itself.

`curl -i -X GET "https://api.box.com/2.0/folders/:folderId" \
     -H "Authorization: Bearer <ACCESS_TOKEN>"`

Hope this helps

**Comment by jcreem1** [comment]
Hi there,

Thanks for the response.  The https://[my domain].app.box.com is correct. The domain references my company's working Box account. 

To add further context I can run client.get_url('folder/[folder_id]') and a hyperlink of 

https://[my domain].app.box.com/folder/[folder_id]

is returned that takes me directly to my Box web app folder. The key here is that I supply the "folder/" in the get_url() where as client.folder(folder_id=[folder_id]) will use "folders/" which is incorrect in my case. 

I figured out a way around this issue by running the following syntax:

json_response = client.make_request('GET', 
                                        client.get_url('folder/[folder_id')
                                         ,).json()

However, it fails and the following exception is displayed:


BoxAPIException: Message: Non-json response received, while expecting json response.
Status: 200
Code: None
Request ID: None

As expected the URL that prints out takes me directly to my Box folder. 

Any idea what this BoxAPIException message is supposed to convey?  I add .json() to the make_request() like it says in the README file on github. I think the request goes through since the return status is 200.

Thanks

**Comment by antusus** [comment]
Hi @jcreem1,

I understand that you have your custom domain. However i think `https://[my domain].app.box.com/folder/[folder_id]` is only for Box web application. If you want to call API than you should refer to:
https://developer.box.com/reference/
There you could see that you are using wrong URL to access folder.
If you haven't changed base URL of the client than your code
```json_response = client.make_request('GET',
client.get_url('folder/[folder_id')
,).json()
```
will call
`https://api.box.com/2.0/folder/:folder_id` - which is wrong. 
You can check that with using printing: 
```print(client.get_url('folder/[folder_id'))```
This will return URL generated using client settings.

The proper URL to access api should be:
`https://api.box.com/2.0/folders/:folder_id`
```json_response = client.make_request('GET',
client.get_url('folders/0')
,).json()
```

I cannot reproduce getting 200 error. That is why we would like you to share information on how are you setting up your client. You can replace your domain with any string byt please show us what you are doing.
