### ISSUE TITLE
Is there a way to get folder_id based on webhook_id created on it?

### ISSUE THREAD

**Issue by mingchun-zhao** [box/box-python-sdk#767]
Hi, 
I'm looking for an boxsdk API to get folder_id from the associated webhook_id.
Any ideas?

**Comment by antusus** [comment]
Hi,

please check documentation at https://developer.box.com/reference/get-webhooks-id/

When you get webhook details you should be able to get its target and target ID.

**Comment by mingchun-zhao** [comment]
got it, thanks.
