### ISSUE TITLE
total_count of users broken in API

### ISSUE THREAD

**Issue by lkabongoVC** [box/box-python-sdk#77]
The total_count field returned by the API seems to have an incorrect value in most requests, it does not cause much trouble if people use iterators over results instead of ranging on total_count but it doesn't serve as a shortcut to know the appropriate number of entries (i.e. users, groups?, ...).

**Comment by jmoldow** [comment]
Have you seen this in cases besides what we discussed in #76 for users and groups?

**Comment by lkabongoVC** [comment]
I've checked folders and files and they work properly AFAIK. Can't really remember if it was only for users. Renamed the issue, but it can be removed/closed since it's API more than sdk related.
