### ISSUE TITLE
Created folder through boxsdk not showing in the app.box.com web interface

### ISSUE THREAD

**Issue by bmsan** [box/box-python-sdk#773]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Using the box-python-sdk I have created a folder under the root("0") parent.
Running the script again I can see that the folder was indeed created. (and it's id is consistent with the previous run).

Going to the web interface https://app.box.com/folder/0 I do not see that folder created. 
I've also tried accessing https://app.box.com/folder/folder_id_returned_by_boxsdk but it tells me `Oops! We can't seem to find the page you're looking for.`

I'm logging in using App Token (Server Authentication). I am using the  OAuth2 function and setting only the access_token.

### Steps to Reproduce

```
from boxsdk import OAuth2, Client

def get_create(client, folder_name, parent="0"):
    for item in client.folder(parent).get_items():
        if item.name == folder_name:
            return item.id
    return client.folder(parent).create_subfolder(folder_name).id


auth = OAuth2(
    client_id=None,
    client_secret=None,
    access_token="your_actual_token_here", # <- add a valid token here
)
client = Client(auth)

user = client.user().get()
print(f"The current user ID is {user.id}")


folder_id = get_create(client, "new_folder")
print(folder_id)

```

**Comment by antusus** [comment]
Hello @bmsan,
App Tokens authorise application to work in a Service Account space which is separated from the user space. That is why you cannot see the folder in your account.
[App Tokens](https://developer.box.com/guides/authentication/app-token/)
If you did follow [those instructions](https://developer.box.com/guides/authentication/app-token/app-token-setup/) there is no way of sharing this folder with any user. You would need JWT (or CCG) account to do that.
