### ISSUE TITLE
Is there a maximum length for HTTP Response Header and Body included in a notification from V2 webhooks?

### ISSUE THREAD

**Issue by mingchun-zhao** [box/box-python-sdk#774]
Hi there, 
I would like to save the HTTP Header and Body for V2 webhooks notifications,
Is there a maximum length for HTTP Response Header and Body included in a notification from V2 webhooks?

**Comment by antusus** [comment]
Hi @mingchun-zhao ,

Thanks for submitting this question! We will take a look and get back to you ASAP!

@antusus

**Comment by antusus** [comment]
Hello @mingchun-zhao,

I've asked service owners but they have not specified any limit. So this response follow HTTP specification.

**Comment by mingchun-zhao** [comment]
Hi @antusus,

Thanks for your answer, got it.
