### ISSUE TITLE
download multiple files to make up for not being able to download folders 

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#78]
i am trying to download the contents of folder which are all files to the my hard drive and this is the code i have been using i have tried different variations of it but all of them print only the last item in the list to all the files i want the name of the file in box to be matched in my machine. 

```python
for i in seed:
    new_download=open(i,'w')
    print (i)
    new_download.close()
    open_file=open(i,'wb')
    for k in seed_id:
        client.file(k).download_to(open_file)
        print (k)
    open_file.close()
```

**Comment by jmoldow** [comment]
This is because you have a nested for-loop. Try this:

```python
for i, k in zip(seed, seed_id):
    with open(i,'wb') as open_file:
        client.file(k).download_to(open_file)
```

**Comment by danyal123** [comment]
wow I get it now thank you
