### ISSUE TITLE
Box Search API: 400 Bad Request when offset up to 10000

### ISSUE THREAD

**Issue by chinh-pd** [box/box-python-sdk#797]
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, [for reference](https://support.box.com/hc/en-us/community/posts/7390857656723-400-Bad-Request-When-Offset-is-10000)).

### Versions Used
Python SDK: 3.5.0
Python: 3.7

![image](https://user-images.githubusercontent.com/113652238/216080451-7e0f4d99-3259-45d3-8fe2-93bca0e8196f.png)

**Comment by lukaszsocha2** [comment]
Hi @chinh-pd,
thanks for reaching us out. The issue you reported is not Python SDK bug, but the standard behaviour of API. See endpoint documentation: https://developer.box.com/reference/get-search/. The `offset` param has description: `Queries with offset parameter value exceeding 10000 will be rejected with a 400 response`. If you have any further question regarding Box API please reach Box Support.
Best,
@lukaszsocha2
