### ISSUE TITLE
event based trigger

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#82]
hey i am trying to write a code that would intiate sub_folder creation upon the creation of a parent folder i am trying to use the events module for this but am having issues with the stream_position part 
this is the code i have so far it for some reason does not detect any events at all 

```python
def events_python(stream_position):
     try :
                  Ev=client.events().get_events(limit=1000,stream_position=stream_position)
                  nxt_stream_pos=Ev['next_stream_position']
                  print (nxt_stream_pos)
                  event_list=client.events().get_events(limit=1000,stream_position=nxt_stream_pos)
                  jsone= (event_list['entries'])
                  dicts={}
                  for k in jsone[0]:
                        if k == None :
                             break
                  dicts[k]=[d[k]for d in jsone]
                  et=dicts['event_type']
                  print (et)
                  item_type=dicts['source']
                  print (item_type)
    except:
                  print ('\n', 'No new events have occured since the last stream position')
#events_python('now')


def trigger():
    if et == 'ITEM_CREATE'
        ("execfile('onboarding.py')")
    else
        break
```

**Comment by danyal123** [comment]
i am sorry for some reason my code blocks are not showing up

**Comment by jmoldow** [comment]
I see three things that don't look right about this code sample. First, you don't seem to be calling your trigger() function anywhere (and that function also won't work). Second, I think your for-loop should look like:

```python
for k in jsone[0]:
    dicts[k] = [d[k] for d in jsone] # this should be inside, not outside the loop
```

Third, you are throwing away all the events that occur between ``stream_position`` and ``next_stream_position``. What you really want to do is process all those events, and then propagate the ``next_stream_position``.

However, there is no need to do that manually. You should use the ``generate_events_with_long_polling`` method on the ``Events`` class. See https://github.com/box/box-python-sdk/blob/master/boxsdk/object/events.py#L105

Your code can look something like:

```python
for event in client.events().generate_events_with_long_polling(initial_stream_position):
    trigger(event)
```

**Comment by jmoldow** [comment]
Also, for future reference, please see https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting for how to use code blocks in Github issues.

**Comment by danyal123** [comment]
long polling is suppose to read the events in real time right so if i get the next stream position and start reading from then i should be aware of all following events right?
this code runs and then times out after a while which makes sense due to the limited time of the access token but it doesn't print any events and since it is a generator i cant print it or call objects from it i just want to extract what type of events occur. is there a sample code that you can recommend i am using python 2.6 on vim  

def event_python(stream_position):
    Ev=client.events().get_events(limit=1000,stream_position=stream_position)
    nxt_stream_pos=Ev['next_stream_position']
    print (nxt_stream_pos)
    event_list=client.events().get_events(limit=1000,stream_position=nxt_stream_pos)
    jsone= (event_list['entries'])
    dicts={}
    for k in jsone[0]:
        if k == None :
            exit
        dicts[k]=[d[k]for d in jsone]
    et=dicts['event_type']
    item_type=dicts['source']
    return nxt_stream_pos
q=event_python(0)


for event in client.events().generate_events_with_long_polling(q):
    print (event)

**Comment by danyal123** [comment]
I tried long polling it is suppose to read events in real time when i run my code it stays on for a while before timing out in which time i simulated events with in box to see if it catches any i got nothing is there a sample code that you can recommend to extract what event occurs in real time a trigger event would be the creation of a folder. 

def event_python(stream_position):
    Ev=client.events().get_events(limit=1000,stream_position=stream_position)
    nxt_stream_pos=Ev['next_stream_position']
    print (nxt_stream_pos)
    event_list=client.events().get_events(limit=1000,stream_position=nxt_stream_pos)
    jsone= (event_list['entries'])
    dicts={}
    for k in jsone[0]:
        if k == None :
            exit
        dicts[k]=[d[k]for d in jsone]
    et=dicts['event_type']
    item_type=dicts['source']
    return nxt_stream_pos
q=event_python(0)
for event in client.events().generate_events_with_long_polling(q):
    print (event)

**Comment by Jeff-Meadows** [comment]
If you just pass ``None`` to ``generate_events_with_long_polling``, it will get the latest stream position for you.

The following code prints events for me:

    for event in client.events().generate_events_with_long_polling():
        print event
