### ISSUE TITLE
Monitor events in subfolders recursively

### ISSUE THREAD

**Issue by annie0467** [box/box-python-sdk#828]
Given a single folder, Is there any way to keep monitoring all of its subfolders  for events(ex: ITEM_UPLOAD, ITEM_DOWNLOAD, etc) and associate it with the specific folder name?

For ex: hierarchy is as follows
/ Main_Folder
 -> A
 -> B
 -> C
 
 There might be more folders in A, B, C
 I need to track events in each subfolder folder
 
I wish to use   generate_events_with_long_polling() 

I have tried creating a monitoring thread on each single folder, but I run into unexpected issues after sometime.

**Comment by lukaszsocha2** [comment]
Hi @annie0467,
by default `generate_events_with_long_polling()` provides ALL events for the authenticated user. So if an action takes place in any directory, you will get an event for it. Event has field `source`, which allow to get more details about event source. It could be one of: [File](https://developer.box.com/reference/resources/file/) / [Folder](https://developer.box.com/reference/resources/folder/) / [User](https://developer.box.com/reference/resources/user/) / [Event source](https://developer.box.com/reference/resources/event-source/) object. See Event object documentation [here](https://developer.box.com/reference/resources/event/). If the event source is File, Folder or Event source, it will have `parent` field, so you can filter out events happening in a specific folder (or a set of folders).
You can use this code snippet to print name of the folder, in which the event takes place:
```
events = client.events().generate_events_with_long_polling()
for event in events:
    event_source = event.source
    if event_source.parent:
        print(f'Got {event.event_type} event in folder: {event_source.parent.name}')
```
Best,
@lukaszsocha2

**Comment by annie0467** [comment]
Thanks for your reply @lukaszsocha2
I was using the exact same code with tweaks of my folder id matching
but I now have figured how to track events in all subfolders using this same code.

My only concern is that even after exception handling, the monitoring code get errors unexpectedly say after a few minutes or so

```
    raise BoxAPIException(
boxsdk.exception.BoxAPIException: Message: Authorization Failed
Status: 404
Code: not_found
```
And I confirmed that there is not authorization problem in the folder path I give 
any suggestions?

**Comment by mhagmajer** [comment]
Hi @annie0467, can you share your monitoring code that errors after a few minutes? We'll try to reproduce on our side
