### ISSUE TITLE
Support for Create Jobs to Terminate User Session API?

### ISSUE THREAD

**Issue by tribloom** [box/box-python-sdk#836]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When will the create jobs to terminate user session API (https://developer.box.com/reference/post-users-terminate-sessions/) be supported?

[api-docs]: https://developer.box.com/reference/post-users-terminate-sessions/

**Comment by antusus** [comment]
Hello @tribloom ,

so far we do not have or plan adding session termination to this SDK. However we do welcome contributions, if you would like to add it.

**Comment by mgrytsai** [comment]
hi @tribloom,

Though we don't have support for session termination API in the python SDK yet, but I just wanted to give a heads up that we've been working on a generation of SDK with full API support. And we are currently in a Public Beta. This [new generation Python SDK](https://github.com/box/box-python-sdk-gen/releases/tag/v0.1.2) is available and you could use that for Session termination API.

Here is a snippet how you could use that:
```
from box_sdk_gen.developer_token_auth import DeveloperTokenAuth
from box_sdk_gen.client import Client

def main(token: str):
    auth: DeveloperTokenAuth = DeveloperTokenAuth(token=token)
    client: Client = Client(auth=auth)

    # Session termination for User by UserId and UserLogin
    client.session_termination.create_user_terminate_session(['you user_ids'], [])
    # Session termination for Group by GroupId
    client.session_termination.create_group_terminate_session(["your group_ids"])


if __name__ == '__main__':
    main('your developer token here')
```
[Click](https://github.com/box/box-python-sdk-gen/blob/main/docs/session_termination.md) here to learn more about session termination in the SDK.
