### ISSUE TITLE
offset limit to get files id versions

### ISSUE THREAD

**Issue by 7orG** [box/box-python-sdk#837]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am using the Python SDK to recover/downloads previous versions of a file. The documentation states that the maximum offset allowed is 9999, but I am able to only set the offset to 999 with a successful response.

Please see https://developer.box.com/reference/get-files-id-versions/

However, using an offset greater that 1000 works for a cURL call

### Steps to Reproduce
Run this script

```
from boxsdk import Client, OAuth2

# Initialize OAuth2, create new Box client instance
oauth = OAuth2(
        client_id='CLIENT_ID',
        client_secret='CLIENT_SECRET',
        access_token='ACCESS_TOKEN',
    )
client = Client(oauth)

try:
    # Set user details and get file object 
    user_id = 'USER_ID'
    user_object = client.user(user_id=user_id).get()
    user_client = client.as_user(user_object)

    file_id = 'FILE_ID'
    file_object = user_client.file(file_id=file_id).get()

    offset = 1000  # Number of versions to skip.
    limit = 10  # Max number of versions to process after the offset.

    # Retrieving all versions
    versions = file_object.get_previous_versions()

    # Skipping the first 'offset' number of versions
    for _ in range(offset):
        next(versions, None)

    # Process 'limit' number of versions after the offset
    for i, version in enumerate(versions):
        if i == limit:
            break
        print(f'Version {version.id}: {version.created_at}')

except Exception as e:
    print(f"An error occurred: {e}")
```

### Expected Behavior
Getting the 10 versions after the 1000

### Error Message, Including Stack Trace
no error thrown in the console

### Versions Used
Python SDK: 3.8.1
Python: 3.11.4

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk/search?type=Issues

**Comment by antusus** [comment]
Hello @7orG ,

you should be able to use offset while getting versions like so:
```python
offset = 0
    limit = 3000  # Max number of versions to get - you can set it to 10010
    pageLimit = 100
    j = 0
    # Retrieving all versions
    while j <= limit:
        versions = file_object.get_previous_versions(offset=j, limit=pageLimit)
        for version in versions:
            print(f'Page {j} Version {version.id}: {version.created_at}')
        j += pageLimit
```
this way you should be able to iterate on all versions that API allows to.

**Comment by 7orG** [comment]
Hello @antusus,

Thank you so much for your fast response, I can get the versions of the file using your recommendation.

Really appreciate it!!
