### ISSUE TITLE
Download ZIP retry loop

### ISSUE THREAD

**Issue by psevertson** [box/box-python-sdk#844]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The `download_zip` call is missing the `skip_retry_codes={202}` parameter, which is causing it to retry `MAX_RETRY_ATTEMPTS` times until it returns the successful response

### Steps to Reproduce
1. Call `client.download_zip()` with a zip name, files to zip, and a writeable stream
2. The download takes a long time to generate, because it gets stuck in a retry loop

### Expected Behavior
Expected the zip download to complete in a quicker time by returning the first successful response

### Versions Used
Python SDK: 3.9.0
Python: 3.9.13

**Comment by antusus** [comment]
Hi @psevertson,

thanks for pointing that out. We are working on a fix.
