### ISSUE TITLE
Error in deleting folder locks

### ISSUE THREAD

**Issue by Sevillesilveira** [box/box-python-sdk#860]
Hi 

I created a folder lock on a folder with id 233490176640 (I am the owner of the folder). 
When I run the following code;
  locks = client.folder(folder_id='233490176640').get_locks()
  lock = locks.next()
  print(f'A lock on a folder with ID {lock.folder.id}')

I get the below output:
![image](https://github.com/box/box-python-sdk/assets/121432447/b33f3970-c397-4ea0-b710-95ab2741edaa)

But when I try to delete the lock, I get the following output:
![image](https://github.com/box/box-python-sdk/assets/121432447/10081d25-2b96-466e-9bc1-b75b789872bf)
![image](https://github.com/box/box-python-sdk/assets/121432447/91734a51-57e7-4d91-a7b4-afcbd5e065d8)

Kindly let me know why I can't delete the folder lock

**Comment by arjankowski** [comment]
Hi @Sevillesilveira,

In order to delete a `folder_lock` you have to pass a `folder_lock_ID` instead of `folder_ID`.
Please take a look at this documentation [here](https://github.com/box/box-python-sdk/blob/main/docs/usage/folders.md#delete-a-folder-lock)

Regards,
Artur
