### ISSUE TITLE
Chunked uploader hangs for large files

### ISSUE THREAD

**Issue by axatha** [box/box-python-sdk#870]
When I try to upload a file of size > 2GB or so, chunked uploader code hangs and upload never completes. I tried to add some debug logs and its seems to be hanging when the futures (trying to upload parts in parallel) are waiting to complete. Looks like some futures are just not completing. 

Using python SDK version '3.9.2'

However, when I upload all parts sequentially uploads are successful.

**Comment by axatha** [comment]
folder = client.folder(folder_id).get()

    uploader = folder.get_chunked_uploader(file_path, file_name)

    try:
        file = uploader.start()
    except BoxAPIException as err:
        if err.code == "upload_session_not_found":
            file = uploader.resume()
        else:
            raise err

**Comment by mhagmajer** [comment]
Hello @axatha. Thanks for posting! Can you clarify if the code you posted is the code causing errors? Also, please consider using https://github.com/box/box-python-sdk-gen/ which is our new generation of Python SDK. Upload related errors can sometimes be difficult to debug. Are you using a proxy? How long does the upload operation take before it hangs on your end with a large file?

**Comment by axatha** [comment]
Yes, I pasted the code I am using. I am not using a proxy and  it usually hangs after a few mins.

**Comment by congminh1254** [comment]
Hi @axatha 

It seems like the uploader have some issue with the internet connection during upload. Can you try with lower upload thread by following [this configuration](https://github.com/box/box-python-sdk/blob/main/docs/usage/files.md#automatic-uploader) and check if it can be upload successfully?

And just to confirm, the issue will happen all the time or only sometime or with some special files?

**Comment by axatha** [comment]
I have an upload bandwidth of 700Mbps. So the failure was def not because of slow internet. Are you able to validate that you can upload a file > 10GB using chunked uploader?
