### ISSUE TITLE
Searching in ancestor folders

### ISSUE THREAD

**Issue by britnyblu** [box/box-python-sdk#882]
### Description of the Issue
Using the search functionality with "ancestor_folders" parameter does not work because it tries to join integers
`            additional_params['ancestor_folder_ids'] = ','.join([folder.object_id for folder in ancestor_folders])
`
They must be changed to strings first.
https://github.com/box/box-python-sdk/blob/main/boxsdk/object/search.py#L225

### Steps to Reproduce
parent2=client.folder(12345)
parent1=client.folder(12346)

for h in box_obj.client.search().query(query='ABCD',content_types=['name'],ancestor_folders=[parent1,parent2],result_type="file"):
    print(h)

Error:
`File ~/.local/lib/python3.10/site-packages/boxsdk/util/api_call_decorator.py:63, in APICallWrapper.__get__.<locals>.call(instance, *args, **kwargs)
     60     instance = instance.clone(instance.session.with_default_network_request_kwargs(extra_network_parameters))
     62 method = self._func_that_makes_an_api_call.__get__(instance, owner)
---> 63 return method(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/boxsdk/object/search.py:225, in Search.query(self, query, limit, offset, ancestor_folders, file_extensions, metadata_filters, result_type, content_types, scope, created_at_range, updated_at_range, size_range, owner_users, trash_content, fields, sort, direction, **kwargs)
    223 additional_params = {'query': query}
    224 if ancestor_folders is not None:
--> 225     additional_params['ancestor_folder_ids'] = ','.join([folder.object_id for folder in ancestor_folders])
    226 if file_extensions is not None:
    227     additional_params['file_extensions'] = ','.join(file_extensions)

TypeError: sequence item 0: expected str instance, int found`

**Comment by congminh1254** [comment]
Hi @britnyblu 

I believe that while initialize a folder object, the ID should be string. For example:
```
client.folder(folder_id='22222')
```

Please check if it works for you.

Bests,
Minh

**Comment by britnyblu** [comment]
my mistake, thanks!
