### ISSUE TITLE
Implement Byte Range requests for file content downloads

### ISSUE THREAD

**Issue by jmoldow** [box/box-python-sdk#95]
Downloading files from the API supports the `Range` header (https://box-content.readme.io/reference#download-a-file) from RFC 7233 (http://tools.ietf.org/html/rfc7233). The `content()` and `download_to()` methods should be enhanced to allow for Range requests.

The Box API only supports a subset of RFC 7233, but it'd be nice to build this in such a way that it'd be backwards compatible for the SDK to enable the full RFC 7233 spec, if Box ever began to support the full spec.

An initial proposal was presented in #56. I've begun work on a more extendable and Pythonic proposal.

**Comment by mattwiller** [comment]
As [documented here](https://github.com/box/box-python-sdk/blob/master/docs/usage/files.md#download-a-file), the `byte_range` option has been added to the file download methods.
